### ISSUE TITLE
Big performance drop inside LeadDeveloper view

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#101]
Together with all of the progressbars you get a really big performance drop. 
Maybe the progressbars should have reduced refreshing when the Lead Developer view is up?

**Comment by BrutalCSkakan** [comment]
Actually it feels like it is all modal windows that get this performance issue

**Comment by InDieTasten** [comment]
Hmm... well, since @jhovgaard doesn't want to reveal the shortcut to open developer tools, it's all on himself to determine the cause of that :D #Karma

**Comment by BrutalCSkakan** [comment]
The button over TAB is opening the dev-tools for me. If you're talking about Chrome Dev Tools?

**Comment by InDieTasten** [comment]
Yes, I'm talking about chrome dev tools. One could now start profiling to see if it's some inefficient javascript, or if there are really unusual graphics updates that make chrome rerendering and compositing inefficient.

@BrutalCSkakan Thank you for all the feedback you provided thus far btw. It's really great to have people like you in the player base!

**Comment by jhovgaard** [comment]
Haha. It is indeed $digests happening and causing the lag. It's mostly just not optimized angular code.

**Comment by jhovgaard** [comment]
Fixed.
