### ISSUE TITLE
Faster way to send workers for vacation

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#105]
I just hit some type of "milestone" when people were getting too much -mood and therefore I sent them to vacation. It's a little bit irritating due to the amount of clicks that's needed to send all of the workers for vacation. 
Maybe there should be some option for this under the "Employees" tab?

**Comment by jhovgaard** [comment]
Good idea. Like a mass-edit feature. Let's plan it.

**Comment by jhovgaard** [comment]
Planned for HR Manager. Closing this issue.
