### ISSUE TITLE
Bugging red indicator

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#109]
The red indicator underneath the item dissapears when hovring in & out from outside the workspace

http://www.filedropper.com/noredindicatior

**Comment by InDieTasten** [comment]
Can you please submit media in form of direct links to images and gifs?

If you really need to post something different, like a zip archive or your save-game, please use the upload feature from within github, instead of commercial file sharing services. That would be really great, thanks :)

**Comment by jhovgaard** [comment]
I've been the video. This will be fixed when we rewrite the grid-system to use jQuery instead of Angular.

**Comment by InDieTasten** [comment]
Link-rot occuring. It's funny cause I told you @BrutalCSkakan  :tongue:

**Comment by jhovgaard** [comment]
Probably never gonna that due to cost of development. Sorry :(
