### ISSUE TITLE
Show latest developed module/component

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#115]
When you're not using the Auto Repeat you often get into situations where you can't rememeber the last job of a worker.
It should really show what the previous developement was.

**Comment by InDieTasten** [comment]
how does the last job a developer did matter?

**Comment by BrutalCSkakan** [comment]
I got x amount of developers, basically one for each component. 
I also got x amount of Lead Devs for modules, these are also having one module each to handle.
But sometimes I have to change job for one of the Lead Devs in order to get the right amount of modules in time, and now I start to lose my memory of what that Lead Dev's job was before I changed it.

**Comment by jhovgaard** [comment]
How about adding job/development history for all task-based employees?

**Comment by jhovgaard** [comment]
Latest build shows that this is indeed a required feature (when running large organizations).

Let's approve this suggestion: https://github.com/hovgaardgames/startupcompany/issues/188

Closing this one.
