### ISSUE TITLE
Auto Repeat doesn't re-activate after Manager comes back from vacation

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#116]
As the title says. 
I had a bunch of developers handling different developments, these were connected to a specific manager that I later sent to vacation. 
The developers stopped Auto Repeat(Which is correct) but didn't "re-activate" after the manager came back. 

This is probably something to discuss as it's not really a bug, but maybe a nice feature to have. 
BUT it can also be some type of "worker enhancement" feature that you have to get from experience/research points or similiar. 

We talked about "traits" on Discord before, this might be a good candidate for this type of feature?

**Comment by InDieTasten** [comment]
Because you went a bit vague in the end of your description, I marked this as discussion. Whatever outcome this discussion might have shall be redefined in a clean issue :)

Thanks

**Comment by jhovgaard** [comment]
I get how this is annoying. Created new issue with a solution: https://github.com/hovgaardgames/startupcompany/issues/219
