### ISSUE TITLE
Non-purchased areas should be designed

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#118]
These non-purchased areas are still in the house but not bought, therefore there should be an existing wall that we basically just "tear apart" when we buy the area. 

The walls could be designed as some type of "Under construction" design. Together with planks on the floor & non finished walls, no painted walls and different working tools.

**Comment by InDieTasten** [comment]
Not sure about the effort of implementation, but to me this seems like:
Big effort, low value

**Comment by BrutalCSkakan** [comment]
Absolutetly no priority, but details are important for the final version

**Comment by jhovgaard** [comment]
Removed areas. Not relevant anymore.
