### ISSUE TITLE
Optimization: Game saves when idle

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#129]
I've been idle for 12 hours, the game still saves every 10 seconds. This can be optimized when it's paused in the background to prevent uneccesary load from the program. 

An example could be to not be saving then game when it hasn't been the active window for around 10 minutes. 

**Non-prio**

**Comment by InDieTasten** [comment]
When it's paused and the window is inactive, we don't need saving at all. Maybe one last time, when focus of the window is lost.

**Comment by InDieTasten** [comment]
This is a very mobile-ish enhancement though. So I agree with non-prio, as this can be assumed to be a rare case.

**Comment by jhovgaard** [comment]
Decreased size of savefiles instead.
