### ISSUE TITLE
Find a way to help CTO release versions

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#130]
Currently only one CTO can work one a release. It's going to take too much time when larger framework gets unlocked.

**Comment by InDieTasten** [comment]
I don't think the idea was to add multiple CTOs, as the 'Chief' part kind of implies, that you only have one of them.

**Comment by InDieTasten** [comment]
Maybe a CTO can level up in experience over time and tier milestones to get faster at releasing things

**Comment by jhovgaard** [comment]
@InDieTasten @BrutalCSkakan I was thinking something like a "Assistant" that could help, but not a great idea tho.

**Comment by jhovgaard** [comment]
New version with fast releases does not require this functionality anymore. Closed.
