### ISSUE TITLE
Not able to upgrade employee

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/startupcompany#133]
When trying to upgrade an employee to tier 3 the tooltip kept stating that I needed to fulfill all requirements for tier 3, but I was able to hire a new tier 3 employee.

It could be that I just don't know the mechanics of what the requirements are for the different tiers.

**Comment by BrutalCSkakan** [comment]
This relates to #35. Can't remember if the new employeesystem is using the same rankingsystem as the ones you're playing on.

**Comment by InDieTasten** [comment]
Is this still relevant?

**Comment by WodeCraft** [comment]
I do not think so. I have not encountered it the last couple of times I have played, but will test the latest beta tomorrow :)

**Comment by InDieTasten** [comment]
@WodeCraft results?

**Comment by WodeCraft** [comment]
Not an issue. Have upgraded several empoyees to tier 3/expert without any issue.

**Comment by InDieTasten** [comment]
Fixed by black magic
