### ISSUE TITLE
Upgrading Sales employee results in tier 2 jobs

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/startupcompany#135]
I noticed (in beta 5) that I had upgraded a sales employee from T1 to T2 and the employee was in the process of finding a job. The indicator stated that it was a T1 job being found but when it completed, the result was a T2 job.

Not sure if this was a single fluke or if it can be reproduce. I will try and reproduce just to be sure.

**Comment by WodeCraft** [comment]
I have not been able to reproduce this error in Beta 7

**Comment by InDieTasten** [comment]
Fixed by black magic
