### ISSUE TITLE
Unmanageable list of blueprints

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/startupcompany#137]
It is just a small thing and nice to have, but the list of blueprints is getting a bit unmanageable when you get to T3+. Even with only one Lead Developer the amount of blueprints and how to find them when you need to create some components, modules or products can get a bit tricky, but when you get more than one Lead Developer, the sorting of the list of blueprints is different which makes any "system" or "muscle memory" you might have had go down the drain.

It would be nice if the list of blueprints either always was sorted the same way for all Lead Developers, or better if the layout itself was modified, so it would be easier to manage.

**Comment by jhovgaard** [comment]
I'm suggesting that we completely remove the inventory from this view and instead show blueprints in full size, like this: 
![image](https://cloud.githubusercontent.com/assets/1388347/22182307/98fff060-e0a2-11e6-8769-4f193e9a4a6d.png)
(Ignore the weird layout).

What do you guys think?

**Comment by roastchicken** [comment]
@jhovgaard I think it would be good to have something like that, with a few additions:

- A tooltip that shows which items you need to 'craft' a module when you hover over it.
- Showing the two items being used to 'craft' the current item in the left hand side, as it is in the current build. (Beta 7 was the last time I tested this, but I don't imagine it's changed in Beta 8.2)

**Comment by jhovgaard** [comment]
New lead dev view does not have this issue. Blueprints have been removed.
