### ISSUE TITLE
Changes notes: Limits for what can be done

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/startupcompany#138]
Is it possible that the change notes for future beta versions contain information about what limits there are in the beta. I don't mean every limit, but something like:
- You can only upgrade to tier 3
- Designers do not get extra components/modules above tier 2

Just to let the people who test the beta's know what limits there are so we don't report something as a bug which is actually just a known limitation in that beta.

**Comment by jhovgaard** [comment]
Will do this for future releases, thanks!
