### ISSUE TITLE
Add punishment for cancelling contracts

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#139]

**Comment by jhovgaard** [comment]
Just opened this for discussion:

How are we going to punish the players? Should it be an instant money punishment, like 1% of potential income?

Or something else?

**Comment by markrichey** [comment]
Lower contract values going forward from the client? Only a small % reduction but permenant? Simulates a bad reputation building over time.

**Comment by jhovgaard** [comment]
Implemented a version where you have to pay a pre-defined punishment price.
