### ISSUE TITLE
Add Contract penalty cooldown

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#140]
If the client cancel as contract a cooldown should be added for that client, meaning you won't receive any new contracts for this client within the next 30 days.

**Comment by markrichey** [comment]
If a player cancel's too many contracts should the "industry" as a whole enforce a penalty (less than the 30 days) but represent the idea that these company's talk to each other?

**Comment by jhovgaard** [comment]
@markrichey I think we have to figure out how to symbolize this to the player. My idea is that the player will actually see the contracts coming in from "blacklisted companies" and I believe that's gonna be a big enough punishment. 

Also because we don't have that many companies offering contracts, so you get to the point of being blocked from everyone quite fast I think.

**Comment by markrichey** [comment]
@jhovgaard that sounds good. As the players company get larger anyway the incentive to cancel will go down due to overheads etc and the need for those contracts.
