### ISSUE TITLE
Purchases fail silently

### ISSUE THREAD

**Issue by PeachIceTea** [hovgaardgames/startupcompany#142]
Purchases will fail without an explanation why. This happens when you have not enough money, have reached the maximum amount of workstations or don't even have any rent space. I think a tool tip should appear telling you the reason why the purchase failed. 

It would be even better if they were grayed out to tell the player immediately that they can't purchase that item, maybe including the reason. However then they should be distinguishable from items that aren't unlocked yet.

**Comment by Zolor** [comment]
Maybe add that also if you try to buy a desk but have reached the maximum amount of desks that you get an error/explanation for that too

**Comment by PeachIceTea** [comment]
Yeah. That's what I meant with "aren't allowed".

**Comment by markrichey** [comment]
Should the front end even offer you the option to buy a desk if you dont have space? Maybe some pre filtering of the list based on what you can actually have and use would be good as it will force the player to think why then say, for example, "oh I need to buy more space before I can have more desks".

**Comment by jhovgaard** [comment]
Added alert when trying to purchase something too expensive.
