### ISSUE TITLE
Loose conditions are confusing

### ISSUE THREAD

**Issue by PeachIceTea** [hovgaardgames/startupcompany#143]
Right now you loose if you drop below -10k cash even if you could theoretically just get a loan and play on. 

I think that if you don't already have 3 loans the game should automatically give you one (maybe with worse conditions than the ones available normally). Maybe this should happen when you drop below 0 cash. You loose if you already have 3 loans and drop below 0.

Additionally the game shouldn't let you spend money that drop you below 0 (or -10k if that limit is kept).

**Comment by InDieTasten** [comment]
Has been discussed on discord.

Summary:
When dropping below certain balance, like $-10,000.00, offer player to choose a loan. If no loan is available to take, it's gameover.

**Comment by jhovgaard** [comment]
Implemented
