### ISSUE TITLE
"Send all employees under<50% mood to vacation"-button

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#146]
As the title says, we NEED THIS BUTTON.

**Comment by BrutalCSkakan** [comment]
The button will bring up a menu just like the "Manager" view. The view will tell us everyone that's going to be sent to vacation. You should be able to enable/disable those you want/don't want to send to vacation

**Comment by jhovgaard** [comment]
Hmm... Making sure mood is high is one of the objectives of the game. I'm not sure making such a convenient feature is doing anything good to the game.

**Comment by InDieTasten** [comment]
Yeah. I feel like that's part of the gameplay. At least in the beginning. When you reach a certain size I can see why it would get a bit annoying. This automation could  be a task for a high level HR manager or similar. This would then escalate to being a feature rather then an enhancement I guess. :D

**Comment by jhovgaard** [comment]
Having this as a feature of the HR Manager sounds like a great idea actually. We could do something like "Automatically send employees on vacation when lower than 30% happiness"

**Comment by InDieTasten** [comment]
I'll take this as approvement then ^^

**Comment by markrichey** [comment]
@InDieTasten I like this idea allot because it also serves to constrain the player from just working the employees into the ground. If a whole load of them could just be sent on holiday that's quite amusing!

**Comment by jhovgaard** [comment]
Consolidated this with https://github.com/hovgaardgames/startupcompany/issues/146
