### ISSUE TITLE
Create a progressbar in the background of the Contracts view

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#147]
http://i.imgur.com/j6Yazf1.png

This print gave me an idea
The background should be a big progressbar
keep the background just as it is, but make it fade just like a standard progressbar?

**Comment by InDieTasten** [comment]
You mean for the "deliver now" button, right? So the button becomes a progress bar, that turns back into a button once complete?

**Comment by BrutalCSkakan** [comment]
No I mean the whole background of each contracts. The color should be the same color as the disabled button, and if you got all of the components/modules then it turns into a little bit brighter green

**Comment by InDieTasten** [comment]
hm, seems very big. not sure I like that. I'd be ok with just the button, but thats just an opinion.

**Comment by BrutalCSkakan** [comment]
So you'd rather have this "boring" gray background? The progressbar will just give some more color into the view

**Comment by InDieTasten** [comment]
@BrutalCSkakan I'd have to see it in order to tell. It must be a very light green that fills the areas. It also messes with the typography on top. All the sudden you have grey on green, which looks really bad

**Comment by WodeCraft** [comment]
I have to agree with @InDieTasten here. To make the whole background on big progressbar sound to me like it is going to be cluttered and "noisy". But I do agree that it would be a nice feature to see the progression of the contract.

**Comment by jhovgaard** [comment]
I created an example of the background approach:
http://i.imgur.com/BuNbHD2.png

Let me know what you think.

**Comment by BrutalCSkakan** [comment]
This is exactly what I tried to say, I approve that picture.

**Comment by InDieTasten** [comment]
Looks good. Maybe the green needs to be a touch lighter for me to not dislike the gray on green thing I mentioned
