### ISSUE TITLE
A small percent of contracts getting cancelled by the buyer

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#148]
To simulate reality, the work you're doing should be able to be randomly postponed, cancelled or to even raise the amount of modules/work needed for the job

**Comment by InDieTasten** [comment]
This is a big change. I think it'd made sense, if the contracts with potentially changing requirements are at least flagged as such.

**Comment by jhovgaard** [comment]
I really have bad experience with these random events, when players have been putting effort into completing the task. I tried it before and got a lot of negative feedback. Closing this one, sorry :-)
