### ISSUE TITLE
Way to remove rented area

### ISSUE THREAD

**Issue by NoraNava** [hovgaardgames/startupcompany#150]
I accidentally pressed on one of second floor rent areas (well, i accidentally pressed on floor changing button and didn't understand why my area isn't rented anymore and pressed that rent button again) and, as I assume, now i'm paying for area that is unused. Maybe it should be able to un-rent on something like that?

**Comment by InDieTasten** [comment]
Isn't there a popup asking you, whether you really want to rent the area?
Even if not, you still did 2 actions in a row by accident, which sounds very unlikely to happen to any other users. And since it probably happened right in the beginning of your game, the consequence would just be to restart the game.

**Comment by WodeCraft** [comment]
@InDieTasten It is true that something like this will most likely start at the beginning of the game and you could just start over, but I must admit I agree with @NoraNava, a feature for "un-renting" an area will be a nice feature to implement at some point.

**Comment by InDieTasten** [comment]
@WodeCraft Yeah, I guess you are right. There should be a way to no longer rent a space.

I am still not sure how you where you would put that option though?
Maybe add an extra "rendering mode" that adds "Unrent" buttons to owned spaces. The mode could be togglable in the inventory screen and the buttons will be disabled, if there are items in the space that need to be moved away first, which must also be explained somewhere, either as tooltip or general text that appears in that "mode".

Someone having better ideas? Not very satisfied with the "findability" of that "mode" in the inventory menu.

**Comment by jhovgaard** [comment]
It's a good idea, but I'm closing this suggestion for one reason: it's good that you can make bad decisions.

You will eventually be in need of the area anyways, but now you learned why renting areas should only be done when in need.

Also, I think the originally experience that caused this issue to be created was combined with a bug on the area-renting functionality.
