### ISSUE TITLE
Marketer 

### ISSUE THREAD

**Issue by KearnsyUK** [hovgaardgames/startupcompany#152]
I personally think there should be a marketer job to promote your products which say unlocks at level 7 instead of the HR.

**Comment by jhovgaard** [comment]
Suggestion to Marketer employee type:
Marketer can generate a campaign. It's a pre-paid and consists of the following variables:
Campaign:

1. Product: Existing products
2. Platform: Web, Mobile, Desktop
3. Budget: Easy, Moderate, Aggressive
4. Duration: 1 day, 3 days, 5 days

The combination of these variables will result in:
Price Per Hour: $10
Estimated Users Per Hour: 10

I'm not sure if we should show the users per hour. What do you guys think?

**Comment by jhovgaard** [comment]
Great suggestion:

AFRAram : cant you add a perk (having a market research) that unlocks the price per hour and estimated users per hour?

**Comment by jhovgaard** [comment]
Marketer implemented. Moving to Beta 8 for AFRA's suggestion.
