### ISSUE TITLE
Push to Steam Greenlight

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#157]
* [x] Produce 5 new screenshots
* [x] Produce video material
* [x] Write a new game description

**Comment by jhovgaard** [comment]
Done! Just waiting for Greenlit.

**Comment by BrutalCSkakan** [comment]
Got greenlit, now getting them Steam dollars.

**Comment by InDieTasten** [comment]
Btw, will @jhovgaard hand out steam keys for pre-orderers and will there be an experimental/playtesting feed as beta in steam? So mäny q-estions D:
