### ISSUE TITLE
Contract windows isn't scrollable

### ISSUE THREAD

**Issue by dennisschott** [hovgaardgames/startupcompany#165]
If the requirements are floating on two lines, the confirm button isn't clickable.
overflow-y scrollable required

**Comment by InDieTasten** [comment]
Version please

**Comment by AlainMus** [comment]
it is in version 7 and 8(this i'm sure) the button is clickable but only the very top edge off the button is visible

**Comment by jhovgaard** [comment]
Extended width of dialog to allow 2 lines of components.
