### ISSUE TITLE
New Messages look equal to the headline

### ISSUE THREAD

**Issue by prempador** [hovgaardgames/startupcompany#166]
Already talked to Jonas about this. When having an unread message it has the same size, font and color as the headline telling you what is what. 

Possible solutions: 
- Make a thin border around the messages
- Change the color of the headline

**Comment by InDieTasten** [comment]
@jhovgaard add `s:appoved` label when you agree to his enhancement

**Comment by jhovgaard** [comment]
Greyed out headline
