### ISSUE TITLE
Save files are breaking

### ISSUE THREAD

**Issue by LapinoLapidus** [hovgaardgames/startupcompany#167]
The version I'm using is Beta 7. 
I've tried re-installing it with no success.

Let me explain this issue.
First of all, I started a game, when I went to close the game, via the game menu and returned the other day, I couldn't click "Load Game". I've tried to do a make save today, played for a bit and clsoed it, and I couldn't load it again.

~LapinoLapidus

**Comment by jhovgaard** [comment]
Thanks for the report!

Can you attach the content of your Startup Company savegame folder? It should be in Documents/Startup Company

**Comment by LapinoLapidus** [comment]
Hey,
There is no such folder in my Documents.

**Comment by LapinoLapidus** [comment]
This was fixed, the cause was BitDefender Ransomware Protection protecting my precious user folder.

**Comment by InDieTasten** [comment]
What exactly caused the break though? I think if there are file access errors, the game should communicate these to the user

**Comment by LapinoLapidus** [comment]
Hey, I have some pictures from BitDefender Ransomware protection, it's really weird: http://prntscr.com/dxothn http://prntscr.com/dxotvf http://prntscr.com/dxou2j @InDieTasten

**Comment by jhovgaard** [comment]
I've investigated this a bit more.

My guess is that the blocking is based by popularity/reputation. Found this ressource:
http://softwareengineering.stackexchange.com/questions/191003/how-to-prevent-my-executable-being-treated-from-av-like-bad-or-virus

Not much we can do about it for now. Closing the issue.

**Comment by InDieTasten** [comment]
I'd suspect first and last screenshot to be buggy from bitdefender. the only way for @jhovgaard to fix this would probably be to sign the executable. i don't know how that works and what places you have to go to get that verified
