### ISSUE TITLE
Game save breaks. All worker mood set to 10% and cannot advance the day

### ISSUE THREAD

**Issue by tjohns89** [hovgaardgames/startupcompany#169]
Happened to me twice now in beta 7. All of a sudden all of the workers will go into a bad mood and the skip to next day button doesn't work. You press it and it just subtracts your salaries but doesn't advance time. First time was around day 80 and second time was day 189.

**Comment by tjohns89** [comment]
[Startup Company.zip](https://github.com/hovgaardgames/startupcompany/files/709606/Startup.Company.zip)

Added save file

**Comment by jhovgaard** [comment]
Fixed.
