### ISSUE TITLE
Tutorial Loan-Message will pop up even after purchasing a Loan

### ISSUE THREAD

**Issue by prempador** [hovgaardgames/startupcompany#170]
Just a minor bug, but when I press on the play button on the left at the line loan, it tells me where to get my loan. After I purchased one I went back and the message where to get a loan still pops up even when there are no more loans available I can take. 
### Possible fixes: End the tutorial for this line after finishing it.

Files attached.
![screenshot from 2017-01-17 09 18 57](https://cloud.githubusercontent.com/assets/9047327/22012834/57adaf68-dc96-11e6-9eba-666ebb4ce7d9.png)
![screenshot from 2017-01-17 09 19 47](https://cloud.githubusercontent.com/assets/9047327/22012833/57ad34ac-dc96-11e6-8e9b-752c21679d0d.png)

Note: Beta 8.1 Linux Playtest

**Comment by prempador** [comment]
New screenshot added

![screenshot from 2017-01-18 20-44-01](https://cloud.githubusercontent.com/assets/9047327/22080191/f7bd1b00-ddbe-11e6-9568-80f489243f76.png)

**Comment by jhovgaard** [comment]
Disabled tutorials for now. We need to switch over to using videos instead. Too much work into implementing those embedded tutorials.
