### ISSUE TITLE
Mail Quality of Live Change

### ISSUE THREAD

**Issue by prempador** [hovgaardgames/startupcompany#171]
When opening mails there is only a delete button. If you want to go back to your inbox you have to press List on the top left or press the Mail button again. 

Maybe add a back to Inbox button next to the delete button. 

![screenshot from 2017-01-17 09 25 42](https://cloud.githubusercontent.com/assets/9047327/22013006/1ec3a634-dc97-11e6-8a2d-34dc47be1f62.png)

**Comment by InDieTasten** [comment]
What about that breadcrumb bar? Does it not link back?

**Comment by prempador** [comment]
> you have to press List on the top left < 
Yeah breadcrumb bar. Wasn't sure about the name on this one.

**Comment by InDieTasten** [comment]
Oh my bad. Pardon me. Yeah, it seems very _hidden_ .
A back button would be of some help I guess. @jhovgaard

**Comment by jhovgaard** [comment]
Back button added.
