### ISSUE TITLE
Console Error after failed offer on contract (Beta 8)

### ISSUE THREAD

**Issue by AlainMus** [hovgaardgames/startupcompany#172]
Note: only for Beta 8 playtesting
When making an offer on a contract and failing the offer you get the following error in the console.

![image](https://cloud.githubusercontent.com/assets/18419088/22014836/c4bd4fd8-dc9f-11e6-92ec-635d1da868a7.png)

after that it spams the following error every 10 seconds or so

![image](https://cloud.githubusercontent.com/assets/18419088/22014878/f0525f3a-dc9f-11e6-87ff-2819f76f2ea4.png)

**Comment by InDieTasten** [comment]
I'd imagine this is the savegame interval, so i mark it as critical for now

**Comment by InDieTasten** [comment]
Please elaborate whether the errors result in any impact for the player. Is it still saving? Are there other things that no longer work as expected?

**Comment by AlainMus** [comment]
It does not seem to afftect the gameplay in any way.

it's still saving the game, but it actually outputs the error every second.
![image](https://cloud.githubusercontent.com/assets/18419088/22019575/6cf47dde-dcb4-11e6-9fae-3d2d493ca88e.png)
 as you can see after the saving, i get 60* the same error, then it saves again

**Comment by jhovgaard** [comment]
Fixed!
