### ISSUE TITLE
Inventory deleted when merging a medium server (Beta 8)

### ISSUE THREAD

**Issue by AlainMus** [hovgaardgames/startupcompany#173]
When merging components to create a medium server the entire inventory gets deleted.

i also had this issue when creating a small server(manully putting in the components, not using a blueprint)
but i cant seem to reproduce it 100%. sometimes it gets deleted sometimes not.

medium server deletes it 100% off the times so far

**Comment by AlainMus** [comment]
Ok, the problem seems to be not only related to the medium server.

i just had my inventory deleted when merging an authentication module. I was running it at full speed, maybe that has something to do with it?

**Comment by jhovgaard** [comment]
Fixed. Was being caused by all modules requiring more 2 or more of the same component type.
