### ISSUE TITLE
Bug or oversight: Time still advances while you are viewing a contract details

### ISSUE THREAD

**Issue by tjohns89** [hovgaardgames/startupcompany#176]
Ideally time should stop once the contract is open. Otherwise, you can sit on the contract screen let your workers keep producing components to fulfill the deal without time being deducted from the contract length. This isn't really a problem later in the game since the length given to complete contracts far exceeds what you should need. I assume that will change in the future though.

**Comment by jhovgaard** [comment]
Fixed by pausing the game when opening the contract view. Also disabled keyboard shortcuts for resuming the game.
