### ISSUE TITLE
Disable missclicks on current work-object

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#180]
Case: My designer was doing a "Web Design Component", when he started to get close to 95% I spamclicked so he could start the next work as fast as possible. 
BUT when I started to click, he instead stopped the current work and started the new job without finishing the current job.

Maybe right-click should stop the current work? But stop left-clicking from being able to cancel the job

**Comment by InDieTasten** [comment]
Referring to #208 this has been reworked
