### ISSUE TITLE
Send on vacation AFTER work is done & send him the day after

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#181]
It's not logic for a person to go to vacation immediately when told. They should rather go to vacation the next day? 

There should be a prompt asking if the employee should finish his current job before the vacation, or if he just should pause it

**Comment by InDieTasten** [comment]
I like them to go home immediately when told. If you want him to go later, tell him later?

**Comment by BrutalCSkakan** [comment]
I don't have time to tell 10x employees to go to vacation at the same time unless I pause the game. 
But if I start to tell them to go to vacation "tomorrow", then they will all go to vacation at the same time.

**Comment by jhovgaard** [comment]
The player would expect instant action. Closing this.
