### ISSUE TITLE
Change color of the managers on-off button

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#182]
Current case: 
The on/off button for an employee is either light-gray(off) or green(on)

What I'd like to see: 
Light gray if there's no spots left to fill
Dark gray if the manager can add more employees to his work crew
Green if the employee currently is assigned to that work crew

Current:
![image](https://cloud.githubusercontent.com/assets/8394703/22075705/634b685c-ddad-11e6-809a-ed61bad68ecb.png)

What I'd like:
![image](https://cloud.githubusercontent.com/assets/8394703/22075857/f650cdb8-ddad-11e6-82fb-23c204197713.png)

**Comment by InDieTasten** [comment]
Second screenshot is confusing. You mean to display all unassigned workers with dark-gray? What qualifies the assumption that one would want to add the highest in the list?

I'd rather consider visual difference between workers, that are already assigned to a _different_ manager and instead color the "3/3" thingy red and maybe flashing it, when the player tries to assign more employees than possible

**Comment by BrutalCSkakan** [comment]
I see that my picture is a little bit wrong, it should be dark gray on all 3 of them.

BUT when I'm clicking a dark gray switch, and the manager has all spots taken(3 of 3) then the rest of the switches should be light-gray. 

Green: Is activated
Dark Gray: Can be activated
Light Gray: Can't be activated(Unless you untick one of the green switches, those with light-gray should then change its color to dark gray)

**Comment by jhovgaard** [comment]
I get it now. Agreed with @InDieTasten, but if all switches go from light gray to dark gray it makes great sense.

Should we consider adding a global switch that says "Show already managed employees", so you can control employees from other managers too?
