### ISSUE TITLE
When a manager assigns an employee to a group, automatically activate Auto Repeat on that employee

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#184]
When a manager assigns an employee to a group, automatically activate Auto Repeat on that employee

**Comment by SirFinrod** [comment]
I would rather to click on auto repeat then forgotting to click to close and waste all my components

**Comment by jhovgaard** [comment]
Been doing some playtesting and I actually agree with @BrutalCSkakan. Let's make it auto-repeat when assigned to Manager.

**Comment by jhovgaard** [comment]
Done!
