### ISSUE TITLE
Sales Executives don't automatically get Auto Repeat when attaching a manager.

### ISSUE THREAD

**Issue by LapinoLapidus** [hovgaardgames/startupcompany#185]
Basically, when I attach a Manager to a Sales Executive, their "Auto Repeat" button doesn't turn on automatically, however, other "roles" like Developer & Graphic Designers do get "Auto Repeat".

This is quite annoying because with all the other people, it gets put on "Auto Repeat".

**Comment by BrutalCSkakan** [comment]
Developers doesn't always get Auto Repeat automatically. Probably something wrong

**Comment by InDieTasten** [comment]
Duplicate of #184
