### ISSUE TITLE
Automatically upgraded Manager <- BUG

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#186]
I had a beginner manager(Manager #1), I went into "Stats" to check if I can upgrade. It was greyed out and told me that I needed T10. (I CLICKED ON THE GRAY UPGRADE BUTTON ONCE)
I contiuned to play -> Hired another Manager(Manager #2) -> Accidently clicked on Manager #1 -> Saw that he now gave me 5 "In charge" instead of 3 -> Checked stats and voila, he suddenly was Intermediate

**Comment by jhovgaard** [comment]
Fixed.
