### ISSUE TITLE
Change the negotation between companies and seller

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#189]
I feel like job negotiations should be changed. 

It should be in 2 segments. The first one is a "blind bet" with 10 companies competing to get the deal. 
The second segment is a broken-down negotiation-deal with only 3 companies left. 

In this case you get one chance to understand what the others are betting, and the second one is where you can fine-tune your bet to get a bigger chance on succeeding the bet.

EDIT: There should also be a chance of companies declining a deal.

**Comment by jhovgaard** [comment]
I really like this idea. Let's plan it for Beta 9.
