### ISSUE TITLE
Some visual bugs 

### ISSUE THREAD

**Issue by SirFinrod** [hovgaardgames/startupcompany#195]
![visual misplacement](https://cloud.githubusercontent.com/assets/25222894/22106251/f2d30056-de58-11e6-9665-37a349955eb0.png)

![startupcompany_2017-01-19_17-02-52](https://cloud.githubusercontent.com/assets/25222894/22109563/56ece678-de69-11e6-83d2-322455e3d92c.png)

![startupcompany_2017-01-19_17-03-11](https://cloud.githubusercontent.com/assets/25222894/22109573/606e6974-de69-11e6-834c-4733f39e83bc.png)

Also one of the whiteboards gone missing but i did not screenshot that for some reason i dont know :P

**Comment by SirFinrod** [comment]
Some more 
![startupcompany_2017-01-19_17-07-22](https://cloud.githubusercontent.com/assets/25222894/22109682/d0799108-de69-11e6-8eef-76146e1c518d.png)
![startupcompany_2017-01-19_17-07-32](https://cloud.githubusercontent.com/assets/25222894/22109683/d081ce5e-de69-11e6-910c-f61d268eb83e.png)

**Comment by SirFinrod** [comment]
After i designed my second floor i found this on the first floor  :P 
![startupcompany_2017-01-19_18-21-18](https://cloud.githubusercontent.com/assets/25222894/22112552/6cea0284-de74-11e6-88bc-513c22c8df4c.png)

**Comment by InDieTasten** [comment]
@SirFinrod If it keeps appearing after restart, it might be useful for jonas to check your savegame

**Comment by SirFinrod** [comment]
@InDieTasten when i restarted game its fixed but then the second floor get messed up like this :P 

![startupcompany_2017-01-19_18-30-24](https://cloud.githubusercontent.com/assets/25222894/22112791/5f9d0242-de75-11e6-8b43-67f8f42d30d9.png)

**Comment by InDieTasten** [comment]
savegame please ;) thanks for all your info so far!

**Comment by SirFinrod** [comment]
[Startup Company.zip](https://github.com/hovgaardgames/startupcompany/files/717038/Startup.Company.zip)

**Comment by InDieTasten** [comment]
Thanks :)

**Comment by jhovgaard** [comment]
Awaiting isodomjs to be completed, before we can fix this.

**Comment by NFHQ** [comment]
Here is how its making my game looks... yea pretty bad 
![screenshot_3](https://cloud.githubusercontent.com/assets/26171403/23580931/20f537e8-0103-11e7-943d-8b6e97bfd237.png)

**Comment by InDieTasten** [comment]
@jhovgaard before going to replacing the rendering mechanism completely via isodomjs, you could try to fix this exact issue. It seems to be an issue with switching floors, which should work just as fine as loading from main menu

**Comment by jhovgaard** [comment]
Removed multiple floors. Fixed :D

**Comment by InDieTasten** [comment]
Got an idea: Just cancel the project all together. That would resolve all the issues 👅

**Comment by jhovgaard** [comment]
:D Fortunately multiple floors was removed because of performance problems.

**Comment by InDieTasten** [comment]
Ah, good ol' friend performance. "we have too many nested loops, captain!" ( ͡ಠ ʖ̯ ͡ಠ)
