### ISSUE TITLE
Can't scroll in contract view

### ISSUE THREAD

**Issue by prempador** [hovgaardgames/startupcompany#197]
When I get two lines of components the close button is not visible. And I can't scroll down so I always have to restart the game to continue. 

Beta 8

![screenshot from 2017-01-19 15 13 38](https://cloud.githubusercontent.com/assets/9047327/22109910/0bcea0fa-de5a-11e6-8701-62b3213b8a57.png)

**Comment by jhovgaard** [comment]
Duplicated of https://github.com/hovgaardgames/startupcompany/issues/165
