### ISSUE TITLE
Better Office bonus calculation (Mood over 100%)

### ISSUE THREAD

**Issue by prempador** [hovgaardgames/startupcompany#198]
After adding over 100 coffee machines to my office i managed to get my employees to have over 100% mood.
Beta 8
![screenshot from 2017-01-19 15 29 56](https://cloud.githubusercontent.com/assets/9047327/22110514/416982d2-de5c-11e6-9c67-419cf1cb01a9.png)

**Comment by InDieTasten** [comment]
Over 100 coffee machines will legit add 1314% to any dev out there. This is intended behavior. Studies confirm this exact phenomenon. [/s]

Feel free to create a feature issue that describes implementing a better office bonus calculation.

**Comment by jhovgaard** [comment]
Fixed. Now support much more complex calculation of office bonus.
