### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by SirFinrod** [hovgaardgames/startupcompany#200]
### It can get a bit messy and confusing when you have a lot of stuff in your inventory. I suggest it should be atleast color sorted. if possible user administration 

![startupcompany_2017-01-19_22-40-14](https://cloud.githubusercontent.com/assets/25222894/22122247/4ca58b78-de98-11e6-980f-b29c1eac4133.png)

**Comment by InDieTasten** [comment]
I'd recommend sortable and filterable list

**Comment by jhovgaard** [comment]
Optimized inventory view. Hopefully this one is better.
