### ISSUE TITLE
While merging you don't see what components the merge is using

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#201]
I'd suggest that the merge window to the left should show what components the current merge is using. This is good when you have alot of merging going on and you don't know who's eating up all a specific component

![image](https://cloud.githubusercontent.com/assets/8394703/22122388/0d03c15c-de88-11e6-9cb8-99fae935b7f8.png)

**Comment by jhovgaard** [comment]
Revised lead dev view. No more relevant.
