### ISSUE TITLE
Merging does not follow the same "pattern" as the developer have

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#202]
When you're in the developer menu and you're clicking what component it should make, then it "activates". If you then click on another component it will stop the current one and start the other one. 

This behaviour should be the same on other employees, such as the Lead Dev. 

Please, have this one in mind when changing #180

**Comment by InDieTasten** [comment]
#180 was already adressed and is now closed. Marking this enhancement

**Comment by jhovgaard** [comment]
Aligned.
