### ISSUE TITLE
Unclear "Missing Component" bug in Lead Dev view

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#203]
I got "Missing Component" once when merging, although I had over 100 components on all the components that was needed for the module.

One guess is that it was prompted when the employee went home for the day. This only happened once after the first merge.

**Comment by jhovgaard** [comment]
@BrutalCSkakan Can explain how I reproduce this? I don't experience it myself.

**Comment by BrutalCSkakan** [comment]
It was a very strange situation, like if the auto-repeat started at the exact time as the employee went home for the day. 
Can probably not reproduce im afraid

**Comment by InDieTasten** [comment]
Has there been any occurrences of this issue since? If not, please mark invalid and close the issue.

**Comment by BrutalCSkakan** [comment]
Haven't got this since the issue was created. Where do I mark it as invalid?
