### ISSUE TITLE
Feature: Queue the next objective

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#204]
What about module/component-queueing? 
Lets say that I want to do 10x Network Components, and after that I want to do 5 Backend Components, shouldn't I be able to queue up these 10 NC & 5 BC?

**Comment by jhovgaard** [comment]
Keeping this open for up-votes.

**Comment by BrutalCSkakan** [comment]
Close this and continue on #214 ?
