### ISSUE TITLE
Enable Auto Repeat as a standard for Lead Dev

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#205]
1. Assign the Lead Dev to a manager
2. Start a merge of a module
3. Look at the Auto Repeat <--- It's disabled. 

Expected behaviour: When I assign an employee to a manager I'd really want it to do what it's supposed to do, which is to get the Auto Repeat functionality. I don't want to manually add him to a manager, and then activate the Auto Repeat.

**Comment by InDieTasten** [comment]
Related to #184 ?

**Comment by BrutalCSkakan** [comment]
Cool, must have been drunk as I can't remember #184 . But yeah, same thing
