### ISSUE TITLE
Contracts: Screen is not scaling (Beta 7)

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/startupcompany#206]
For contracts where you send an offer and the list of components is big, the button for closing the window is barely visible.

![screen_not_scaling](https://cloud.githubusercontent.com/assets/4112189/22122819/a97162fa-de89-11e6-8b65-2cf50f0519d7.png)

**Comment by jhovgaard** [comment]
Duplicated of https://github.com/hovgaardgames/startupcompany/issues/165
