### ISSUE TITLE
Module merging icon is not centered

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#207]
![image](https://cloud.githubusercontent.com/assets/8394703/22122979/2cfb0b8a-de8a-11e6-9e28-a5aa674bdf90.png)

**Comment by jhovgaard** [comment]
@BrutalCSkakan OCD triggered much? :D

**Comment by InDieTasten** [comment]
You want him to change the margin/padding so it's even? Then you just shift the problem. Now the entire thing will off-center in regards of the container. Too much work. @jhovgaard reopen if you feel like fixing this particular case nontheless
