### ISSUE TITLE
Clicking a component for developers cancels the current "built"

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/startupcompany#208]
I you accidentally click on a component while the developer is currently working on another component, all the progress is lost and the developer will automatically start working on the new component.

Could you please either give a warning that you are about to cancel the current work, or put the new component in some sort of queue?

**Comment by jhovgaard** [comment]
Fixed. Now shows a confirm if task is in progress.

**Comment by InDieTasten** [comment]
Duplicate of #180
