### ISSUE TITLE
2 rows of modules/components in sales negotiation destroys CSS

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#209]
Watch the "Close" button

![image](https://cloud.githubusercontent.com/assets/8394703/22123386/b5b784e8-de8b-11e6-893f-69ca143ac942.png)

**Comment by jhovgaard** [comment]
Duplicate. Fixed.

**Comment by InDieTasten** [comment]
Duplicate of #165
