### ISSUE TITLE
My sales executive doesn't give me any jobs

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#211]
![image](https://cloud.githubusercontent.com/assets/8394703/22123587/75ecd2ea-de8c-11e6-86d7-2ea68fe94168.png)

I don't know if this error is related tho

**Comment by InDieTasten** [comment]
Upload savegame please :)

**Comment by jhovgaard** [comment]
Also which beta version?

**Comment by jhovgaard** [comment]
Closing, the Sales Ex has been strongly modified since this bug.
