### ISSUE TITLE
Upgrading an employee should require more than just a high Tier

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#212]
What about employee experience? I wouldn't really see the possibility of a newly recruited developer(That's a beginner when hired) to be turned into an expert until he's got some experience

**Comment by SirFinrod** [comment]
rather then experience levels can match with workstation types like on a beginner workstation only begginers can work, on intermediate workstation only intermediate and begginers can work etc

**Comment by jhovgaard** [comment]
Beta 4 was working as @SirFinrod suggests and it was really just annoying and players spent a long time understanding it.

I would rather see this to go in a direction where employees will improve their speed over time and over time be able to advance.
