### ISSUE TITLE
List of completed contracts is slow

### ISSUE THREAD

**Issue by WodeCraft** [hovgaardgames/startupcompany#213]
After 298 days the list of completed contracts is very slow to be shown and will freeze the entire game and make it unresponsive until the list is loaded and shown.

This is not just the initial showing of the list, but every time you want to see the list of completed contracts.

**Comment by InDieTasten** [comment]
@jhovgaard Add pagination?

**Comment by jhovgaard** [comment]
@InDieTasten indeed! @WodeCraft Can you attach your savegame?

**Comment by WodeCraft** [comment]
Is it the .dton-file that is stored under the "Documents/Startup Company"-folder? Named something like "sg_beta7_xxxxx.dton"

**Comment by jhovgaard** [comment]
@WodeCraft Exactly :-)

**Comment by WodeCraft** [comment]
Here you go ... that is the only one I have, so guess that is the one :)
[sg_beta7_d778c1d1-5.zip](https://github.com/hovgaardgames/startupcompany/files/722043/sg_beta7_d778c1d1-5.zip)

**Comment by jhovgaard** [comment]
@WodeCraft that is one well-designed office!

**Comment by jhovgaard** [comment]
Done!
