### ISSUE TITLE
Unassigned employees are not paid

### ISSUE THREAD

**Issue by roastchicken** [hovgaardgames/startupcompany#220]
Employees not assigned (i.e. not attached to a desk) do not show up in the budget. They do not seem to be paid either.

Tested on Beta version 8.2.

**Comment by jhovgaard** [comment]
Fixed!

**Comment by roastchicken** [comment]
@jhovgaard @InDieTasten This bug is not fixed in Beta 8. If an employee is not attached to a desk, they do not show up in the budget nor is their salary charged.

**Comment by jhovgaard** [comment]
Fixed again!
