### ISSUE TITLE
Upgrade workstation

### ISSUE THREAD

**Issue by Acerik** [hovgaardgames/startupcompany#221]
Add button to upgrade workstation. Just press button, pay price, get new workstation. http://imgur.com/a/NoTYl Price can like old - new workstation

**Comment by jhovgaard** [comment]
Keeping this open for up-votes.

**Comment by bernardodc** [comment]
Will this be implemented for the full steam release? Still think it is a good idea! :-)

**Comment by jhovgaard** [comment]
Yes, and I agree, good idea :-)
