### ISSUE TITLE
Maximum debt number format

### ISSUE THREAD

**Issue by roastchicken** [hovgaardgames/startupcompany#222]
When you go in debt you get a notification saying:

> Fortunately the bank allowed us a credit of $10.000. Make sure you don\'t go below that!

Most other numbers in the game use the format of $10,000. This change in format can confuse people who are not used to this other format, like me. I initially thought it said $10 😛 

This was tested in Beta version 8.2.

It seems to be set in app/scripts/game.js line 582.

**Comment by jhovgaard** [comment]
Fixed!
