### ISSUE TITLE
Difficulty setting

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/startupcompany#23]
- [ ] UI for setting the difficulty
- [ ] Implement as factors in various sections of the game
  - [ ] Make difficulty affect productivity/salary when hiring employees
  - [ ] Extend this list or reference extra issues here

---

First suggested on reddit: https://www.reddit.com/r/developertycoon/comments/4ubg3g/suggestion_multiple_difficulties_settings/

**Comment by InDieTasten** [comment]
First suggested on reddit: https://www.reddit.com/r/developertycoon/comments/4ubg3g/suggestion_multiple_difficulties_settings/

**Comment by InDieTasten** [comment]
>I thought at something, some devs should have problems/not able to acquire some competences, to increase the difficulty - hermier

**Comment by jhovgaard** [comment]
Up for vote on Conflux
