### ISSUE TITLE
Easter Eggs

### ISSUE THREAD

**Issue by danielbruni** [hovgaardgames/startupcompany#231]
Let's  gather some ideas for Easter Eggs.

* [ ] If you build too many coffee machines: Random Event: Worker xy has caffeine overdose and needs z days to rest
* [ ] Rename a worker to Jhovgaard or his real name to get a special character look or special stats?

**Comment by InDieTasten** [comment]
-[ ] When reaching T5 with no female employees, you will receive mad letters from SQWs and feminists.

**Comment by NFHQ** [comment]
Possibility of female workers requiring maternity leave?

**Comment by InDieTasten** [comment]
@NFHQ Not much of an easter egg, but rather a nice detail one could add to the game.
