### ISSUE TITLE
Play As Yourself

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#232]
Allow the player to play as the CEO of the company. Start of game will ask them:

* Name
* Skill: Sales Executive, Developer, Designer, Lead Developer

The player can then position himself in the office. Based on the selected skills he will be able to function as a regular employee. The CEO will also be able to control hiring. Also the CEO doesn't cost any salary.

**Comment by raimonds1503** [comment]
Can you fire yourself?

**Comment by roastchicken** [comment]
I think if anything you could just have a desk for yourself, but not have any specific skills or actions associated with your person. Just to make it more realistic, so you have a player to represent yourself in the game but you still do all the things from the main interface.

**Comment by bernardodc** [comment]
I would like that a lot. This way you can also create a nice and fancy executive office for yourself! :-)

**Comment by bernardodc** [comment]
Will this be implemented for the full steam release? Still think it is an AWESOME idea! :-)

**Comment by jhovgaard** [comment]
I want it, but it's too early to say. I need some time planning out the feature to see if it can be done in a decent way.

I'll keep you updated in here.

**Comment by jhovgaard** [comment]
Moved to Conflux.
