### ISSUE TITLE
Starting money

### ISSUE THREAD

**Issue by roastchicken** [hovgaardgames/startupcompany#235]
Currently the player starts out with $0 and has to take out a loan to buy anything. Since players might not know this is something they have to do, an alternate solution would be good.

The following solutions have been proposed:

- Start with $20k in the bank
- Start with the $40k loan already loaned

What do you guys think?

**Comment by jhovgaard** [comment]
I think $40k is the minimum to start making revenue. Otherwise the player will have to take up another loan in the beginning.

**Comment by jhovgaard** [comment]
Closed due inactivity.
