### ISSUE TITLE
-100k bank and "stuck" at night

### ISSUE THREAD

**Issue by veryhasted** [hovgaardgames/startupcompany#237]
I was at +80k in bank at day 76. I then then during the night I went from 80k to -80k and about another -2k every time I pressed "Jump to start of the day"  but it would only forward about 1 hour.

![image](https://cloud.githubusercontent.com/assets/19938706/22404003/40bbf888-e627-11e6-930a-76fb583b0b70.png)

Save file
[https://ufile.io/e02c6](url)

**Comment by InDieTasten** [comment]
What versions did you play with that save?

**Comment by jhovgaard** [comment]
Beta 8 confirmed. Trying to reproduce it now.

**Comment by jhovgaard** [comment]
Fixed. Was caused by injection null values into unassignedEmployees array on deleting empty workstations.
