### ISSUE TITLE
Deletion of items in the scene

### ISSUE THREAD

**Issue by trdwll** [hovgaardgames/startupcompany#242]
tl;dr unable to delete a wall I placed (Windows 10).

**Comment by BrutalCSkakan** [comment]
Please provide your saved games file, it's located in C:\Users\Kim\Documents\Startup Company

**Comment by trdwll** [comment]
Unnecessary, I notified @jhovgaard via DM on discord about this the moment I found it.

**Comment by johannwagner** [comment]
Fixed in a previous beta. @jhovgaard prooved it in stream.
