### ISSUE TITLE
When there are 3 rows of modules for a contract you're unable to exit the menu

### ISSUE THREAD

**Issue by trdwll** [hovgaardgames/startupcompany#243]
Basically the UI doesn't have a scrollbar so you can click continue etc. (The UI for the contract stays up so you have to exit the game.)

**Comment by trdwll** [comment]
Edit: I forgot to mention this is on the contracts where you bid. If you accept/bid the other bids make the UI scroll down, but you're unable to view/click the Close button.

**Comment by BrutalCSkakan** [comment]
This is known and probably fixed in the closed beta. 
But you should be able to click the small 1px button that you see at the bottom of that window, otherwise i'd suggest you to easily change the css behaviour under the developer tools if you're familiar with such tools.

**Comment by InDieTasten** [comment]
@jhovgaard Can you provide a status for this item?

**Comment by jhovgaard** [comment]
@InDieTasten yes, it was originally fixed for 2-row contracts. Now it reached 3 rows. This has to be fixed. 3 rows indicates too many component types.

**Comment by InDieTasten** [comment]
@jhovgaard Has this been fixed already? If not, consider this a bump :)

**Comment by jhovgaard** [comment]
Fixed
