### ISSUE TITLE
Different work table levels

### ISSUE THREAD

**Issue by Aveik** [hovgaardgames/startupcompany#246]
_First of all! I don't know if this has been implemented but it might add some difficulty to the game._

Basically, starting with a full speed production with a powerful PC, great desk, great chair and 2+monitors should be something that the employees need to work towards with the growth of the company. Its a startup basically.

What I mean by this, when you create your first game you should also start with basic items like:
- Medium PC (Not so great power, could decrease productivity speed, or could be just default). This also doesn't have to be "Medium" it can be super low, low medium, high, super high, SUPERCOMPUTER etc. (and also a macbook ;-) But i'll get to that later)

- Hardware peripherals can be dependant on the level of the pc. F.e. when you have a low PC you can't get multiple monitors
Also every component in the PC could be exchanged and upgraded (GPU, CPU, RAM etc), other stuff like compatibility between the components would be too much of a customization hehe

- Keyboard, if the keyboard is bad and not comfortable for the employee, it could maybe decrease happiness and decrease productivity, but with a high end keyboard the productivity, comfort etc. could be increased

- Another thing is monitors, this could be major for productivity increase, it would require a powerful PC and some extra money, allow up to 4 monitors (3 inline and 1 above the middle one you get the point)

- Desk size and desk customization and looks

- Chair, could increase happiness and comfort

**Examples:**

Default PC:
- Low PC (default productivity value, I guess 0%??? idk)
- Bad keyboard (-10%)
- 1 cheap monitors (no benefits nor disadvantages)
- Bad cheap chair (-15%, back & butt hurts)
- Bad, unstable desk (-10%, not enough mouse, arm, keyboard space)

Something that progress showed
- Powerful PC (+100% productivity)
- Medium Keyboard (+15% productivity)
- 3 monitors (90% productivity, (30% each))
- Comfortable chairs (+10%)
- Great quality desk (+10%)
etc.

Also these things would be customized for each and every one of the employees, so if you have bought a powerful PC for one, you would have to buy it for the other employees individually.

**Comment by InDieTasten** [comment]
Better computers don't improve productivity directly, but rather rise the motivation, which in turn could improve productivity

**Comment by Aveik** [comment]
It would be awesome also having mods that could change the textures of desks, monitors chairs etc. Ofc these mods would come from steam workshop
