### ISSUE TITLE
macOS Modding Issues - Unable to Launch when .DS_Store

### ISSUE THREAD

**Issue by bnewman200** [hovgaardgames/startupcompany#249]
I found that the program is looking for ".DS_Store" file on maxOS that is a hidden file. It typically is only created when there is usually a change or deletion of a file in the directory. 

It appears that you are looking for all files when reading the mods directory and not just for directories inside the mods directory. Therefore, it is looking at the .DS_Store file and failing, then crashing the program.

Please let me know if more information is needed.

**Comment by jhovgaard** [comment]
Should be fixed adding file filtering.

**Comment by jhovgaard** [comment]
Done
