### ISSUE TITLE
macOS - Request to change location for Documents

### ISSUE THREAD

**Issue by bnewman200** [hovgaardgames/startupcompany#250]
Currently the program is storing information in the users <username>/Documents/Startup Company/ directory. For macOS user this is not typical. The typical directory is <username>/Library/Application Support/<application name>/. 

This means that most macOS users will look into <username>/Library/Application Support/Startup Company/ for both all of the files that would typically be stored in the Documents/Startup Company/ directory.

**Comment by connorhu** [comment]
The default peruser Application support folder is:
~/Library/Application Support
not /Library...

**Comment by jhovgaard** [comment]
Now using Application Support.
