### ISSUE TITLE
Rename Employees

### ISSUE THREAD

**Issue by bnewman200** [hovgaardgames/startupcompany#253]
Could you add the ability to rename the employees?

**Comment by InDieTasten** [comment]
Would also like to rename the company

**Comment by jhovgaard** [comment]
Opening this for discussion. Is it too unrealistic to be able to rename employees?

**Comment by InDieTasten** [comment]
It is unrealistic, but nobody would care. I think it's a great idea. I'm sure people would come up with some pretty funny names. Having some customization abilities is always a ➕ IMO.

**Comment by jhovgaard** [comment]
@InDieTasten +1 for stream/review friendly feature, you're right.

**Comment by jhovgaard** [comment]
Both company name and employee names can now be renamed by clicking on the name.
