### ISSUE TITLE
Object Deleting

### ISSUE THREAD

**Issue by NFHQ** [hovgaardgames/startupcompany#256]
Objects wont delete. Desks will delete fine but walls, seats ect wont when clicking on the delete button it dosent change anything

**Comment by InDieTasten** [comment]
Yeah, I've seen this in the review by ellitopia gaming as well

**Comment by brandinarsenault** [comment]
Definitely an issue, hope it is resolved soon 👍

**Comment by InDieTasten** [comment]
I consider this fairly safe to be an issue right now.

**Comment by jhovgaard** [comment]
Fixed!
