### ISSUE TITLE
Beta 9.4: Working Overtime to Complete Tasks not fulfilling

### ISSUE THREAD

**Issue by bnewman200** [hovgaardgames/startupcompany#261]
When having an employee work overtime in order to complete a task, the task goes unfulfilled until the employee comes in the next day. 

Therefore, if you have an employee stay overtime to help complete a contract, the contract still does not get completed until hours later.

**Comment by jhovgaard** [comment]
Turned the overtime feature off for now. Need to redesign the location of the button to make it available for all employee types + overtime should be a static number since task can be very large now.

**Comment by InDieTasten** [comment]
Redesign status of this feature can be viewed at #266
