### ISSUE TITLE
Beta 9.4: Money Display Disappeared

### ISSUE THREAD

**Issue by bnewman200** [hovgaardgames/startupcompany#262]
Sometime after reaching T5 and hiring a CTO, the money display disappears and no longer shows the current bank balance, but shows blank.

**Comment by metathias** [comment]
Experienced the same Issue around that tier. Have not hired CTO though.

**Comment by jhovgaard** [comment]
@bnewman200 @metathias Can one of you send me a savegame with the money gone?

**Comment by jhovgaard** [comment]
Had to play until Tier 5 to experience the same thing :D

Was caused by enabling benefits. Fixed now.
