### ISSUE TITLE
Beta 9.4: Employee becomes idle through saved game

### ISSUE THREAD

**Issue by bnewman200** [hovgaardgames/startupcompany#263]
When closing an reopening the game, all employees become idle even though they have managers. This forces you to goto each employee with a manager and reassign the highlighted task.

**Comment by jhovgaard** [comment]
I was not able to reproduce this. However I did change a lot of code related to tasks, so it might have fixed it. Let's reopen this if it happens in Beta 9.5.

**Comment by jhovgaard** [comment]
Reopened. Still happen in 9.5

**Comment by jhovgaard** [comment]
Finally fixed this. Was happening once for every just hired employee. After that it wouldn't happen.

**Comment by johannwagner** [comment]
This bug is not fixed. Some employees are idle after savegame in Beta 9.8.
