### ISSUE TITLE
Item Location

### ISSUE THREAD

**Issue by Jeff-Shapiro** [hovgaardgames/startupcompany#270]
Items can easily be built outside of the floor space as shown. The desk was placed within the wall but placed itself outside. Will conduct a trial again to see if I can recreate the issue.

![image](https://cloud.githubusercontent.com/assets/20011187/24295646/eebe4560-10ef-11e7-9f03-2a8229208421.png)

**Comment by johannwagner** [comment]
Same as #257. Also occurs on Beta 9.6.

**Comment by Jeff-Shapiro** [comment]
@johannwagner please only make comments on my issues if it is correct and valid.

**Comment by jhovgaard** [comment]
Fixed.
