### ISSUE TITLE
Beta 9.6: Equality in the bidding

### ISSUE THREAD

**Issue by johannwagner** [hovgaardgames/startupcompany#271]
You win the bidding, if your price is equal to a bidden price from another company

**Comment by jhovgaard** [comment]
It is by design. What would you prefer?

**Comment by johannwagner** [comment]
You could redo the bidding or just make sure that there are no equal values.

**Comment by johannwagner** [comment]
Or you could close the issue.

**Comment by jhovgaard** [comment]
No equals sounds right imo!

**Comment by InDieTasten** [comment]
If two bids are exactly the same, you could do 50/50 to where it goes, or if possible, evaluate both companies reputation to the requester, like amount of jobs won for that company.
