### ISSUE TITLE
Beta 9.7: Employment Counter in Stats

### ISSUE THREAD

**Issue by johannwagner** [hovgaardgames/startupcompany#275]
You disabled or removed the employee employment counter as you optimized performance. You should remove the counter or reenable this again.
This employee is my first employee. I am currently at Day 41.
![image](https://cloud.githubusercontent.com/assets/12380026/24321770/0b3f7816-1155-11e7-9c6b-01249df20425.png)

**Comment by jhovgaard** [comment]
Finally fixed!
