### ISSUE TITLE
Beta 9.7: Weird behaviour of Developer

### ISSUE THREAD

**Issue by johannwagner** [hovgaardgames/startupcompany#276]
This is my intermediate developer. 
The modules are unlocked in an wierd way and I am not able to see how I unlock the other one. Should there be a mouse over ?

![image](https://cloud.githubusercontent.com/assets/12380026/24321832/30f80ea0-1156-11e7-8680-5390bde8d725.png)

**Comment by InDieTasten** [comment]
Possibly related to #35 ?

**Comment by johannwagner** [comment]
Dunno, i asked Jonas and he said, i should report it.

**Comment by InDieTasten** [comment]
Ok, @jhovgaard : Feel free to evaluate the type of the issue. Can't decide between enhancement, bug or missing tooltip.

**Comment by jhovgaard** [comment]
Enhancement :-)

**Comment by jhovgaard** [comment]
Fixed!
