### ISSUE TITLE
Beta 9.7: 30 Workstations available from new game.

### ISSUE THREAD

**Issue by Swinkid** [hovgaardgames/startupcompany#280]
The screenshot shows 26, but I was able to purchase 30 desks from starting a new game. Im guessing this is a bug left somewhere when you allowed unlocking the whole floor form the get go.

![30](https://cloud.githubusercontent.com/assets/6237394/24326726/ac3b518e-11ac-11e7-8f00-156575bbf1d3.PNG)

**Comment by InDieTasten** [comment]
Could also be related to #35, if there is another criteria for items to be unlocked

**Comment by johannwagner** [comment]
It is a new feature in Beta 9.7, Jonas told me. There are going to be multiple offices in the future.

**Comment by InDieTasten** [comment]
@johannwagner How is your comment related to this issue?

**Comment by jhovgaard** [comment]
@johannwagner is right, this is a new feature of 9.7. All workstations are available from the beginning.

@Swinkid It shows 26 remaining, but it looks like you have a few desks placed in the background. Doesn't it add up?

**Comment by Swinkid** [comment]
@jhovgaard Sorry i should've been clearer. What I had meant to say is that yes there was 30 to begin with, I had just placed a few. 

Initially thought this was a bug, just close it :P
