### ISSUE TITLE
Beta 9.8: LeadDev shows locked icons

### ISSUE THREAD

**Issue by johannwagner** [hovgaardgames/startupcompany#281]
![image](https://cloud.githubusercontent.com/assets/12380026/24475746/36a55334-14d1-11e7-81c6-e6865bfdc86f.png)

**Comment by jhovgaard** [comment]
Caused by having employees at different levels.

**Comment by johannwagner** [comment]
Happens, if the Lead Dev has a lower level than the required Developer Level for component.

**Comment by jhovgaard** [comment]
Fixed!
