### ISSUE TITLE
Beta 9.8: Sales Executive Contract Frozen

### ISSUE THREAD

**Issue by bnewman200** [hovgaardgames/startupcompany#282]
After completing a bidding contract, the sales executive could no longer search for a new contract.

This may have occurred because the contract was completed through the contracts interface and not the employee interface. However, I did attempt to replicate the issue and it did not happen again.

![capture](https://cloud.githubusercontent.com/assets/6477813/24486443/cc501b5a-14cf-11e7-93a9-346c6792578b.PNG)

**Comment by bnewman200** [comment]
Here is a screenshot with the contract completed.

![capture](https://cloud.githubusercontent.com/assets/6477813/24486497/0246d23a-14d0-11e7-99c2-20e5343a9917.PNG)

**Comment by jhovgaard** [comment]
Having a hard time reproducing this. Please let me know if you find a way.

**Comment by akkusb** [comment]
Hi, I was able to reproduce this bug. If I take a contract and detach sales executive from desk, then finish the contract and put sales executive to desk again this bug happens.

**Comment by jhovgaard** [comment]
Wow, good job reproducing this @akkusb. Thanks a lot!

**Comment by jhovgaard** [comment]
Fixed!
