### ISSUE TITLE
Beta 9.10: Headhunting: Progress not pausing during non business hours.

### ISSUE THREAD

**Issue by metathias** [hovgaardgames/startupcompany#285]
Doing an intermediate Headhunt (which is supposed to take 8 hours) at the end of business hours still continues to progress, And finish even during non business hours.

**Comment by jhovgaard** [comment]
What do you guys think about this? The reason it keeps going is because there's no employee attached to the headhunting progress.

Tell me what you think.

**Comment by Scorpionsilver** [comment]
I have though of it like an application deadline, so people have that long to apply and you are hiring the best from that group only

**Comment by jhovgaard** [comment]
Will keep the behavior for now. Can't see a way to fix it without defining the working hours statically which I  don't like.
