### ISSUE TITLE
Wall offset when zooming

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/startupcompany#29]
By using different zoom levels (zoom in/out) and replacing walls, the walls seem to shift up/down depending on the zoom level.
It's kind hard to see at first, but if you got OCD problems, this will be spotted right away.
http://prntscr.com/bxm6xe
![image](https://cloud.githubusercontent.com/assets/7047377/17193753/c4f0bd6a-5454-11e6-9299-c115b72fd699.png)

---

First seen on reddit: https://www.reddit.com/r/developertycoon/comments/4unlin/bug_walls_and_zoom_level/

**Comment by InDieTasten** [comment]
I'd put that on `might not fix` personally, instead of milestone 6, as I perceive this as minor as possible.

**Comment by jhovgaard** [comment]
Note: Fix by dynamically calculate location of assets instead of saving the value.
