### ISSUE TITLE
Beta 9.12: New version of product with an other framework with lower features

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#291]
Created a product with "ExpensiveFramework4" features: 8 then created an new version with "CheapFramework4" features: 7 
Shows features left: -1 
Confirmed and all features are active
![ezgif-2-9dc86d2121](https://cloud.githubusercontent.com/assets/16868650/24583220/802cf45c-1743-11e7-8f05-844d3871f36b.gif)

**Comment by jhovgaard** [comment]
Fixed
