### ISSUE TITLE
Beta 9.12: Hire more employees than workstations/seats

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#292]
Can hire more employee than (max) workstations/seats.
Need to fire and other employee to fire all other employee with no workstations/seats.

![suc4_github](https://cloud.githubusercontent.com/assets/16868650/24583289/8322b55a-1745-11e7-9543-fe5804395e0d.jpg)

**Comment by johannwagner** [comment]
There is a option missing firing unassigned employees.

**Comment by jhovgaard** [comment]
Fixed, now allowing to fire/dismiss from employees view.
