### ISSUE TITLE
Beta 9.12: Headhunted all available candidates down

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#293]
Headhunted all available candidates, hired all and removed them. /J4F
After restarting the game, still none candidate available.

![suc5_github](https://cloud.githubusercontent.com/assets/16868650/24583314/7aa3ce18-1746-11e7-98c2-0902b3dfabc8.jpg)

**Comment by jhovgaard** [comment]
Fixed. When list is empty new candidates will be generated.
