### ISSUE TITLE
Error in calculation of the finances (subsequent error of #292)

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#295]
Subsequent error of: **Hire more employees than workstations/seats** - https://github.com/hovgaardgames/startupcompany/issues/292

![suc_6_jpeg90](https://cloud.githubusercontent.com/assets/16868650/24586102/d179096c-1799-11e7-9034-598ec106cbf1.jpg)
![suc_7_jpeg90](https://cloud.githubusercontent.com/assets/16868650/24586103/d43b99d0-1799-11e7-8676-620bc2be8952.jpg)
![suc_8_jpeg90](https://cloud.githubusercontent.com/assets/16868650/24586104/d68c4338-1799-11e7-9771-b8596644e0ff.jpg)
![suc_9_jpeg90](https://cloud.githubusercontent.com/assets/16868650/24586106/d8e65a92-1799-11e7-9563-8f766a8ec19f.jpg)
![suc_10_jpeg90](https://cloud.githubusercontent.com/assets/16868650/24586107/db1b081c-1799-11e7-9268-ce546a93bcc9.jpg)

And yes the office is full.

**Comment by johannwagner** [comment]
There is an older bug like this. Unassigned employees are not paid.

**Comment by rremo** [comment]
Yes there is one, i have not seen.
See: **Unassigned employees are not paid** - https://github.com/hovgaardgames/startupcompany/issues/220
