### ISSUE TITLE
No tooltips of components shown, if the workload and game speed too high

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#297]
![ezgif-2-931edac7ff](https://cloud.githubusercontent.com/assets/16868650/24586624/a06a55d6-17a5-11e7-98f0-75cf0517ec68.gif)

**Comment by johannwagner** [comment]
Maybe occurs because frequent tooltip updates...

**Comment by jhovgaard** [comment]
Oh, this is actually caused by missing tracking of the objects, which is causing the tooltip to be re-rendered every in-game minute. I'm on it...

**Comment by jhovgaard** [comment]
Fixed!
