### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/startupcompany#30]
I would like to have some achievements for various stuff, like milestones for each and every stat one can have. Like get into top 3 of competitors, get number 1 of competitors, win 10 job offers in a row, have 15 active clients, get to T3, have a monthly profit of $500 000.
You could even add something weird like deny 100 jobs in a row or stuff.

This would greatly increase replayability. I know you've mentioned that it's only supposed to be a weekend game, that you pull out every once in a while, start a new company and play it for 2-3 days after reaching the end, but you could still increase that time to maybe a day more, when people are engaged in completing all the various achievements. A lot of them are also fairly simple to implement and don't require any fancy architecture or additional storage to keep track of them.

**Comment by jhovgaard** [comment]
This is a great idea, and absolutely something to implement.

It should be build into Stream Archievements/cards from the beginning, so we need Greenlight approval first.

**Comment by InDieTasten** [comment]
Well, I think you could implement your own achievements system so you don't rely on greenlight approval. Syncing your own achievements with steam should be an easy patch then, and you can support achievements when you consider additional platforms in future out of the box.

**Comment by InDieTasten** [comment]
Although this is a nice feature I think it's these things you are going to implement last. So putting this into early milestones doesn't make much sense. Theres already so much in milestone 6

**Comment by jhovgaard** [comment]
Closing this in favor for #32
