### ISSUE TITLE
Create Product graphs shrunk

### ISSUE THREAD

**Issue by brandinarsenault** [hovgaardgames/startupcompany#300]
The graphs for each product type under Create Product are shrunk and cause issues reading the number and type compared to when using the "New Version" button inside of a product.

**Comment by johannwagner** [comment]
Does not happen on my machine.
![image](https://cloud.githubusercontent.com/assets/12380026/24588898/8b704632-17d1-11e7-9dda-228f6757394b.png)

**Comment by jhovgaard** [comment]
Was able to reproduce. Don't know how unfortunately :D Investigating...

![](http://i.imgur.com/5CuNafl.png)

**Comment by jhovgaard** [comment]
Fixed. Caused by calculation happened while animation.
