### ISSUE TITLE
Beta 9.12: New Version Cancellations

### ISSUE THREAD

**Issue by brandinarsenault** [hovgaardgames/startupcompany#303]
I was in the middle of selecting the features for the new version, and I decided to cancel using the "X" button on the window instead of finishing, and now the "New Version" button is unclickable, the features were not added and the product version has not changed.

**Comment by brandinarsenault** [comment]
Also happens if you do not finish implementing prior to pressing release.

**Comment by jhovgaard** [comment]
Fixed! Good catch.
