### ISSUE TITLE
Beta 9.12: Graphs Disappear on Back

### ISSUE THREAD

**Issue by brandinarsenault** [hovgaardgames/startupcompany#304]
When you press back on both the Create Product and New Version sections from the Features Selection page, the graphs disappear for selecting a type of product.

**Comment by Sabakyo** [comment]
Some pictures to support this, managed to reproduce it.

Creating a new product:
![new product](https://cloud.githubusercontent.com/assets/660486/24605030/64914f22-1824-11e7-9d09-819a29c81483.PNG)

Press Back on the next page:
![back](https://cloud.githubusercontent.com/assets/660486/24605040/6e65d658-1824-11e7-9c95-af4a70e9a0d3.PNG)

Pie Charts disappear:
![after](https://cloud.githubusercontent.com/assets/660486/24605047/78a9a0ea-1824-11e7-96c9-a3019a3b4581.PNG)

**Comment by jhovgaard** [comment]
Added loading animation + fixed back issue.
