### ISSUE TITLE
Interface: Add "Manage Benefits" Button to employee tab?

### ISSUE THREAD

**Issue by Sabakyo** [hovgaardgames/startupcompany#305]
This is a rather minor suggestion, it felt a little odd to try and find the benefits page. I found myself clicking tabs until finally finding it on the Company Profile. 

It might flow a little better if there was a button to view that on the Employee list?

![capture](https://cloud.githubusercontent.com/assets/660486/24604912/050c1fb4-1824-11e7-9e90-e2832293831e.PNG)

**Comment by jhovgaard** [comment]
Moved benefits to its own tab + moved the company view to the menu instead.
