### ISSUE TITLE
Beta 9.12: Laggy (static) pie charts 

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#306]
Complain at a 'high level':
![ezgif-1-1236e906d1](https://cloud.githubusercontent.com/assets/16868650/24674758/f71c4cf8-197c-11e7-8dcd-565a3bc78e6a.gif)

**Comment by rremo** [comment]
Maybe it has something to do with https://github.com/hovgaardgames/startupcompany/issues/304

**Comment by jhovgaard** [comment]
Yes, was fixed with #304
