### ISSUE TITLE
Improve products bar statistics

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#307]
![sac_04-04-2017_1jpg](https://cloud.githubusercontent.com/assets/16868650/24674889/7623f2bc-197d-11e7-9ffd-4a617b805791.jpg)
Day: 589-595 daily $400 - $600
Day: 596 +**~**$6000
Day: 597 +**~**$13000
(im not sure if the bar calc based on +new user or on $$$)

![sac_04-04-2017_2](https://cloud.githubusercontent.com/assets/16868650/24674939/a71bee88-197d-11e7-9abc-baf71281361c.jpg)
The difference is too little,

![sac_04-04-2017_4](https://cloud.githubusercontent.com/assets/16868650/24674908/841d7f32-197d-11e7-9789-fe803d779ef7.jpg)
I think its a good way too use the full space in the red marked field. 
(may also add the orange marked area)
Maybe write the new users/d or the day in the bars self.

**Comment by jhovgaard** [comment]
Should probably just change to use Chartist: https://gionkunz.github.io/chartist-js/examples.html

**Comment by rremo** [comment]
Looks good!

**Comment by jhovgaard** [comment]
Introduced new chart!
