### ISSUE TITLE
[FEEDBACK NEEDED] [WIP] Updated Game Description

### ISSUE THREAD

**Issue by Sabakyo** [hovgaardgames/startupcompany#308]
**ABOUT STARTUP COMPANY**

Startup Company is a business simulation sandbox game. You play as the CEO of a newly founded software development company looking to earn a name for yourself in the industry.

Here's what you'll find under the hood:

**HIRE EMPLOYEES**

A great company is built by great people. Optimize your benefits and work conditions to attract the best employees. 

**WIN CONTRACTS**

Get ready to have your people get in touch with their people! 

You'll be facing hundreds of available contracts, but not all of them will be good for your developers. Work your way up and compete with the best in the industry to win the big contracts! 

**DEVELOP, MERGE, DELIVER!**

That's right, even software needs a little piecing together!

No matter if you want to deliver contracts or build your own product you need components and modules. Use developers, designers and lead developers to produce what you need. 

Startup Company includes a fully featured crafting/development system where you will be able to merge components into modules. 

**RELEASE, UPDATE AND EXPAND**

Your work doesn't stop once your product is released into the world!

Update your product's features and generate hype to increase your user-base and income for your product.  

You'll have to keep a close eye on your hype and user count as well as your server load for some products so be prepared to maintain your masterpiece or forget it ever happened expand to create something better.

It's your sandbox, let your imagination run wild!

**DESIGN THE PERFECT OFFICE**

What's an office without some desks and a bubbling water cooler?

Startup Company features a full blown sandbox mode, enabling you to design your dream office. Do it well and your developers will be working faster than ever!

**Comment by Sabakyo** [comment]
Current draft is mostly just a rewording of the current one to fix a few grammatical and spelling errors while adding some "Flavor" text.

**Comment by jhovgaard** [comment]
Way way better already. I notice all your changes, absolutely the kind of "voice" I think fits the game.

A thing to add to the list: Describing the products functionality

**Comment by WodeCraft** [comment]
The phrase "A great company is build by" should be "A great company is built by".

I think the "list" of what the game includes should reflect the paragraphs later, and be sorted the same way. Just my point of view, don't know if others agree :)

As Jonas said, it is a great text and more capturing than the current one :)

**Comment by johannwagner** [comment]
I just like it. I like your tone very much !

**Comment by Sabakyo** [comment]
Possible Final draft, Please review and let me know if I missed anything!

**Comment by jhovgaard** [comment]
@Sabakyo Jeez it looks good!

We need one new element of the description: Products. It should basically explain how you can create products and develop/expand and be the new Zucks. Kinda :D

**Comment by Sabakyo** [comment]
I've added a section that talks about products and expanding after. If you want me to describe it a bit more or differently let me know.

**Comment by jhovgaard** [comment]
@Sabakyo Looks good! Can you rewrite it so it doesn't include other services (like Myspace)? I'm afraid of trademarks.

**Comment by WodeCraft** [comment]
It looks really good. The only sentence I noticed was: "Once your product is out into the world your work doesn't stop there!"
It sounds a bit odd to say. Maybe a rephrase into something like: "Your work doesn't stop once your product is released into the world!"

Just a suggestion :)

**Comment by Sabakyo** [comment]
All fixed!

**Comment by jhovgaard** [comment]
@Sabakyo Did something go wrong here?

"You'll have to keep a close eye on your hype and user count as well as your server load for some products so be prepared to maintain your masterpiece or forget it ever happened expand to create something better."
