### ISSUE TITLE
Finance overview

### ISSUE THREAD

**Issue by bernardodc** [hovgaardgames/startupcompany#309]
Would be nice to have a real overview of revenue and cost per month / quarter / year and a valuation of the company... + graphs of course to show the evolution!

**Comment by bernardodc** [comment]
I guess this is now becoming included, with the valuation functionality that is being integration? Will it also be possible to sell part of your own shares to allow for further investments in growth?

**Comment by jhovgaard** [comment]
We should still keep this open as I want to extend the finance overview.

Regarding selling your own shares, then yes I believe so. However not included yet.
