### ISSUE TITLE
Employees table - make it sortable by columns

### ISSUE THREAD

**Issue by Vodoprovod4ika** [hovgaardgames/startupcompany#312]
I think that this will really help when you headhunt new employee /with good skill/ and want to check with who is best to switch it /employee with lowest % skill/ without scrolling all the list few times.

**Comment by Freakspot** [comment]
It would also be great if you could add a "show headhunted employees only" option to those filters.

**Comment by jhovgaard** [comment]
Added sorting for employees view. 

Hiring has been revised to that's not really relevant anymore.
