### ISSUE TITLE
Beta 9.15: Savegame cant load (*.DTON and .ZIP)

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#313]
The savegame-folder contains **sg_ffb2b0ab-a.dto**n and **sg_ffb2b0ab-a.zip**

![grafik](https://cloud.githubusercontent.com/assets/16868650/24995810/7eda435c-2030-11e7-9959-5ece5afc79d0.png)

**Comment by rremo** [comment]
Same with only an "old" *.dton
![grafik](https://cloud.githubusercontent.com/assets/16868650/24996499/6cb799b0-2033-11e7-9fd0-79fcbc9201a9.png)

**Comment by rremo** [comment]
For playtesting:
[sg_ffb2b0ab-a.zip](https://github.com/hovgaardgames/startupcompany/files/918892/sg_ffb2b0ab-a.zip) (1,36MiB)

**Comment by jhovgaard** [comment]
Optimized savegame updater. I got your office working now :-)
