### ISSUE TITLE
Beta 9.15: Language settings 

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#314]
- Change the language to the same (English->English, Danish->Danish)
- Danish isnt translate? 
- Resetting the windows size to full
![ezgif-1-b7a98c1ee3](https://cloud.githubusercontent.com/assets/16868650/24996368/ed9960f0-2032-11e7-8bf3-d033a28cb274.gif)
l

**Comment by jhovgaard** [comment]
Sorry, this shouldn't have been included. English the only supported language for now. Turning off Danish now.
