### ISSUE TITLE
Beta 9.15: Missing description (Tier levelup)

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#315]
![grafik](https://cloud.githubusercontent.com/assets/16868650/24996855/c2324650-2034-11e7-8a1e-7722b6649f06.png)
![grafik](https://cloud.githubusercontent.com/assets/16868650/24997042/72b3a406-2035-11e7-8dd5-3d5b8ab37b6c.png)
![grafik](https://cloud.githubusercontent.com/assets/16868650/24997235/2ad14c64-2036-11e7-950f-6775cc62e4c3.png)
![grafik](https://cloud.githubusercontent.com/assets/16868650/24997375/b72ff14c-2036-11e7-9c7d-fde837c5100f.png)

**Comment by jhovgaard** [comment]
Fixed!
