### ISSUE TITLE
Beta 9.15: Product income stats dont displayed

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#316]
Income stats per day only displayed at the first product.
![ezgif-1-18f8fabdd2](https://cloud.githubusercontent.com/assets/16868650/25042259/df93829e-2116-11e7-8bf0-26ae62f6c26f.gif)

**Comment by rremo** [comment]
See: https://github.com/hovgaardgames/startupcompany/issues/317

**Comment by jhovgaard** [comment]
Fixed right? Or Maybe I misunderstand

**Comment by rremo** [comment]
yes, fixed
