### ISSUE TITLE
Beta 9.15: Product generate no income [critical]

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#317]
I have wonder why i make so little money and it always getting 4-5k away per day.
![grafik](https://cloud.githubusercontent.com/assets/16868650/25044886/8fd4b6a2-2129-11e7-9b24-200f474bca55.png)
Product income per day: ~114k $
Hosting, only: 2250$ 

![grafik](https://cloud.githubusercontent.com/assets/16868650/25044895/9f22a9fc-2129-11e7-9a84-fa387f478e1f.png)
![grafik](https://cloud.githubusercontent.com/assets/16868650/25044974/112e38ae-212a-11e7-9d63-a4fb504e595e.png)
![grafik](https://cloud.githubusercontent.com/assets/16868650/25044988/1e716392-212a-11e7-81fa-81dd48652ef3.png)
![grafik](https://cloud.githubusercontent.com/assets/16868650/25044992/22cb4048-212a-11e7-998f-a5921b52d45d.png)
![grafik](https://cloud.githubusercontent.com/assets/16868650/25045002/2e5fb3a8-212a-11e7-8bd3-5d3fe5be8db4.png)
![grafik](https://cloud.githubusercontent.com/assets/16868650/25045005/33263e5c-212a-11e7-865c-c34a5e267f06.png)

**Comment by rremo** [comment]
CTO is needed.
Fixed in Beta 9.16?

**Comment by jhovgaard** [comment]
Yes fixed :-)
