### ISSUE TITLE
Beta 9.16: Office Rent in Financial Overview 

### ISSUE THREAD

**Issue by johannwagner** [hovgaardgames/startupcompany#319]
![image](https://cloud.githubusercontent.com/assets/12380026/25062829/0ea1a17e-21d5-11e7-942a-654cb8fa712e.png)
![image](https://cloud.githubusercontent.com/assets/12380026/25062832/1b083068-21d5-11e7-8ed6-a14a7445d1ac.png)

Something is wrong here. I dunno, if the 10k Office Rent is monthly or just got the wrong label.

**Comment by jhovgaard** [comment]
Fixed!
