### ISSUE TITLE
Achievement Collection

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/startupcompany#32]
## Heres the list of potential achievements for Startup Company.
- [ ] -("Enjoy your stay") Hire 1 employee
- [ ] -(Interviewer) Hire 5 employees
- [ ] -(Employment Machine) Hire 10 employees
- [ ] -("You're out!") Fire 1 employee
- [ ] -("YOU as well!") Fire 5 employees
- [ ] -("Amateurs!") Fire 10 employees
- [ ] -(Dream big) Be Top 3 on leaderboard(competitors list)
- [ ] -(Leader) Be # 1 on leaderboard(competitors list)
- [ ] -(Economic setback) Don't work on any job for 14 days
- [ ] -(Starvation) Don't work on any job for 30 days
- [ ] -(Into black) Have a monthly profit of at least 0
- [ ] -("It's something") Complete your first job
- [ ] - ("Same, but different") Installed 1 mod
- [ ] - ("Install all the mods!") Installed 5 mods

---

As continuation for #30 

---

Original post

**Comment by InDieTasten** [comment]
Issues marked s:discussion shouldn't be added to milestones. Especially collection type of issues.

**Comment by jhovgaard** [comment]
Added all these achievements. Closing this one as the discussions keeps going on Steam Community Hub: http://steamcommunity.com/app/606800/discussions/0/2333276539588139385/
