### ISSUE TITLE
Stopping game Idle

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#321]
**Stopping the user of play the game in idle mode.**

**For the calculation on the stream**:
1 day = ~73 seconds (time stopped)
73 * 670 days (fast speed) = 48910 seconds
48910sec / 60 = 815.1666666666667 min
815.1666666666667min / 60 = 13.58611111111111 hours 
on "idle mode"

**Comment by jhovgaard** [comment]
Thanks!

**Comment by jhovgaard** [comment]
Fixed.
