### ISSUE TITLE
Beta 9.16: Panning is lagging when game is paused

### ISSUE THREAD

**Issue by datenpate** [hovgaardgames/startupcompany#322]
When I pause the game and scroll with WASD the screen updates are lagging. This wasnt the case in the 8.8-beta.

MacBookPro12,1
Intel Core i7 3,1 GHz
16 GB RAM

I attached a cpuprofiler output.
[CPU-20170416T142339.cpuprofile.zip](https://github.com/hovgaardgames/startupcompany/files/924265/CPU-20170416T142339.cpuprofile.zip)

**Comment by rremo** [comment]
Its lagging in the late game, with 30 Workstation and a lot of items and componets?

Like:
![lategame_unbenannt2](https://cloud.githubusercontent.com/assets/16868650/25071264/f210d2ee-22b2-11e7-9c10-b38942b42444.jpg)

**Comment by datenpate** [comment]
No. Just from the beginning of the game. No workstations and nothing else in the office.

**Comment by jhovgaard** [comment]
@datenpate How do you pan? Mouse-dragging or WASD?

**Comment by jhovgaard** [comment]
Fixed, super smooth now :-)
