### ISSUE TITLE
Beta 9.16: CTO feature view scrolls down when hitting space key

### ISSUE THREAD

**Issue by datenpate** [hovgaardgames/startupcompany#323]
I expect to toggle "pause" when hitting the space key. But in the CTO feature scrollview it is just scrolling down one page.
<img width="813" alt="bildschirmfoto 2017-04-16 um 15 27 53" src="https://cloud.githubusercontent.com/assets/208993/25071487/5a3ddc62-22b9-11e7-8e60-c08e8d14c7d1.png">

**Comment by jhovgaard** [comment]
Disabled "space scrolling".
