### ISSUE TITLE
Beta 9.16: Adding "New instance" in hosting does not decrement components

### ISSUE THREAD

**Issue by datenpate** [hovgaardgames/startupcompany#324]
When I add a new instance, the components are not substracted from the inventory.

<img width="804" alt="bildschirmfoto 2017-04-16 um 18 34 37" src="https://cloud.githubusercontent.com/assets/208993/25072617/7a6b8024-22d3-11e7-850d-df8c8f4ed75f.png">

**Comment by jhovgaard** [comment]
Good catch. Fixed!
