### ISSUE TITLE
Items/Furniture are overlapping

### ISSUE THREAD

**Issue by datenpate** [hovgaardgames/startupcompany#325]
see screenshot
<img width="633" alt="bildschirmfoto 2017-04-17 um 00 19 33" src="https://cloud.githubusercontent.com/assets/208993/25074759/b101bbfa-2303-11e7-8d58-77c325fcc493.png">

Jonas: Includes other items like meeting table and and glasswalls.

**Comment by markrichey** [comment]
Hello,
Just had the issue when placing a desk in Beta 12.4.

![screen shot 2017-08-14 at 21 37 33](https://user-images.githubusercontent.com/12082867/29290674-e636e154-8138-11e7-90ff-012d669b0a71.png)

All the best and thanks for a great game.

Mark

**Comment by MazeBank** [comment]
Hello @markrichey 
Thank you for this report!
As staff has been notified so far they will look into this as soon as possible!

Jason </>

**Comment by jhovgaard** [comment]
All fixed!
