### ISSUE TITLE
Beta 9.17: Too much workstation with "old" savegame

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#326]
![unknownq94](https://cloud.githubusercontent.com/assets/16868650/25084607/dc5dd806-235d-11e7-94f5-73a843a2ebc1.jpg)

**Comment by jhovgaard** [comment]
It is a bug, but it only happens for people who're coming from earlier versions, not new ones. I think this is the best solution, allowing negative workstations.
