### ISSUE TITLE
Beta 9.18: Lead developer was able to develop module despite missing components

### ISSUE THREAD

**Issue by Freakspot** [hovgaardgames/startupcompany#330]
I have no idea how this happened, now that it did I cannot replicate it again. 

**What I did:**
- Selected the lead dev and wanted to develop a new interface module
- Saw that I was missing a wireframe component, but was still able to begin the process
- Wireframe components went down to -1 (see screenshots), module finished anyway

![missing-components](https://cloud.githubusercontent.com/assets/2371427/25278653/4a4e62a6-26a4-11e7-8273-fdbbfc813493.PNG)

**Comment by Freakspot** [comment]
Although I seem to have all the required components now, I cannot develop another Interface module again, effectively breaking the game for me. Clicking on the module does trigger the clicky sound, but the process does not begin.

![image](https://cloud.githubusercontent.com/assets/2371427/25279027/74a87e6e-26a5-11e7-8c51-1c09e89a5e91.png)

**Comment by jhovgaard** [comment]
Fixed first part of this one. Trying to reproduce the -1.

**Comment by jhovgaard** [comment]
-1 fixed.
