### ISSUE TITLE
Beta 9.19: Accept/decline contract window does not show how long components will take to produce

### ISSUE THREAD

**Issue by Freakspot** [hovgaardgames/startupcompany#332]
Once you've opened the "accept/decline" window for new contract, you're not able to close it again without declining it which is kind of annoying for me as a player, because I sometimes need to check how long specific components will take before I'm able to decide whether I wanna accept or decline it.

**Comment by Freakspot** [comment]
As this is done by design and the "Chargeable hours" thingy is supposed to indicate how long you'll need to produce components, it should be renamed to be more clear for new players.

Maybe "Estimated time"?

**Comment by jhovgaard** [comment]
Added. Now called "Production hours"
