### ISSUE TITLE
Beta 9.20: Cancelling the production of a component will create a border around it

### ISSUE THREAD

**Issue by Freakspot** [hovgaardgames/startupcompany#333]
Not sure if intended or not?
As soon as I click on the component again, the border disappears again.

![image](https://cloud.githubusercontent.com/assets/2371427/25289715/18c288da-26cb-11e7-865b-f1ffc768ce85.png)

**Comment by jhovgaard** [comment]
It's by design to make it easier to remember what you're working on in the beginning :-)
