### ISSUE TITLE
Beta 9.18: Typos and similar

### ISSUE THREAD

**Issue by Freakspot** [hovgaardgames/startupcompany#334]
It says "LandingPage". The f in framework shouldn't be capitalized.
![image](https://cloud.githubusercontent.com/assets/2371427/25289332/724e8e78-26c9-11e7-9d48-ab0641180485.png)

Is there a reason that UI is not spelled with a capital i?
![image](https://cloud.githubusercontent.com/assets/2371427/25289453/f7e95068-26c9-11e7-874b-e93ab3493642.png)

It says FixedPrice. Goes for all those "labels" I think? Maybe intended?
![image](https://cloud.githubusercontent.com/assets/2371427/25290017/69964c28-26cc-11e7-9980-8ec7f1a4e3b6.png)

Most of those shouldn't be single words, should they?
![image](https://cloud.githubusercontent.com/assets/2371427/25290227/6bb2af5a-26cd-11e7-9d13-51ca65aa5e38.png)

**Comment by Freakspot** [comment]
Says FreeBeverages.
![image](https://cloud.githubusercontent.com/assets/2371427/25290615/1684c26e-26cf-11e7-8613-916be824bad6.png)

**Comment by Freakspot** [comment]
All of these are single words, too.

![image](https://cloud.githubusercontent.com/assets/2371427/25307899/da469148-27a9-11e7-8cd1-ba5c840a9e92.png)

**Comment by jhovgaard** [comment]
All fixed!
