### ISSUE TITLE
Beta 9.21: Missing game icon in taskbar on Linux

### ISSUE THREAD

**Issue by Freakspot** [hovgaardgames/startupcompany#337]
I'm using Antergos, icon shows up as a squared question mark.

![image](https://cloud.githubusercontent.com/assets/2371427/25307735/5b2ff258-27a6-11e7-9bb0-956774769f37.png)

**Comment by johannwagner** [comment]
Same on Mac. 

Startup Company is next to Steam.
![bildschirmfoto 2017-08-02 um 21 51 05](https://user-images.githubusercontent.com/12380026/28892001-badca59a-77cc-11e7-8f8a-672dfebf7196.png)
