### ISSUE TITLE
Load screen loop issue

### ISSUE THREAD

**Issue by MrBidule** [hovgaardgames/startupcompany#338]
Hi,

The latest version (9.23) does not work on my PC.

https://youtu.be/NG1lB_eubQ4

The version 8 works perfectly

   Operating System: Windows 7 Professionnel 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr.170307-1800)
           Language: French (Regional Setting: French)
System Manufacturer: System manufacturer
       System Model: System Product Name
               BIOS: BIOS Date: 09/12/13 15:27:11 Ver: 38.01
          Processor: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 CPUs), ~3.4GHz
             Memory: 16384MB RAM
Available OS Memory: 16352MB RAM
          Page File: 4272MB used, 28427MB available
        Windows Dir: C:\Windows
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: Using System DPI
 System DPI Setting: 96 DPI (100 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.01.7601.17514 64bit Unicode

Card name: NVIDIA GeForce GTX 1070

**Comment by jhovgaard** [comment]
Thanks for reporting this!

We're seeing issues with savegame compatibility. A quick fix right now:
* Go to Documents/Startup Company folder
* Move all files to another destination (or delete them if you don't mind losing your savegame).

Also if you can attach the files here that would be very helpful too!

**Comment by MrBidule** [comment]
It works, thanks ! ;)

**Comment by MrBidule** [comment]
My save:

[Save.zip](https://github.com/hovgaardgames/startupcompany/files/949317/Save.zip)

**Comment by jhovgaard** [comment]
Thanks, much appreciated!

**Comment by jhovgaard** [comment]
Fixed. Fresh version uploaded to Humble Bundle.
