### ISSUE TITLE
humble bundle project name changed to 'Beta 9'

### ISSUE THREAD

**Issue by MindALot** [hovgaardgames/startupcompany#347]
FYI - "Startup Company" has been renamed in humble bundle to 'Beta 9'.

If this was not intentional - may want to adjust it.

**Comment by MindALot** [comment]
As a user - it is confusing when searching for the game.  I just noticed beta 8 was named 'Beta 8' as well.
The issue sticks out more when searching ones library alphabetically.

**Comment by jhovgaard** [comment]
Good idea, thanks! Fixed it right away. CTRL+F5 to see the change.
