### ISSUE TITLE
website - no obvious link to prefered feedback/issues location.

### ISSUE THREAD

**Issue by MindALot** [hovgaardgames/startupcompany#348]
I could only find this github location due to reddit post.

**Comment by rremo** [comment]
A link to GitHub would be useful for some players.

I think the Idea is:
You and others can give feedback via Facebook, Twitter or Discord:
https://www.facebook.com/startupcompanygame
https://twitter.com/hovgaardgames
https://discord.gg/0zDkARA91ghgKlU4 <- Very active there!

**Comment by jhovgaard** [comment]
Added links in main menu
