### ISSUE TITLE
Tooltip doesn't always match current module in Lead Dev view

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#349]
The tooltip that you get when hovering over the module that is currently in the making in the Lead Developer view doesn't update when you change module _and_ the percentage bar is at 0%. (For example when there is missing components or when you change while paused.) Instead is sticks to displaying the information for the original choice.

Here are some screenshots to clarify:

![sc_bug_screenshot_1](https://cloud.githubusercontent.com/assets/4162261/25348965/4e68a4cc-2920-11e7-9ca6-7cee5d2c8cc2.png)
![sc_bug_screenshot_2](https://cloud.githubusercontent.com/assets/4162261/25348981/5fa6b472-2920-11e7-8f03-62d6774bb2d6.png)
![sc_bug_screenshot_3](https://cloud.githubusercontent.com/assets/4162261/25348984/6221c08e-2920-11e7-8b09-e4efb52a1154.png)

**Comment by jhovgaard** [comment]
Fixed this by disabling the popover for the preview. I believe the popover was more confusing than helpful.

Thanks for reporting the bug!
