### ISSUE TITLE
Missing Tooltips Collection

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/startupcompany#35]
# Collection of potentially missing tooltips
- [ ] Past-Due Fee

**Comment by InDieTasten** [comment]
Issues marked s:discussion shouldn't be added to milestones. Especially collection type of issues.

**Comment by BrutalCSkakan** [comment]
- [ ] How much mood/speed/whatever does a specific item give you in the shop

**Comment by jhovgaard** [comment]
Closing this for now. All above tips added.
