### ISSUE TITLE
Windows: Location of Documents Folder 

### ISSUE THREAD

**Issue by johannwagner** [hovgaardgames/startupcompany#351]
Windows contains a settings to set the Documents folder. SC ignores that folder and creates a Documents folder in user directory, even if the setting contains a different path.

This issue was mentioned by ener156 in Discord.

**Comment by PeachIceTea** [comment]
Should be fixed by using [app.getPath("documents")](https://electron.atom.io/docs/api/app/#appgetpathname). I am not sure what it returns on Mac or Linux, someone should check that. Don't let that stop you from fixing #251 though.

**Comment by jhovgaard** [comment]
Closing, but with reference to #251
