### ISSUE TITLE
Duplication of modules and components when trying to switch module in lead dev view

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#354]
When you're trying to change which module to make in the lead developer view, but the module you're trying to switch to is missing components, the game still "returns" the modules and components used to make the current module while not actually switching module. This essentially enables the player to duplicate modules and components.

Here's a video for demonstration: [https://www.youtube.com/watch?v=b92G3SgkPjo](https://www.youtube.com/watch?v=b92G3SgkPjo)

**Comment by jhovgaard** [comment]
Fixed.
