### ISSUE TITLE
10.2: Various issues/errors

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#358]
**From Jarule @Discord:**
If you start a new game and no employees hired:
![untitled-2](https://cloud.githubusercontent.com/assets/16868650/25784166/4da228bc-3369-11e7-8032-6c26b2574ca9.jpg)
With 1 employee:
![unknown2](https://cloud.githubusercontent.com/assets/16868650/25784157/29312762-3369-11e7-8e0f-0ef987e607c1.jpg)

**From Jarule @Discord: Text is missing.**
![untitled-1](https://cloud.githubusercontent.com/assets/16868650/25784149/e2a9ea90-3368-11e7-9e57-1276df88843d.jpg)

**From TehKingPenguin @Discord: double $ sign beside cancel**
![unknown](https://cloud.githubusercontent.com/assets/16868650/25784148/de2a4712-3368-11e7-8b7b-3a524baf0999.jpg)

**"Undefined"**
![unbenannt-3](https://cloud.githubusercontent.com/assets/16868650/25784187/ef89d2ba-3369-11e7-9bce-c9da0191a8e2.jpg)

**Comment by rremo** [comment]
An other:
![unbenannt-4](https://cloud.githubusercontent.com/assets/16868650/25784339/3b6fce22-336b-11e7-9272-acf1672a9350.jpg)
german lang.

**Comment by jhovgaard** [comment]
Partly done. Employee view are going to be revised therefore no changes.
