### ISSUE TITLE
Missing translations Beta 10.2 in french

### ISSUE THREAD

**Issue by DryTutoVincentH** [hovgaardgames/startupcompany#359]
Hello,

here is some missing translations that I have see in the game : 

- low-medium-high (in the urgency of the contract)
![startupcompany-beta10 2_2017-05-08_10-20-18](https://cloud.githubusercontent.com/assets/28527550/25795975/01c1b902-33d8-11e7-9459-a89f486de485.png)

- in finances, in budget there is the word "contract from" and not the french word "contrat de" : 
![startupcompany-beta10 2_2017-05-08_10-21-30](https://cloud.githubusercontent.com/assets/28527550/25796020/3b4f8e6a-33d8-11e7-8f3e-6eabd093a526.png)

- In the same window finances, in transactions there is also missing translations : 
![startupcompany-beta10 2_2017-05-08_10-22-59](https://cloud.githubusercontent.com/assets/28527550/25796074/6ee3f856-33d8-11e7-97f0-b23346b7ebf2.png)

- In product, there are missing translations about Desktop (bureau in french) and for  "/day" (/jour in french)
![startupcompany-beta10 2_2017-05-08_10-24-54](https://cloud.githubusercontent.com/assets/28527550/25796147/b02c2ec8-33d8-11e7-9a17-8d042b2c310a.png)

- In the employee window, when my mouse past on the image, it's the english word (developper, hiresexecutive, etc)
![startupcompany-beta10 2_2017-05-08_10-26-21](https://cloud.githubusercontent.com/assets/28527550/25796207/ed2418a4-33d8-11e7-9e21-8e2675994147.png)

- When I want to quit the game : 
![startupcompany-beta10 2_2017-05-08_10-28-01](https://cloud.githubusercontent.com/assets/28527550/25796237/0589bcaa-33d9-11e7-89d6-dadfd4257908.png)

- In society view, the button for locked is not translate in french : 
![startupcompany-beta10 2_2017-05-08_10-28-37](https://cloud.githubusercontent.com/assets/28527550/25796273/2a9ca34a-33d9-11e7-8a99-4b6f0071f1ef.png)

- Same thing for buy objects (locked) : 
![startupcompany-beta10 2_2017-05-08_10-29-35](https://cloud.githubusercontent.com/assets/28527550/25796295/40419d04-33d9-11e7-9d49-ae6e1a02d55b.png)

- In mail box, there is missing translations about sender, inlbox, subject, day, list, etc : 
![startupcompany-beta10 2_2017-05-08_10-30-58](https://cloud.githubusercontent.com/assets/28527550/25796348/7f8f48da-33d9-11e7-8e76-c5965701b6dd.png)

- Comming in next beta : 
![startupcompany-beta10 2_2017-05-08_10-33-06](https://cloud.githubusercontent.com/assets/28527550/25796419/ba8827a4-33d9-11e7-9062-8a0d416a2b75.png)

- Buttons comfirm and cancel : 
![startupcompany-beta10 2_2017-05-08_10-34-37](https://cloud.githubusercontent.com/assets/28527550/25796484/f235eb96-33d9-11e7-8516-405a00c5477e.png)

I don't see others things missing but I add comment if I see something !!

Sincerely,

Vincent (UE4 Dry tuto)

**Comment by DryTutoVincentH** [comment]
Also : 
![startupcompany-beta10 2_2017-05-08_10-50-02](https://cloud.githubusercontent.com/assets/28527550/25797085/1f1a7e86-33dc-11e7-9fc5-7362a56b258a.png)

**Comment by DryTutoVincentH** [comment]
For a contract completed : 
![startupcompany-beta10 2_2017-05-08_11-12-09](https://cloud.githubusercontent.com/assets/28527550/25797855/3d4fc368-33df-11e7-9261-44006676753f.png)

**Comment by jhovgaard** [comment]
All fixed except the "coming in next beta" part, it will be removed in next Beta.

**Comment by DryTutoVincentH** [comment]
Thanks
