### ISSUE TITLE
10.2: Key control, arrow keys

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#361]
![unbenannt12515](https://cloud.githubusercontent.com/assets/16868650/25987269/84a963ba-36f3-11e7-976a-ebefcd9b788b.jpg)

I have searched a new employee and wanted to scroll left or right with the arrow keys (with the mouse wheel works!)
Unfortunately it did not work, I had to click somewhere first.

**Comment by jhovgaard** [comment]
Revised the hiring system. UI is not available anymore.
