### ISSUE TITLE
10.2 New products version with same framwork and features

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#362]
![ezgif-1-0d9a11b34d](https://cloud.githubusercontent.com/assets/16868650/25987908/29499e74-36f6-11e7-9328-a193ab07d8a7.gif)
(_**bad quality: gif is high compressed**_)

**Comment by jhovgaard** [comment]
By purpose actually, it allows you to change features.

Later I will add license cost when releasing new versions, which will make it more obvious.
