### ISSUE TITLE
10.3 Localization (German)

### ISSUE THREAD

**Issue by rremo** [hovgaardgames/startupcompany#364]
![suc_1-loc](https://cloud.githubusercontent.com/assets/16868650/26032860/ee4b3d92-389d-11e7-83bf-f4c5e51bc623.jpg)

**Comment by rremo** [comment]
After creating the product: 
![suc_2-loc](https://cloud.githubusercontent.com/assets/16868650/26032928/b3709328-389f-11e7-9175-f6b2e9f39f02.jpg)
![suc_3-loc](https://cloud.githubusercontent.com/assets/16868650/26032935/e8907ae6-389f-11e7-940a-789b24d417bc.jpg)

**Comment by jhovgaard** [comment]
Fixed!
