### ISSUE TITLE
Black game 

### ISSUE THREAD

**Issue by mikendk2** [hovgaardgames/startupcompany#372]
just happen 

![skaermbillede 2017-05-27 14 11 25](https://cloud.githubusercontent.com/assets/29000022/26521348/e8a1bdd2-42e6-11e7-9b40-89570798e929.png)

**Comment by jhovgaard** [comment]
Experienced this before. We need to figure out how to reproduce it.

**Comment by jhovgaard** [comment]
Fixed. It was caused by UI not updating when switching between employee types, allowing for example Lead Devs to get Sales Executive tasks assigned. Causing the game to crash.
