### ISSUE TITLE
Beta 10.14 : Can't complete a contract

### ISSUE THREAD

**Issue by A-xis** [hovgaardgames/startupcompany#373]
Hi,

I'm playing StartupCompany with the new beta 10, and I'm issuing a bug. I have won a contract, and I can't complete it.

![capture du 2017-05-31 15-09-53](https://cloud.githubusercontent.com/assets/2327024/26633313/41d73c7c-4613-11e7-9e29-6c3ae42e18a8.png)

How to reproduce :
During the bidding, close the windows
Sometimes, You can't complete the contract, the option is not present.

**Comment by jhovgaard** [comment]
Thanks for reporting this. I have a good idea why this is happening. Will look into it!

**Comment by A-xis** [comment]
Already got this during Beta9

**Comment by A-xis** [comment]
Still present in beta 11.1

**Comment by jhovgaard** [comment]
Finally fixed!
