### ISSUE TITLE
Incorrect modal when selecting employees while modal is open.

### ISSUE THREAD

**Issue by XekeDeath** [hovgaardgames/startupcompany#383]
I click on the Sales exec, and the modal box appears to show me that he can search for a contract.
I then click on my developer in the background without closing the Sales Manager box.
The modal now shows my developer as part way through searching for a contract, instead of the icons of the components they can make.

When selecting the developer first, then clicking the Sales Manager, the modal box shows an empty list of components the Sales Manager can make, rather than the contract search options.

![image](https://user-images.githubusercontent.com/5275413/27184927-05a65056-5227-11e7-8d8b-b53a993e6d23.png)
![image](https://user-images.githubusercontent.com/5275413/27184949-174c718c-5227-11e7-94a8-a69e054bdd4e.png)

**Comment by jhovgaard** [comment]
Thanks for reporting!

Already fixed this one in upcoming Beta 11. Did it break your savegame yet? If you reload the game after doing above it will crash. If so just send me your savegame and I can fix it (located in Documents/Startup Company)

**Comment by XekeDeath** [comment]
I haven't quit yet..! I'm still going..
Kinda afraid to close it now, I might just play until I lose...

**Comment by jhovgaard** [comment]
Haha no worries, I can always fix it without any loss!

**Comment by jhovgaard** [comment]
No fixed in Beta 11.
