### ISSUE TITLE
Beta 11.8: Auto Repeat switch still active after removing and reassigning employee to desk

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#394]
When you remove an employee from a desk they are automatically deattached from their manager. When you reassign them to a desk however, they keep their auto repeat switch on while not being attached to a manager. It doesn't affect gameplay, since they don't continue to auto repeat after they have finished the currect component, but it is still a confusing UI bug.

Here's a video for demonstration: https://youtu.be/-vsy2ItpK5A

**Comment by jhovgaard** [comment]
Fixed!
