### ISSUE TITLE
[Linux] Menu screen shows part of game

### ISSUE THREAD

**Issue by Freakspot** [hovgaardgames/startupcompany#402]
Basically I just start the game, hover over the middle part of the window and it reveals.. this.
![image](https://user-images.githubusercontent.com/2371427/27996369-db6ed480-64e0-11e7-8cd8-39b5cdfe3900.png)

**Comment by jhovgaard** [comment]
Closing this one. Talked with Freakspot off GH and he's not using Ubuntu (only supported dist)
