### ISSUE TITLE
Can´t play the game...loading screen

### ISSUE THREAD

**Issue by Gowanni** [hovgaardgames/startupcompany#404]
i Can´s play the game...i start the Game and get the loading screen , but its never finished loading

**Comment by jhovgaard** [comment]
Hi Gowanni,

Thank you for reporting.

Can you tell me what beta version you are running?

Also, can you attach your savegame file? Either here or send it to my email at jhovgaard@gmail.com. Your savegame files are located in Documents\Startup Company. Files are starting with sg_.

**Comment by Gowanni** [comment]
hi,

 

first sorry for my bad english ^-^

i download the newst beta version (11-10), first time i run the game, i want to load my safegame from the last beta version and than was the loading screen and it loads for hours and nothing work.

 

hope u understand what i mean ._.

 

 

 

Gesendet: Montag, 10. Juli 2017 um 15:13 Uhr
Von: "Jonas Hovgaard" <notifications@github.com>
An: hovgaardgames/startupcompany <startupcompany@noreply.github.com>
Cc: Gowanni <PhilStephan@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [hovgaardgames/startupcompany] Can´t play the game...loading screen (#404)


Hi Gowanni,

Thank you for reporting.

Can you tell me what beta version you are running?

Also, can you attach your savegame file? Either here or send it to my email at jhovgaard@gmail.com. Your savegame files are located in Documents\Startup Company. Files are starting with sg_.

**Comment by jhovgaard** [comment]
Totally understand your english, no worries :-)

Can you send me the your savegame? Either here or send it to my email at jhovgaard@gmail.com. Your savegame files are located in Documents\Startup Company. Files are starting with sg_.

**Comment by jhovgaard** [comment]
Savegame received on email. Will look into this tonight.

**Comment by jhovgaard** [comment]
Fixed
