### ISSUE TITLE
White screen after purchase a new building

### ISSUE THREAD

**Issue by diegooe8** [hovgaardgames/startupcompany#405]
I was playing and when I decided to change the building (to the 2nd building) the screen turn into white forever. I had 8 employees, bought the new place and then the white screen appeared.
I hope that this will be usefull for you. Thanks for all!

**Comment by jhovgaard** [comment]
Hi!

Thanks for reporting. I tried to reproduce, but with no luck. Are you still experiencing the problem? Or did it get fixed after restarting?

If you still have the issue, can you send me your savegame? It's located in Documents/Startup Company. Savegames starts with sg_.

Thanks!

**Comment by diegooe8** [comment]
I restarted the game and when I touched 'continue' the game was like before I bought the new building. So I tried again and I could buy it.
Now my savegame is already one step after the purchase. :/

Thanks you!

**Comment by xSickboyx** [comment]
Me too. 8 employees. Buy the 2nd building and white screen forever.

**Comment by xSickboyx** [comment]
Restarted and now works. I took a loan before change building.

**Comment by lichtspeed** [comment]
i also have this problem when i bought that medium building

**Comment by jhovgaard** [comment]
If anyone finds a way to reproduce this, please let me know.

**Comment by johannwagner** [comment]
[01:38] Arts: anybody have the problom where you want to rent a new place for the first time, that when you press rent, the screen just turns white and nothing els happends? :smiley:

**Comment by jhovgaard** [comment]
Fixed
