### ISSUE TITLE
Can not hire new workers!

### ISSUE THREAD

**Issue by KentaM8** [hovgaardgames/startupcompany#406]
Can not hire new workers!
Missing a button?

<img width="1423" alt="canthire" src="https://user-images.githubusercontent.com/30157370/28186847-e3a5eb18-681c-11e7-9e92-57e910d6f58d.PNG">

**Comment by jhovgaard** [comment]
Thanks for reporting! 

Can you attach your savegame and options file? It is located in Documents\Startup Company

**Comment by KentaM8** [comment]
Here is my saved game and options file
http://ffgc.se/OtherFilestc/

**Comment by jhovgaard** [comment]
I think this is related to DPI. Are you running Windows with 125% scaling?

**Comment by KentaM8** [comment]
Nope here is my screen settings
<img width="184" alt="resul" src="https://user-images.githubusercontent.com/30157370/28187266-676d1434-681e-11e7-9c01-937d88e7b1a6.PNG">
<img width="887" alt="canthire1" src="https://user-images.githubusercontent.com/30157370/28187267-692b0b1e-681e-11e7-8a47-52ffed296976.PNG">

**Comment by shequet** [comment]
I have the same problem, I can not click on a candidate, I'm under (Windows 10, Surface Pro 4, 2736x 1824, 100%)

**Comment by jhovgaard** [comment]
Very interesting! Thanks for helping solving this.

Can you turn Developer Mode (in Options) and the in the console, try and execute these commands, and then message me the result.

First this:
```javascript
require('electron').screen.getPrimaryDisplay().scaleFactor;
```

Then this:

```javascript
window.devicePixelRatio;
```

**Comment by shequet** [comment]
Result First 2
Result Seconde 2

**Comment by shequet** [comment]
require('electron').screen.getPrimaryDisplay().scaleFactor;
2
window.devicePixelRatio;
2

**Comment by jhovgaard** [comment]
Perfect! Got a solution for you guys, hang on!

**Comment by shequet** [comment]
![snip_20170713235257](https://user-images.githubusercontent.com/5202159/28189489-6f12944a-6826-11e7-82e7-9e82c6347dae.png)

**Comment by jhovgaard** [comment]
Beta 11.12 is now available in your library. Grab it here: https://www.humblebundle.com/home/library

It should force DPI to be 100% and thereby fixing the UI.

**Comment by jhovgaard** [comment]
Btw, please let me know if it fixed the issue :-)

**Comment by shequet** [comment]
This is corrected, thanks 
![snip_20170714010632](https://user-images.githubusercontent.com/5202159/28191459-af5a1960-6830-11e7-846c-d77079e66fe8.png)

**Comment by jhovgaard** [comment]
Great, thank you too!
