### ISSUE TITLE
Add "Big UI" support

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#407]
Use DPI scaling (125%). Need CSS optimization.

**Comment by elmakong** [comment]
this issue still persist on beta 12.3, the menu on bottom screen not resized on 4k monitors with 250% scaling. the font also, having a hard time reading whats written on screen.
![image](https://user-images.githubusercontent.com/8539103/29244494-3cab2d94-7fe3-11e7-8136-9877813fb163.png)

**Comment by jhovgaard** [comment]
Implemented.
