### ISSUE TITLE
Furniture are overlapping

### ISSUE THREAD

**Issue by MarcoBoekholt** [hovgaardgames/startupcompany#408]
The left chair of the **Large Meeting Table** is overlapping with the **Glass Wall**
![d5fa9c040bbfbcb496c4635e37764303](https://user-images.githubusercontent.com/1371927/28289189-0062c3d4-6b42-11e7-82aa-1f1dc8b8ff4e.jpg)

**Comment by Cliff122** [comment]
Duplicate of #325?

**Comment by MarcoBoekholt** [comment]
Well almost the same except its a other furniture

**Comment by jhovgaard** [comment]
Updated #325 to include all items. Closing this. Thanks for reporting!
