### ISSUE TITLE
Beta 12.1: "Share" is always 0%

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#410]
The share you own in a competitor company is always displayed as 0%, regardless of how many shares you actually own in it.

![share_0_percent_1](https://user-images.githubusercontent.com/4162261/28393288-484bd0f0-6ce6-11e7-9c88-f00c2231e349.png)
![share_0_percent_2](https://user-images.githubusercontent.com/4162261/28393289-4a376334-6ce6-11e7-9b1d-d93c5bea2e23.png)

**Comment by jhovgaard** [comment]
Added more digits to show low share amount.
