### ISSUE TITLE
Beta 12.1: Inconsistent unit for "Owned Stocks"

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#411]
In the competitors view, your share in your own products is shown in percent, while your share in competitors is shown as the amount of shares you own.
![inconsistent_ui_1](https://user-images.githubusercontent.com/4162261/28393352-8b074ff0-6ce6-11e7-89fd-d6c8fb6a1272.png)

**Comment by jhovgaard** [comment]
Now showing "-" instead of "100%" for own products.
