### ISSUE TITLE
Beta 12.1: Logo background always blue

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#412]
Every product has a different background color for their logo in the products list, in the product view however the background is always blue, regardless of which product you're looking at.
![different_logo_colors_1](https://user-images.githubusercontent.com/4162261/28393432-fe0e9990-6ce6-11e7-945c-74fabb2606ac.png)
![different_logo_colors_2](https://user-images.githubusercontent.com/4162261/28393430-fe0a1e10-6ce6-11e7-9bf6-2bd53744b1b9.png)
![different_logo_colors_3](https://user-images.githubusercontent.com/4162261/28393431-fe0b29a4-6ce6-11e7-8f90-dd19527e40e9.png)

**Comment by jhovgaard** [comment]
Fixed!
