### ISSUE TITLE
Beta 12.1: TV's can be placed so they intersect

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#416]
Since TV's are only take up one box in grid they can be placed directly next to each other, which results in them intersecting each other.
![tvs_intersecting_1](https://user-images.githubusercontent.com/4162261/28429782-368f2c34-6d7e-11e7-8ae5-00a2d831cb71.png)

**Comment by jhovgaard** [comment]
Fixed! TVs now take up 2x1
