### ISSUE TITLE
Beta 12.1: Income from competitor products doesn't show in "Last 30 Days"

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#417]
The income you get from companies you own shares in only shows up in the transactions tab, not in the "Last 30 Days" box like the revenue from your own products does.

![competitor_product_revenue_not_showing_1](https://user-images.githubusercontent.com/4162261/28429904-c375bef6-6d7e-11e7-8f16-5cd1c7749af2.png)
![competitor_product_revenue_not_showing_2](https://user-images.githubusercontent.com/4162261/28429903-c374dc5c-6d7e-11e7-9491-11bd1ad8a2bd.png)

**Comment by jhovgaard** [comment]
Fixed!
