### ISSUE TITLE
Beta 12.1: Inconsistent phrasing in lead developer view and status bar

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#418]
When a lead developer is missing the compontents required to make a certain module it shows up as "Missing requirements" in the employee view, but in the employee status bar it says "Missing Components" instead.
![inconsistent_phrasing_1](https://user-images.githubusercontent.com/4162261/28430365-99821372-6d80-11e7-8e3e-876a5347d25d.png)

**Comment by jhovgaard** [comment]
Now using "missing components" everywhere

**Comment by Cliff122** [comment]
Some modules require other modules though. What will it say if they are missing those?

**Comment by jhovgaard** [comment]
You're right :D

**Comment by jhovgaard** [comment]
Now using "missing requirements" everywhere
