### ISSUE TITLE
Beta 12.1: Inconsistent time formats

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#420]
In the schedule tab of an employee, where you select their working hours, time is displayed in 12h format. However, in the HR manager view and also the ingame clock time is displayed in 24h format.

![inconsistent_time_format_1](https://user-images.githubusercontent.com/4162261/28433900-a2f00222-6d8d-11e7-9ee2-857cb82623bf.png)
![inconsistent_time_format_2](https://user-images.githubusercontent.com/4162261/28433902-a43a98d6-6d8d-11e7-8e1f-196d0fb41dc5.png)

**Comment by jhovgaard** [comment]
Added timeformat to options view.
