### ISSUE TITLE
Beta 12.1: Displaying of very small shares

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#421]
This is more of an improvement than a bug but I think it would be a small but nice addition to the game.

So, while the new system of displaying three decimals of your share in a company works well for showing percentages between 0.001 and 1, values even lower than that are rounded down to "0.000%" like this.

![replace_0_with_less_than_1](https://user-images.githubusercontent.com/4162261/28433283-5383d15c-6d8b-11e7-9cdf-179939ee06fb.png)

Adding more decimals isn't a good solution for both aesthetic and functional reasons. Instead you could add a "less than sign" (<) in front of the value if it is too low to be displayed so it's more clear that you don't actually own "0.000%" but instead so little that it can't be displayed. Like this.

![replace_0_with_less_than_2](https://user-images.githubusercontent.com/4162261/28433489-1dcddd9a-6d8c-11e7-8c87-cfde6cbb6766.png)

Or alternatively just "< 0%".

![replace_0_with_less_than_3](https://user-images.githubusercontent.com/4162261/28433500-2e1b4750-6d8c-11e7-83dc-d562cdb00463.png)

**Comment by jhovgaard** [comment]
Agree, I kinda prefer the last option " < 0%" Anyone else?
