### ISSUE TITLE
Beta 12.1: Trying to select module with requirements missing duplicates components

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#422]
In the lead developer view, when a module is in the making and you attempt to switch to another module that you don't have all the required components to make, the game "returns" the components and modules required to make the current module while not actually switching which module is currently in the making. This makes it possible to "switch" module over and over and create as many components or modules as you like out of thin air. 

Here's a video for demonstration: https://youtu.be/PAq0OV6gwYA

**Comment by jhovgaard** [comment]
Fixed!
