### ISSUE TITLE
Beta 12.1: Auto repeat causing component duplication

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#423]
When a lead developer on auto repeat is waiting because they're missing required components, you can just cancel what they're currently making which will "return" all components and modules used for that module. Then you can just start making the module again, put it on auto repeat, and when it pauses click cancel. Doing this over and over again enables you to essentially create an infinite amount of modules out of thin air.

Here's a video for demonstration: https://youtu.be/83t_P_zhV_s

**Comment by jhovgaard** [comment]
Fixed, now check for missing requirements before returning components.
