### ISSUE TITLE
Beta 12.1: Products don't generate income while a new version is being made

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#424]
When a new version of a product is in the making, the existing version doesn't generate any revenue.

![products_no_income_1](https://user-images.githubusercontent.com/4162261/28478179-8753a8e6-6e57-11e7-8aaf-d40a2c907596.png)
![products_no_income_2](https://user-images.githubusercontent.com/4162261/28478182-875a39f4-6e57-11e7-89d2-7d79294235e9.png)
![products_no_income_3](https://user-images.githubusercontent.com/4162261/28478180-8756d14c-6e57-11e7-930c-fc0944ce925d.png)
![products_no_income_4](https://user-images.githubusercontent.com/4162261/28478181-87574852-6e57-11e7-8318-759970235470.png)

**Comment by jhovgaard** [comment]
Fixed
