### ISSUE TITLE
Beta 12.1: Unexpected order when sorting by level in employees view

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#426]
When sorting the list of employees by their level it sorts them in the order "Beginner, Expert, Intermediate" instead of "Beginner, Intermediate, Expert" which would make more sense.

![weird_level_sorting_1](https://user-images.githubusercontent.com/4162261/28481141-ffa668cc-6e63-11e7-9eb3-2e8633c665af.png)

**Comment by jhovgaard** [comment]
Fixed
