### ISSUE TITLE
beta 11 lead developer not working under a manager

### ISSUE THREAD

**Issue by lichtspeed** [hovgaardgames/startupcompany#429]
i have 3 managers and they control all my workforce but only 1 lead developer wont do things automaticly

**Comment by jhovgaard** [comment]
@lichtspeed is auto repeat turned on for the individual lead developer? There is a switch in the bottom of the page named "auto repeat". It should be green.

**Comment by jhovgaard** [comment]
Was caused by old version of Beta 11.
