### ISSUE TITLE
Beta 12.2: 'onUnsubscribe' event for mods

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#432]
It would be nice to have an `onUnsubscribe` event in the Modding API that would execute when a user has clicked "Unsubscribe" but before the mod is actually removed. It could be used for removing data that the mod has added and to restore data that it has modified to prevent stuff from breaking when the mod is gone.

**Comment by johannwagner** [comment]
+1

**Comment by jhovgaard** [comment]
Will be implemented in next build. Here is how to use it:

``` javascript
exports.onUnsubscribe = done => {
    GetRootScope().options.saveGames.forEach(filename => {
        Helpers.LoadSettings(filename, settings => {
            settings.updatedFromUnsubscribe = true;
            console.log(settings.companyName);
            Remote.app.saveFile(filename, JSON.stringify(settings), null);
        });
    });

    console.log('making it hang, to test done event');
    setTimeout(() => {
        done();
    }, 5000);
};
```

Basically it's an empty method with a `done` event you have to fire when all actions are done. The event is added to ensure the game doesn't restart before your work is done.
