### ISSUE TITLE
Beta 12.2: Mod description on workshop overwritten on update

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#434]
Whenever you update your mod the description on the workshop page gets overwritten by the description from the `mod.json` file. I think the two should be separete since they serve different purposes. The one from `mod.json` is used to give a short description of the mod to be displayed ingame while the workshop description has more space to, for example describe and explain the mod in further detail.

**Comment by jhovgaard** [comment]
How about `short_description` and `description`? @johannwagner ?

**Comment by johannwagner** [comment]
Accepted. :b

Thanks in Advance!

Am 05.08.2017 7:33 nachm. schrieb "Jonas Hovgaard" <notifications@github.com
