### ISSUE TITLE
Beta 11.12: Hr manager is broken

### ISSUE THREAD

**Issue by coolbluethomas** [hovgaardgames/startupcompany#435]
1. My hr manager is showing no employees under "Affected employees":
![screenhunter 01](https://user-images.githubusercontent.com/5927841/28988400-feeba8ea-796f-11e7-9875-234d476fab09.png)

2. Click on manage Kate, of and on, poof, they're back:
![screenhunter 02](https://user-images.githubusercontent.com/5927841/28988407-02fed5a6-7970-11e7-8f08-7a4f9a2e83d0.png)

**Comment by coolbluethomas** [comment]
Also noticed, if I make everybody go on vacation via this screen, I still end up with a random worker here or there that is working. Strange.

**Comment by jhovgaard** [comment]
Hi there! 

Thanks for reporting! Can you attach your savegame? On Windows it's located in your "Saved Games" folder. Savegames starts with "sg_".

THanks!

**Comment by coolbluethomas** [comment]
Sure, although after realizing this I removed the problem, fired the manager and hired some more to spread my workers. Not knowing if you can trace it back I'll add it.

[sg_8bac7aa2-d.zip](https://github.com/hovgaardgames/startupcompany/files/1201858/sg_8bac7aa2-d.zip)

**Comment by jhovgaard** [comment]
Fixed. Was happening when workstation with manager/HR manager attached was deleted.
