### ISSUE TITLE
Beta 12.3: First contract achievement not firing

### ISSUE THREAD

**Issue by Freakspot** [hovgaardgames/startupcompany#438]
Didn't get the achievement for first contract completed despite having completed multiple contracts by now.

**Comment by legaultp1** [comment]
i agree. did not fire on mine either

**Comment by Cazsius** [comment]
Issue Persists on 12.3.

**Comment by Freakspot** [comment]
Also happens with the hiring 5 achievement I was told.

**Comment by jhovgaard** [comment]
FIxed
