### ISSUE TITLE
Suggestion: Add charities to the game/other ways to spend money

### ISSUE THREAD

**Issue by itsflashpoint** [hovgaardgames/startupcompany#445]
Would be cool if you were able to donate money to organizations/charities that would in return give you "free" advertising/hype to some of your products?

Also would be nice if you give a quarterly/weekly bonuses to some/all employees that would increase productivity for couple of weeks for some employees, and perm for a others, etc?

I dunno, I just have too much money and there is nothing that I can't afford >.<

**Comment by bartusek27** [comment]
I like it, but from my perspective, this is do-able as mod.

**Comment by RedstoneRaudi** [comment]
I'm acutally working on a mod, where you can send money to other companies

**Comment by jhovgaard** [comment]
Moved to Conflux
