### ISSUE TITLE
Beta 12.2 & 12.3: Corrupted save file

### ISSUE THREAD

**Issue by bartusek27** [hovgaardgames/startupcompany#446]
http://errors.angularjs.org/1.4.4/ngRepeat/dupes?p0=saveGame%20in%20ctrl.saveGames%20%7C%20orderBy%3A%20%27-day%27%20track%20by%20saveGame.id&p1=4e056a70-2&p2=%7B%22id%22%3A%224e056a70-2%22%2C%22companyName%22%3A%22BARTOWEBY%20s.r.o.%22%2C%22gameover%22%3Afalse%2C%22fileName%22%3A%22sg_4e056a70-2.json%22%2C%22day%22%3A92%7D

Somehow, my savegame has corrupted. Attaching savegame file, just rename file extension to .json
[sg_4e056a70-2.txt](https://github.com/hovgaardgames/startupcompany/files/1215964/sg_4e056a70-2.txt)

**Comment by johannwagner** [comment]
Can you screenshot your savegame folder ?

**Comment by CZCraftMan** [comment]
By further investigation, it looks like [Real Brands mod](http://steamcommunity.com/sharedfiles/filedetails/?id=1098649803) started it.
It may be because of this

Screenshot
![screenshot157242](https://user-images.githubusercontent.com/11354418/29186707-97407502-7e0d-11e7-869f-ffbd2219fe2c.jpg)

**Comment by johannwagner** [comment]
Try to move the dton file out of the folder, should be the same as the json.

**Comment by CZCraftMan** [comment]
Nothing happened.

**Comment by bartusek27** [comment]
I can load it through "Continue game", but it wont print out in Load menu

**Comment by johannwagner** [comment]
Try to remove your options.json and make sure, that Steam does not download your savegame again.

**Comment by bartusek27** [comment]
Will try

**Comment by bartusek27** [comment]
I will try to fool Steam sync, gimme a minute

**Comment by bartusek27** [comment]
DONE:
I disabled Steam Cloud for Startup Company, then I removed in options excess files. That way, it loads properly.
