### ISSUE TITLE
Suggestion: Better HR

### ISSUE THREAD

**Issue by itsflashpoint** [hovgaardgames/startupcompany#448]
Heys,

Got another suggestion, it would be nice if you could make HR managers make their team take vacations if their mood goes under a certain percentage level that it set by you. It gets hard to keep track of 40+ employees and you know HR should be doing their job... :-)

**Comment by bartusek27** [comment]
Yea, I like this idea, it would give HR Managers another useful feature.

**Comment by legaultp1** [comment]
i agree. another option would be a checkbox to enable automatic schedule management based on the staff so they can decide their own schedule instead of being forced to work specific hours. like real life...
i have the schedule i want and it works better this way :)

**Comment by itsflashpoint** [comment]
Also It'd be nice to have the ability to add a night crew so you can have your company work 24/7.

**Comment by legaultp1** [comment]
not sure how that could work but what about 2 staff sharing the same desktop?
2-3 shift? night crew work on the same workstation as the day crew. would be more efficient I would think but might be a nightmare to implement

**Comment by itsflashpoint** [comment]
Yup thats how it would work.

**Comment by legaultp1** [comment]
i know this is getting a long thread but another idea for this... workstation get assigned a type of staff (dev, sales, HR...) the staff when they arrives, pick a random available workstation that match their job titles if their workstation is currently in use. As for the managers. it would work the same way. you would need more managers to address the staff and more hr staff. anyway, this is a random idea I'm shouting.

**Comment by jhovgaard** [comment]
Moved to Conflux
