### ISSUE TITLE
No mods in Mod Tab

### ISSUE THREAD

**Issue by VIPT0xic** [hovgaardgames/startupcompany#449]
I recently opened my SC and I visit the mods tab, to find "There's currently no mods available", even tho I have all the current mods downloaded?
![sc](https://user-images.githubusercontent.com/18243552/29214333-d771a2a4-7e9e-11e7-97cd-cd8a0abb4b0e.PNG)

**Comment by johannwagner** [comment]
It take some time to load. 2 to 3 seconds per Mod, you subscribed.

**Comment by VIPT0xic** [comment]
It says I have downloaded the mods 
![scmod](https://user-images.githubusercontent.com/18243552/29214401-1a694c1a-7e9f-11e7-85fd-946dc11faf49.PNG)

**Comment by johannwagner** [comment]
Which mod did you subscribe ?

**Comment by VIPT0xic** [comment]
All the mods -The Translation one

**Comment by RedstoneRaudi** [comment]
Create your mods folder manually at this path: C:\Users\YourUserName\Saved Games\Startup Company\

**Comment by VIPT0xic** [comment]
Yes, the update is coming.

**Comment by johannwagner** [comment]
Fixed by Jonas.
