### ISSUE TITLE
Beta 12.3 Load game error

### ISSUE THREAD

**Issue by thomaslos** [hovgaardgames/startupcompany#451]
Load game is borking:

```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: saveGame in ctrl.saveGames | orderBy: '-day' track by saveGame.id, Duplicate key: 8bac7aa2-d, Duplicate value: {"id":"8bac7aa2-d","companyName":"Coolblue BV","gameover":false,"fileName":"sg_8bac7aa2-d.json","day":236}
http://errors.angularjs.org/1.4.4/ngRepeat/dupes?p0=saveGame%20in%20ctrl.sa…2%3Afalse%2C%22fileName%22%3A%22sg_8bac7aa2-d.json%22%2C%22day%22%3A236%7D
    at game.min.js:1
    at game.min.js:1
    at Object.fn (game.min.js:1)
    at m.$digest (game.min.js:1)
    at m.$digest (ng-stats.js:116)
    at m.$apply (game.min.js:1)
    at HTMLButtonElement.<anonymous> (game.min.js:1)
    at HTMLButtonElement.dispatch (game.min.js:1)
    at HTMLButtonElement.g.handle (game.min.js:1)
```

I tried fixing it as dm'ed by changing the option json, but I keep getting a version that seems cached/steam cached? 

So somebody adviced changing via console:

`Cliff122 - vandaag om 16:54
You could modify the options from the console using GetRootScope().options and then save them using GetRootScope().saveOptions(). That's what I've been doing.`

That seemd to work, splicing gets rid of the values, but when I click load game, I again get the error and again my savegames are back :| 

Effectivly it is impossible to load a game, whelp? *puppy face*

**Comment by bartusek27** [comment]
#446

**Comment by thomaslos** [comment]
Same solution idd, that worked.

**Comment by bartusek27** [comment]
Great to hear that! Please, close the topic if everything is sorted out.

**Comment by thomaslos** [comment]
Tbh, it was quite the hassle to fix this, might be worth to fix it.

**Comment by bartusek27** [comment]
Actually, it is already being sorted out - through my report, it was classified as "Critical". No need to have dupes.

**Comment by thomaslos** [comment]
Is the source gone? I never installed the mod you speak off.

**Comment by thomaslos** [comment]
Actually, that should be the same kind of issue.
