### ISSUE TITLE
Remove the on vacation info popup

### ISSUE THREAD

**Issue by thomaslos** [hovgaardgames/startupcompany#453]
After multiple times having to click to get people on vacation this popup gets reeaallyyy annoying

http://imgur.com/a/MFnDT

**Comment by eUPHORIAplays** [comment]
If you do it through the HR MANAGER there is no pop up

**Comment by thomaslos** [comment]
yeah, but that doesn't work for the managers

**Comment by thomaslos** [comment]
biem http://steamcommunity.com/sharedfiles/filedetails/?id=1107559667
