### ISSUE TITLE
Feature Request: Make products more self sustained

### ISSUE THREAD

**Issue by thomaslos** [hovgaardgames/startupcompany#454]
A Product Owner or Product Boss/DomainOwner would be nice. Somebody that keeps an eye on the features for your product to maximize growth.

It is also a tad repetitive to open a products overview, see hype going down/being red, having to click an upgrade, and repeat. 

Could also perhaps mix and match, and maybe give the managers a bit more to do, specialize them. Lets say a product manager and a marketing manager, which will pay attention to resp. product features and marketing.

**Comment by eUPHORIAplays** [comment]
MASSIVE BUMP!!!

**Comment by jhovgaard** [comment]
Moved to Conflux. Probably fixed in Beta 13
