### ISSUE TITLE
from 800k users to 0 in 2 days

### ISSUE THREAD

**Issue by thomaslos** [hovgaardgames/startupcompany#459]
![image](https://user-images.githubusercontent.com/10689073/29231098-2a1b4b6c-7ee6-11e7-9680-3ae11d2430c4.png)

by request, the save game
[sg_8bac7aa2-d.zip](https://github.com/hovgaardgames/startupcompany/files/1219037/sg_8bac7aa2-d.zip)

**Comment by jhovgaard** [comment]
Fixed
