### ISSUE TITLE
Beta 12.3: Inconsistent background style for modules

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#464]
The "Content Management Module", "Email Module" and "Database Layer" don't have the same style for their backgrounds as all the other modules do.
![inconsistent_module_backgrounds_1](https://user-images.githubusercontent.com/4162261/29233256-53a7c2e4-7ef0-11e7-88aa-403def555924.png)

**Comment by Cliff122** [comment]
Just noticed that Frontend Modules are affected by this too.

**Comment by jhovgaard** [comment]
Fixed
