### ISSUE TITLE
Beta 12.3: Weird order in recruitment dropdown

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#466]
In the employee dropdown in the recruitment view, the HR manager is placed before the DevOps, even though it isn't unlocked until Tier 7 while DevOps in unlocked before at Tier 6.
![weird_employee_type_order_1](https://user-images.githubusercontent.com/4162261/29233546-c587ce44-7ef1-11e7-866f-4bc1cf76c6d2.png)

**Comment by jhovgaard** [comment]
Order by is now by tier.
