### ISSUE TITLE
Beta 12.3: Missing shopping competitors on old savegames

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#467]
The "new" competitors of the "Shopping platform" type aren't retroactively added to old savegames made when they didn't exist.
![missing_shopping_competitors_1](https://user-images.githubusercontent.com/4162261/29233767-1d66f922-7ef3-11e7-8196-83e04350b693.png)

**Comment by jhovgaard** [comment]
Should be working for future savegames.
