### ISSUE TITLE
Beta 12.3: Mood and actions on personnel screen

### ISSUE THREAD

**Issue by ArjanS87** [hovgaardgames/startupcompany#469]
I have just started playing your game today and liked it very much.
However, especially when going into the medium office, I found that my tactic of mass-holidays required an extensive amount of clicking to get everyone on the plane to a sunnier place.

Perhaps displaying the mood of employees and the three actions buttons on the personnel screen could reduce the required steps for working with them?

**Comment by Cliff122** [comment]
This feature actually kind of exist in the "HR Manager" which is unlocked at Tier 7.  The HR Manager can manage multiple managers and it also has a list of all the employees it's currentely managing where each one has a button to quickly send all of them on vacation.
![hr_manager_vacation](https://user-images.githubusercontent.com/4162261/29234336-8ee8654c-7ef6-11e7-9537-815b130dd44f.png)

**Comment by johannwagner** [comment]
@ArjanS87 I would close the issue, if the HR Manager is fitting for your needs.

**Comment by ArjanS87** [comment]
It does unlock relatively late and you'd need another person while usually the office is crammed full. But, if that is the way as a game concept than it is the way for me.

**Comment by jhovgaard** [comment]
Employees don't require vacation so quickly anymore.
