### ISSUE TITLE
Beta 12.3: Clicking names fault to moving

### ISSUE THREAD

**Issue by ArjanS87** [hovgaardgames/startupcompany#470]
I had a number of times today that clicking the name-bar to select a new action failed to open the GUI for some reason. It seemed like the hitbox for the action was quite small (I am no developer, so it is just a wild guess).
Also a number of times I ended up just grabbing the desk itself along with the employee.

The game requires quite some clicking, so it would be great to have that as optimized as possible.
Note: I only had one beer so I am quite comfortable with my aim ;)

**Comment by jhovgaard** [comment]
Fixed
