### ISSUE TITLE
Beta 12.3: Hovering over furniture while deleteing other furniture deletes both

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#471]
If you hover over a piece of furniture while you have another piece of furniture in your hand and press "Delete", both the furniture you're holding and the one you were hovering over are deleted. If the item you're hovering over is a workstation it also deletes the employee working at that station.

Here's a video to demonstrate: https://youtu.be/oUxPxoon7eU

**Comment by Cazsius** [comment]
To add on to this issue it also removes (fires) the employee at that desk. This issue is worse than expected.

**Comment by Cazsius** [comment]
Just Noticed that it also messes up the managers, and when the employee is removed it does not update the number of employees the manager is managing. To fix, you must remove the manager from the desk and reasign to reset the number.

**Comment by jhovgaard** [comment]
Fixed
