### ISSUE TITLE
12.3 All stock same revenue?

### ISSUE THREAD

**Issue by thomaslos** [hovgaardgames/startupcompany#472]
Tried multiple stock competitors, but they all pay the same ratio to the dollar I invest, is that on purpose?

(inkomsten=revenue)
![image](https://user-images.githubusercontent.com/10689073/29234098-14534050-7ef5-11e7-8d7a-8fcc74592f09.png)

**Comment by thomaslos** [comment]
Ergo, it doesnt really matter who to invest in. Might be nice to randomise this more so you get more diversion in the stock you would want.

**Comment by jhovgaard** [comment]
Revenue from stocks has been nerfed. You'll now have to sell stocks to gain revenue.
