### ISSUE TITLE
Suggestion - Components Quotas and auto build

### ISSUE THREAD

**Issue by legaultp1** [hovgaardgames/startupcompany#476]
Here is what i have in mind. should be fairly easy to implement
for the Developers, would it be possible to have a field for each of the components or a generic global field
let's say. a dev staff has 3-4 specialities.
the dev right now can make up to 300 components and continue.
some components are burning faster and other slower. so, can we have a feature that says. 
if there is X amount of components stored, go to the next open slot task 
(the task that is unlocked for the dev) and so on
example:

> If {Component[X] < Global_Dev_Component_Limit } {
>        Create Component[X]
> else
> Foreach { Items in Component } {
>        if { Staff_Component_IsUnlocked $Items} {
>              if { Items < Global_Dev_Component_Limit } {
>                  Create $Items
>                   break
>             }
>       }
> }
> 

note. this is not valid code but an example of what i was thinking. do not use it as is as it will not work :)

**Comment by bartusek27** [comment]
Hi **legaultp1**,

thank you for your suggestion, I like it!
Althrough, we need to discuss the implementation of this feature, rest assured, it will be taken in consideration.

Once again, thank you and have fun playing Startup Company!
Take care,
bartusek27

**Comment by Cazsius** [comment]
Corrected Label.

**Comment by jhovgaard** [comment]
Moved to Conflux.
