### ISSUE TITLE
Beta 12.3 - 12hr clock

### ISSUE THREAD

**Issue by spencerisadog** [hovgaardgames/startupcompany#477]
When the game is set to 12hr clock the top clock is still 24 hour.

**Comment by trdwll** [comment]
Confirmed here also.

**Comment by bartusek27** [comment]
Hi **spencerisadog**,

first off, thank you so much for your report!
I am notifying you, that I just replicated your problem and it will be fixed as soon as possible!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Fixed!
