### ISSUE TITLE
Bug: Auto-Repeat

### ISSUE THREAD

**Issue by trdwll** [hovgaardgames/startupcompany#479]
If you have auto-repeat on an employee, switch to a different building, then add that employee to a desk auto-repeat is enabled automatically. Even if you add the manager to a desk it shows as disabled under the manager so there's no need for a manager anymore. 
I'm not 100% sure, but I think it also does this if you remove an employee from a desk with auto-repeat on then add them back to a desk.

**Comment by bartusek27** [comment]
Hi **trdwll**,

first off, thank you so much for your report!
I am notifying you, that I couldn't replicate your problem and need more info on how to replicate it!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by bartusek27** [comment]
Can you provide me with your current version of a game?

**Comment by trdwll** [comment]
The steam version.

**Comment by bartusek27** [comment]
Hi again,

quite an interesting issue - I tried it again as you described but still, everything works as it should.
I will leave this open, so if anyone else will catch this bug too, let us know here in comments.

Thanks trdwll for opening this issue, I am so glad that you like SC, same as helping us make this game better!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Fixed.
