### ISSUE TITLE
Suggestion: close window on click exit

### ISSUE THREAD

**Issue by elmakong** [hovgaardgames/startupcompany#481]
i know that we could close the task window by pressing esc or clicking on the X button. but it would be awesome if we could just click outside the window to close it.

**Comment by bartusek27** [comment]
Hi **elmakong**,

thank you for your suggestion, I like it!
Althrough, we need to discuss the implementation of this feature, rest assured, it will be taken in consideration.

I agree with you, it could be cool to close it this way.

Once again, thank you and have fun playing Startup Company!
Take care,
bartusek27

**Comment by elmakong** [comment]
for website implementation, you could use the query "jquery close window on click outside" on google search. some logic there also.
it will be great if this feature is implemented.

**Comment by jhovgaard** [comment]
Implemented
