### ISSUE TITLE
Employee vacation timer stops when game unassigned from desk

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#484]

**Comment by rudywilkjr** [comment]
I confirmed the presence of this bug too. Employee doesn't progress on their vacation if you give their desk to someone else.  In the early stage of game giving the desk to another employee is a great way to manage rotating vacations.  Employees dialog menu shows their vacation progress when they're still assigned a desk, but when they do not have a current desk their status shows as "Unassigned"

**Comment by jhovgaard** [comment]
Seems to be fixed.
