### ISSUE TITLE
Two Small Grammatical Issues

### ISSUE THREAD

**Issue by QuantumHusky** [hovgaardgames/startupcompany#486]
A few small grammatical issues I have come across so far:

- On the Sales Executive popover view, the description for Search Time reads "Search time increase when you activate more filters." -> Should be "increases"

- On the Sales Executive popover view (under the Schedule tab), the tip at the bottom reads "Mood always decrease while working." -> Should be "decreases"

**Comment by bartusek27** [comment]
Hi **QuantumHusky**,

first off, thank you so much for your report!
I am notifying you, that I found them too and it will be fixed as soon as possible!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by QuantumHusky** [comment]
Also would like to note that duration of employee recruitment campaign option should be 1 day instead of 1 days :)

**Comment by jhovgaard** [comment]
Fixed thanks!
