### ISSUE TITLE
12.3 Osx -> mods didnt get the right permissions

### ISSUE THREAD

**Issue by thomaslos** [hovgaardgames/startupcompany#487]
Have three subscribed mods that work on my windows machine. Started my mac and because of workshop expected all three to be working on the mac. 

Only one worked (sconline), and it looks like an issue with file/folder rights, so I chmod the vacationator folder with 777: 

sconline has different rights than the rest:
![image](https://user-images.githubusercontent.com/10689073/29241731-75fc07da-7f7f-11e7-927b-d66face49a2d.png)

So I try to chmod the vacationator folder to try some stuff out. When try to open the folder, and its is empty:
![image](https://user-images.githubusercontent.com/10689073/29241739-9bd883b6-7f7f-11e7-8567-741ae914dc9e.png)

so I untar the file that was also downloaded:
![image](https://user-images.githubusercontent.com/10689073/29241744-a8efc064-7f7f-11e7-888c-d30df3d689c4.png)

And I f5 in the game, the vacationator works, the dutch translation is still not working, but to show you the difference:
![image](https://user-images.githubusercontent.com/10689073/29241711-25d558ba-7f7f-11e7-89e7-36041b1d9347.png)

**Comment by bartusek27** [comment]
Hi **thomaslos**,

first off, thank you so much for your report!
I am notifying you, that I can't replicate your problem because I don't have an Apple OS environment to test it out. 

If I may ask, on what OS did you created your mods?

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by thomaslos** [comment]
jhovgaard was working on this he knows the details. Made on windows -> dont load on mac. Load on mac, do work on mac (sconline was mac and that worked).

**Comment by jhovgaard** [comment]
Was fixed with the new mod archiver
