### ISSUE TITLE
12:3; selecting program in competitors list offers no back option to list

### ISSUE THREAD

**Issue by ArjanS87** [hovgaardgames/startupcompany#488]
When browsing competitors, you'd want to switch quickly between lists and the details of one of them.
I could find no such ability.

**Comment by bartusek27** [comment]
Hi **ArjanS87**,

thank you for your suggestion, I like it!
Althrough, we need to discuss the implementation of this feature, rest assured, it will be taken in consideration. 

From my opinion, it would definitely need some Back button.

Once again, thank you and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Moved to Conflux
