### ISSUE TITLE
Beta 12.3: Employees don't work from 16:00 - 00:00

### ISSUE THREAD

**Issue by RMidway** [hovgaardgames/startupcompany#489]
![image](https://user-images.githubusercontent.com/30957513/29241983-15e0fb4c-7f4a-11e7-9392-ac7449c050c9.png)

I gave my employee on the right of the pop-up a 16:00-00:00 shift and they just never show up to work. The game is also unpaused.

**Comment by bartusek27** [comment]
Hello **RMidway**,

I see your problem, but for better replication of your problem, could you send us your savefile?
How to find it:
1. Go to C:/Users/<your name>/Saved Games/Startup Company
2. There, you should see your savefile in .json format
3. Rename filetype to .txt (GitHub won't allow us to upload .json)
4. Attach it to your reply

Thanks for your report, can't wait to hear from you back!
Take care,
bartusek27

**Comment by RMidway** [comment]
[sg_91aa61ec-e - Copy.txt](https://github.com/hovgaardgames/startupcompany/files/1220043/sg_91aa61ec-e.-.Copy.txt)

Here's the savegame

**Comment by bartusek27** [comment]
Hi **RMidway**,

I am notifying you, that I just replicated your problem and it will be fixed as soon as possible!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Fixed
