### ISSUE TITLE
Suggestion - Shared Desks - Tier15

### ISSUE THREAD

**Issue by legaultp1** [hovgaardgames/startupcompany#491]
Here is what I have in mind. 

I already commented on the HR side however, this is to complement this discussion
At Tier15, we could have a new item (central server) that sits in the office somewhere. this server would allow a new type of workstation (Thin Clients) to work. this way, a Dev can work from any thin clients that are listed as the specific type of technology. ex: Dev, Lead Dev and so on.

this could also be used for the new multi scheduling system (HR).
this way, a staff could use the workstation in the morning. a different user would work on it in the day and the 3rd shift would be during the night. 1 workstation, 3 staff. 

since they are all identical (per say) they could be randomly assigned.

anyway. this is just a suggestion and might be hard to implement or maybe easier since you don't have to retrofit the current workstations

good luck and great game so far

**Comment by bartusek27** [comment]
Hi **legaultp1**,

thank you for your suggestion, I like it!
Althrough, we need to discuss the implementation of this feature, rest assured, it will be taken in consideration.

Once again, thank you and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Moved to Conflux
