### ISSUE TITLE
Hard to Click on the shaking action needed icons.

### ISSUE THREAD

**Issue by markrichey** [hovgaardgames/startupcompany#492]
Hello,
Firstly great game and congrats on the steam launch, the shaking icons that you get when some sort of action is needed tends to result in the desk being picked up on my Mac, have never seen you suffer the same on the steam so not sure why its doing it.

Keep up the great work!

Mark

**Comment by bartusek27** [comment]
Hi spencerisadog,

first off, thank you so much for your report!
I am notifying you, that I just replicated your problem and it will be fixed as soon as possible! It happens to me also constantly.

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Fixed
