### ISSUE TITLE
Beta 12.3: Commas in competitor names cause issues with localization

### ISSUE THREAD

**Issue by Cliff122** [hovgaardgames/startupcompany#493]
This issue is only really relevant when using mods, since it doesn't cause any issues in the vanilla game.

When a competitors name has a comma in it, such as in "Reddit, Inc." angular seems to interpret the comma as a separator when localizing the string which causes an error.

Here's what it looks like in the competitor details view and the error it's causing:
![comma_in_competitor_name_error_1](https://user-images.githubusercontent.com/4162261/29244100-38426886-7fb0-11e7-9563-1ff4801f45d0.png)

The solution seems to be quite simple though, you just have to remove the braces in the `localize-data-name` attribute on line 9 in the `/competitors/details.html` template.

**Comment by bartusek27** [comment]
Hi **Cliff122**,

first off, thank you so much for your report!
I am notifying you, that I just replicated your problem and it will be fixed as soon as possible! It happens to me also constantly. I noticed it too when I was making mods. To fix it, it is not cause only by commas, but by spaces too.

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Seems to work now. Yay!
