### ISSUE TITLE
Beta 12.3: memory usage stacked

### ISSUE THREAD

**Issue by elmakong** [hovgaardgames/startupcompany#494]
After a while playing the game, the memory usage keep rising up. probably memory leak or not cleaned properly. or maybe my laptop is just too weak..haha.
when started the game and playing for about 15 mins, ram usage around 250mb, after a while, taken up around 700mb

**Comment by bartusek27** [comment]
Hi **elmakong**,

first off, thank you so much for your report!
I am notifying you, that I couldn't replicate your issue. I have for 5 hours in a row opened SC and it still uses 350 MB of RAM. But it can be hardware-related.
But rest assured, that we will check this very closely!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by elmakong** [comment]
Maybe this helps
![image](https://user-images.githubusercontent.com/8539103/29251226-783f7fd4-807b-11e7-9af9-f83b39507561.png)
i only run one instance of the game.
CPU: Intel i7-6500U(yeah, the weak one)

**Comment by bartusek27** [comment]
Hi again,

yea, interesting indeed.
@jhovgaard What do you think of it?

Take care,
bartusek27

**Comment by johannwagner** [comment]
![bildschirmfoto 2017-08-14 um 02 10 38](https://user-images.githubusercontent.com/12380026/29254457-ee562e42-8095-11e7-9ecc-b225d29db2d2.png)

It may come from Reloading the game over and over again using F5.

**Comment by jhovgaard** [comment]
Probably watchers building up. Will look into this.

**Comment by elmakong** [comment]
@johannwagner well, i did alt+tab so much to another applications..i just know that i can refresh the game by using F5

**Comment by jhovgaard** [comment]
Fixed!
