### ISSUE TITLE
Suggestion bugs that set back the progress meters for creating components

### ISSUE THREAD

**Issue by therealdominick** [hovgaardgames/startupcompany#495]
so that the more skillful they are the less of the setback time

**Comment by bartusek27** [comment]
Hi **therealdominick**,

thank you for your suggestion! However, I am not so sure, what do you mean. Can you describe your suggestion more?

Once again, thank you and have fun playing Startup Company!
Take care,
bartusek27

**Comment by therealdominick** [comment]
just so then when your in the part of the game where experts are needed it creates bugs for beginner types

**Comment by jhovgaard** [comment]
Moved to Conflux.
