### ISSUE TITLE
Game-Over Event Locks Up Game

### ISSUE THREAD

**Issue by QuantumHusky** [hovgaardgames/startupcompany#496]
After getting a warning message about only having $10,000 in credit from the bank until the game would be over, I proceeded to let my company fall under that mark. Upon hitting -$11,000+ the game auto-paused, no message popped up, and all buttons became unable to be clicked. Not only the toolbar buttons at the bottom but also the main menu button as well. There was no way to navigate anywhere without restarting.

Sorry, just writing a wiki for the game and wanted to know what actually happened if you went broke! 💃

**Comment by QuantumHusky** [comment]
Further note: after restarting the game, the alert telling me that I am unable to continue and to return to the main menu does show up, but it seems this fails to appear when conditions are first met in-game.

**Comment by bartusek27** [comment]
Hi **QuantumHusky**,

first off, thank you so much for your report!
It might be a minor graphical bug, but for making sure, it won't happen again, we'll look on it.

I am also very happy that you are doing a wiki for SC! Contact me @ Discord for any help/info about the game you need!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Fixed.
