### ISSUE TITLE
Small Employee Tier Unlock Text Bug

### ISSUE THREAD

**Issue by QuantumHusky** [hovgaardgames/startupcompany#497]
This is a fairly minor issue, but when choosing "Employee Type" under the Recruitment popover window, if a player still has Employee Types that are locked, the "Unlocked at Tier ____" text will take the form of the first selected option only, even after changing the selection.

For example: if I am tier 2 and select Manager, the description text will show "Unlocked at Tier 3" in orange (this is the correct value). However, if I change to any of the other options that are locked, the "Unlocked at Tier 3" text does not change, even if the employee type is unlocked at a higher level. Selecting an employee type that is unlocked and then going back to one that is locked will reset this orange text to the correct value, but it will be stuck on that tier level once more when switching between other locked values.

Fortunately, this does not seem to affect actual unlocking, just the labeling here.

Keep up the hard work everyone! :)

**Comment by Cazsius** [comment]
@bartusek27 when you have time can you check replcation... then if replicatable please add s:approved label, too far in current save.

**Comment by QuantumHusky** [comment]
Here's some images to back up these claims 😄 

[Screenie 1](https://ibb.co/mYChhF)
[Screenie 2](https://ibb.co/iZ6KUv)

**Comment by bartusek27** [comment]
Hi **QuantumHusky**,

first off, thank you so much for your report!
I am notifying you, that I just replicated your problem and it will be fixed as soon as possible!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Fixed!
