### ISSUE TITLE
Ability to somehow fine Tune Stock Market Amounts

### ISSUE THREAD

**Issue by Cazsius** [hovgaardgames/startupcompany#499]
Whenever I use the Stock Market, maybe it's due to my OCD, I like to have an even amount of stock in a company. As an example, I like having 500 stock, not 496. 
Also some people have an exact amount they'd like to spend, for another example, they want to spend 4,250$ not 4,267$. 

With the current system this is very hard to do, as the slider is a little shaky and doesn't change in a very fine tuned matter.

What I am suggesting is adding some way to fine tune the amount buying and, or the amount you are spending when buying stock so you can get a closer number.

Edit: I do know the arrow keys exist to go up and down. I am asking for something more along the lines of being able to click the number above the slider or the price, and type in what you want to spend.

**Comment by jhovgaard** [comment]
Moved to Conflux
