### ISSUE TITLE
Add Mod/Plugin Support

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/startupcompany#50]
Some kind of system to add and replace default entities like  with 'resourcepack.json'
- [ ] Replaceable clients
- [ ] Replaceable Technologies(developer skills / skills in general)
- [ ] Potential employee names besides the random generated ones ("Jeve Stobs", "Gill Bates")
- [ ] Components, etc.

**Comment by jhovgaard** [comment]
This task could be part of a mod-support feature.

**Comment by jhovgaard** [comment]
Closing this as modding is now being defined on-the-fly on Discord (#modding).
