### ISSUE TITLE
Suggestions For "Start Up", From A Business Side Of View

### ISSUE THREAD

**Issue by Orion3003** [hovgaardgames/startupcompany#500]
**Hey to everyone the "startup company" community!**

I'm very exited about business games like these so it's something im going to enjoy crontibuting too when I have the time. **Now a fair warning, this is from a business executive point of view and not a game dev point of view so im not saying that these must all be implemented or that they even should be in the future.** I have over 7 years of entrepreneural and business experience running 4 different companies (Most are marketing orientated so I will go into that part a lot, everything to do with advertising ect I will lay it out) so I'll try to go in depth as much as I can.

**FINANCES**

We all know how important finances are to any business. Expanding the budget section is very important. Now keeping this game casual, im not going to go into MBA level of finance frameworks, however expanding the budget section would definatly be better, even things as simple as a income statement (I will cover this bellow) would be good but again, its just a sugestion!

- **LOANS:** The current model is so far good in terms of a placeholder, however I recomend raising the loans to 500k all the way to 1mil. Software companies tend to get quite expensive, so having the option

- **INVESTORS:** Including ways of raising capital aside from loans is also a very important Idea. Having the ability to attract both Venture Capitalists and Angel Investors are very important to startups all around the world today. This can also be implemented product wise, if you need to raise capital to produce something.

- **BUDGET:** As mentioned above, a little more expanded budget section would be a good thing to think about. Usually these can be displayed as Y-T-D which means year to date and last year. A simple income statement can include the following: **Operating Revenue:**Cost of sales, Salaries expenses, operating overhead, general marketing spend such as advertising and pr, training, any R&D, other misc stuff. Then we can have all **Operating Expenses** for both YTD, and lifetime. Also having **Operating/Net Profit** would be good to include aswell. This is where you can include all the investing revenue.

**Marketing**

Now, my area of expertise. Someone once at a conference told me, "your not in business for your product or service, your in business of **marketing** your product or service" which is completely right. the right marketing really effects how your company grows, and how rapidly too! Now as much as I would like to go in depth, ill try to cover just important parts what I think need to be in the game and not bore you to death.

- **ADVERTISING:** Contrary to popular belief, advertising isn't simply throwing money and see if it works, its a very analytical and numbers based game. It's a simple "put $1 and get $3 back" type of idea. In our digital age, advertising is far more cheaper and effective than it used to be, we have the internet to thank for that. The first challange is getting good creatives (Ads) done. You could implement an option of getting it done elsewhere (a possibility to outsource it) OR you could have a team of designers to do it inhouse. Lastly, you could just keep it to the marketers themselves and not really exapnd on it much. The next objective is choosing where and how to buy your ads... There are many places to buy ads on. Are we going to use Media Buying aka Display (traditional banner type of advertising etc), Native advertising (ads that blend in with the content), Email Marketing, Video Advertising, Social media Advertising... you get the idea, there could be lots of choices. Next would be to choose how we spend our ad budget. Are we going to spend it on a CPM basis (cost per 1000 impressions, for example a $7 cpm could mean you spend $7 every time your ad gets displayed 1000 times) or on a CPC basis (you get charged an ammount every time someone clicks). And then finally you could also include A/B testing. Marketers and people who work in the ad industry track porgress of their campaigns and usually test multiple variables to optimise ads so they work and become profitable. There could definatly be an option where you can split test your campaigns which would make it more interesting. To make this more easier I will include a chart I made of the various formulas you could potentially include..

![acrord32_2017-08-13_04-39-08](https://user-images.githubusercontent.com/30967395/29245921-75632206-7fe1-11e7-8648-9a80f35ea1b2.png)

- **MARKET RESEARCH:** Something else that can be included, before developing any product its important to have good market reasearch in place. This could be in a form of spying on your competitors, surveying people in the market and looking at various trends, OR paying a company to perform market research for you and cut all the time and effor you spend doing it yourself.

THIS IS THE IMPORTANT STUFF FOR NOW, I WILL TRY TO CONTINUASLY UPDATE THIS

**Comment by bartusek27** [comment]
Hi **Orion3003**,

thank you for your suggestion! Everyone here appreciate, how much work and effort in writting and explaining you gave to this suggestion. From my point of view, I think it is really complicated for users (Finances), but I loved the marketing stuff so much!

I think it would be better to implement finance stuff into mod like "Realistic Finances" or something 😆 
But I would definitely do at least some of the marketing stuff.

But I should stop talking now and let the community talk! If you have any idea or just want to give a support to this suggestion, feel free to!

Once again, thank you and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Once again thank you for the suggestion. I have noted it :-)
