### ISSUE TITLE
developer not appearing under manager list

### ISSUE THREAD

**Issue by greenalarmclock** [hovgaardgames/startupcompany#501]
im at tier 20, new lead developer i hired doesnt appear in the managers list to be managed. i recently upgraded the manager from beginner to expert.how ever the managment capabilty is still stuck at 3 developers max
![image](https://user-images.githubusercontent.com/30970053/29246370-6370eb70-802a-11e7-9600-7f13975e2f67.png)

**Comment by johannwagner** [comment]
Hey **greenalarmclck**, 

thank you for your bug report. Could you provide us your save game to reproduce the error? 

Savegames are located at `Saved Games/Startup Company`. You can change the file ending to txt to be able to upload it to Github. 

Thanks a lot!
Regards, 
  Johann

**Comment by greenalarmclock** [comment]
[sg_8b960a2b-b.txt](https://github.com/hovgaardgames/startupcompany/files/1220385/sg_8b960a2b-b.txt)
[sg_39983d56-3.txt](https://github.com/hovgaardgames/startupcompany/files/1220387/sg_39983d56-3.txt)
[sg_c241a896-9.txt](https://github.com/hovgaardgames/startupcompany/files/1220386/sg_c241a896-9.txt)
[sg_c9557a0d-3.txt](https://github.com/hovgaardgames/startupcompany/files/1220388/sg_c9557a0d-3.txt)

**Comment by jhovgaard** [comment]
Fixed
