### ISSUE TITLE
Upgrading the products

### ISSUE THREAD

**Issue by Kentor1P** [hovgaardgames/startupcompany#502]
Hi, 
I don't think that it's meant to be so but to upgrade a product I only have to go to My product-->New Version-->Next-->Confirm Selection-->Release and that's it without any changes or without paying.
I hope that it wasn't intentionnal and that you're going to change it.
PS: I LOVE your game! Continue to upgrade it please!!!

Kentor1P

**Comment by bartusek27** [comment]
Hi Kentor1P,

first off, thank you so much for your report!
I am notifiying you that I just replicated your issue, but I am not sure, if I should call it a bug or intention.
Thanks for loving SC as much as we do!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by bartusek27** [comment]
@jhovgaard Can I get an expertise?

**Comment by jhovgaard** [comment]
FIxed :-)
