### ISSUE TITLE
Incorrect cost of upgrades

### ISSUE THREAD

**Issue by MasterofOrion** [hovgaardgames/startupcompany#504]
When doing upgrades for my own products, the displayed cost for each further upgrade increases. But when I do that upgrade, my inventory is not reduced by the displayed amount, but by the inital cost of the first upgrade. Works with all upgrades.
Example: Doing the 5th upgrade of Landing Page shows cost of 10 Frontend Modules and 5 Input Modules. I can only click the upgrade button, if I have 10 Frontend Modules and 5 Input Modules. Clicking will reduce my inventory by 2 Frontend Modules and 1 Input Module.

**Comment by bartusek27** [comment]
Hi **MasterofOrion**,

first off, thank you so much for your report!
I am notifying you, that I just replicated your problem and it will be fixed as soon as possible! To be honest, I didn't even noticed it, so 👍 for ya!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by MasterofOrion** [comment]
Don't rush it. :)
Fixing this will seriously effect the balance of the game, as upgrades will be much harder to obtain.

**Comment by jhovgaard** [comment]
Fixed
