### ISSUE TITLE
Missing translations in beta 12.3

### ISSUE THREAD

**Issue by EnlerStudio** [hovgaardgames/startupcompany#506]
Hello,
I have seen some missing translations in the beta 12.3 : 
- Missing "inbox" and "list"
![startupcompany_2017-08-13_13-27-57](https://user-images.githubusercontent.com/26345717/29249243-29c0e018-802c-11e7-904e-f72aafd41b44.png)
- Missing the translation for buy a market share :
![startupcompany_2017-08-13_13-32-02](https://user-images.githubusercontent.com/26345717/29249244-29c38908-802c-11e7-87f3-eb60f056e96c.png)
- Missing the translation for sell a market share :
![startupcompany_2017-08-13_13-32-24](https://user-images.githubusercontent.com/26345717/29249245-29c87954-802c-11e7-93fa-deb694d922af.png)

I have found no more missing translations, but I will continue to check ;)
UE4 DryTuto.

**Comment by bartusek27** [comment]
Hi **EnlerStudio**,

First off, thank you so much for your report!
I can confirm that those strings are missing and will be added in next updated!

Once again, thank you for your report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by EnlerStudio** [comment]
I have see an another missing translation (in the competitors window, the title) : 
![startupcompany_2017-08-13_20-16-55](https://user-images.githubusercontent.com/26345717/29252297-7b11102c-8064-11e7-89b9-3db39e02a7ac.png)

**Comment by jhovgaard** [comment]
Fixed, thanks for reporting!
