### ISSUE TITLE
Exit button not work

### ISSUE THREAD

**Issue by premaliang** [hovgaardgames/startupcompany#507]
Beta 12.3. Mac.
In main menu. When mouse move to bottom half of the exit button, the button is dimmed and malfunction.

**Comment by jhovgaard** [comment]
Hi there!

What resolution are you running the game in?

**Comment by premaliang** [comment]
Windowed mode.
I just test it., if I narrow down the height of the game window. This issue happens. 
Stretch the game window higher enough, this issue is vanished.

**Comment by jhovgaard** [comment]
Fixed. Will be included in next update.
