### ISSUE TITLE
Potential bug with feature upgrades

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#510]
http://steamcommunity.com/app/606800/discussions/0/1471967615879418402/

Some of the project upgrades do not seem to remove the correct number of components from your inventory. Example: the icon was listed as 40(40) and after the upgrade it would change to 41(39). This allowed me to create 2 of the item and upgrade almost instantly. Not sure if this was for components or modules. 

The researches list a price for the frameworks but as far as I can tell this value was not taken from me. I expected it to be the price you pay when creating an instance of the project not part of the research cost, but every project has been free. I know I didn't have 240k when I did the 2016 framework as my second research or second project.

**Comment by QuantumHusky** [comment]
Can confirm that I have been subject to this same bug at times. Seems to only happen with project upgrades.

**Comment by bartusek27** [comment]
#504 is the same
