### ISSUE TITLE
Employee leaving - HR issue

### ISSUE THREAD

**Issue by PunkoHead** [hovgaardgames/startupcompany#512]
When an employee leaves on their own, the HR still takes charge of it, but you are not able to turn it off.
![image](https://user-images.githubusercontent.com/7597032/29250338-87f7346c-8049-11e7-8fb6-5399bbe4b259.png)

In order to resolve it, you have to unassign the HR from his desk and assign him again.

**Comment by jhovgaard** [comment]
Nice catch, was wondering how this happened (got other reports).

Thanks!

**Comment by jhovgaard** [comment]
Fixed
