### ISSUE TITLE
30 Day Contract Decline Cooldown Broken

### ISSUE THREAD

**Issue by QuantumHusky** [hovgaardgames/startupcompany#513]
It seems that the 30 day wait period before receiving another contract offer from a company after declining their last contract is not working. I noticed this on my main game after I declined a contract and then another sales executive received a contract from that company the next day (in game). As a test, I set up a new game with multiple sales executives and was able to constantly search for new contracts, decline all of them, and still have a steady flow of new contracts coming in from companies that I had already declined within the past 30 days.

**Comment by bartusek27** [comment]
Hi **QuantumHusky**,

first off, thank you so much for your report!
I am notifying you, that I just replicated your problem and it will be fixed as soon as possible! I noticed this too, it may not just been implemented yet.

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27
