### ISSUE TITLE
Suggestion: Beta 12.3 Competitor stock

### ISSUE THREAD

**Issue by elmakong** [hovgaardgames/startupcompany#514]
Hey, it would be great if Up/Down Arrow can make the change increments for 10 or more(future maybe?) and the Left/Right Arrow increases or decreases by 1(as now is).
as it is a bit hard to increase/decrease the stock to buy/sell.
possibly adding a textbox to custom input value?

**Comment by bartusek27** [comment]
Hi **elmakong**,

thank you for your suggestion! Even I like your idea, let's ask the community if they like it too!
Guys, if you have any idea or just want to give a support to this suggestion, feel free to!

Once again, thank you and have fun playing Startup Company!
Take care,
bartusek27

**Comment by thomaslos** [comment]
what could also help is change the scaling of the sliders, the scaling is really steep in the end which doesnt always help with selecting a value

**Comment by thewillwilson** [comment]
Where it says the number of it, if you can click it then type whatever you want, it would be better.

**Comment by elmakong** [comment]
please also consider some people want to buy by value or by stock count.

**Comment by jhovgaard** [comment]
Moved to Conflux.
