### ISSUE TITLE
Exceeding the desk limit by using another savegame

### ISSUE THREAD

**Issue by Devinpennings** [hovgaardgames/startupcompany#517]
At the moment it is possible to exceed the desk limit by using another save game that hasn't reached the limit yet. You can do this by opening or creating a new savegame that hasn't reached the desk limit yet, buy a new desk, but don't place it yet. Now with the desk location selection still opened, open the menu and load the savegame with that reached the desk limit. You can now place the new desk in your office and that way you exceeded the desk limit.

**Comment by jhovgaard** [comment]
Fixed. Insane bug-catching! :-)
