### ISSUE TITLE
Lights For Nighttime; Speeeeedy Game!

### ISSUE THREAD

**Issue by MazeBank** [hovgaardgames/startupcompany#523]
Hello, I do have the suggestion to have Lights.
even tho u should not be working at night time.
i do like to have lights in the game as in when i do have employees working in the night and i barely can see anything.

let's see what the community thinks about it? 

Thank you for reading this suggestion! MazeBank
-------------------------------------------------------------------------------------------------------------------
ADDED:

Hello, I do have the suggestion to have more diffirent speeds.
Now we only can have fast speed and super fast speed.
i do like to see a little less speed fast and super fast.

Let's see what the community thinks about it?

Thank you for reading this suggestion! MazeBank

**Comment by bartusek27** [comment]
Hi **MazeBank**,

thank you for your suggestion! Even I like your idea, let's ask the community if they like it too!
Guys, if you have any idea or just want to give a support to this suggestion, feel free to!

Once again, thank you and have fun playing Startup Company!
Take care,
bartusek27

**Comment by AnnaisFay** [comment]
I like the lights thing. It could either be fixed by adding default lambs to the working tables, or putting up lambs around the office.

I could agree with more options when it comes to speed. :)

**Comment by jhovgaard** [comment]
Promoted to Conflux: https://startupcompany.cnflx.io/public/ideas/948
