### ISSUE TITLE
Vacation

### ISSUE THREAD

**Issue by Mikeace1** [hovgaardgames/startupcompany#525]
Hello,

It would be nice if there was an option to send all of your employees on vacation at the same time.  Having to select each of them is time consuming and annoying.  Also, the loss of motivation requires vacations every 15 days.  It would be nice to have weekends and holidays programmed in that would provide some motivation back, similar to the real world.  Also, while being able to add additional items to improve effectiveness as work is nice, some items to improve motivation loss would be easier.

**Comment by MazeBank** [comment]
Already i agree buddy

**Comment by The4Syndicate** [comment]
Agreed

**Comment by AnnaisFay** [comment]
+1 agree. :) Will surely be put on the roadmap ;)

**Comment by KayJeeCodes** [comment]
I was about to suggest the same but noticed this has already been addressed. Just as the HR Manager can sort out schedules, I think it could be easy enough to sort out programmed holidays. A slider that allows changes like "Every 10 days" or "Every 12 days", something along those lines. It would allow scheduling such that I can make sure to always have at least 1 worker at the office, while the others rest - that sort of thing.

**Comment by MazeBank** [comment]
Hello @KayJeeCodes 
In my opinion, this would make the game too easy.
there is a mod called wolf pack that makes this easier for you already.
I suggest you look that mod!
http://steamcommunity.com/sharedfiles/filedetails/?id=1109853374

<Jason/t>

**Comment by KayJeeCodes** [comment]
@MazeBank > Fair enough, I understand why I suppose. That mod does look interesting I'll be taking a look at that, much appreciated! :)

**Comment by MazeBank** [comment]
Hey again!
Not a problem I am here always!

If you have any further questions feel free to ask I am here!
<Jason/t>

**Comment by jhovgaard** [comment]
Promoted to Conflux: http://status.startupcompanygame.com
