### ISSUE TITLE
Suggestion: Getting rid of old workstations/furniture.

### ISSUE THREAD

**Issue by openworldaddict** [hovgaardgames/startupcompany#527]
It would defintely help if you were able to get rid of old items that you no longer want. the biggest issue is with the workstations. Whenever a new workstation becomes available, i want to replace the old ones with the newer and more efficient workstations, so not being able to get rid of the older ones is a big pain, and I believe being able to do this would be so beneficial, since you only have space for so many workstations based on the office you have. This also goes for furniture items you need to get rid of because you need the space for other workstations.

**Comment by MazeBank** [comment]
You can just right click the old work station and press delete on your key board to get rid of it

**Comment by Cazsius** [comment]
This is already added into the game as @MazeBank you can delete the items. Closing the issue.
