### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by The4Syndicate** [hovgaardgames/startupcompany#528]
Automatic Vacation.

Add the ability for HR to send an employee to vacation when certain mood constraint is reached.

Clicking through individual employee's is very annoying.

**Comment by AnnaisFay** [comment]
There's a mod that currently does this when your employees mood fall below 40%. I could see this feature implemented in the future, but as of right now with a maximum of 50 employees, you should be able to manage their vacations :)

**Comment by MazeBank** [comment]
Hi there!
There is also a mod called: "Wolf Management"
This will allow you to send all your employees to a vacation at once easy as well right?

link: "http://steamcommunity.com/sharedfiles/filedetails/?id=1109853374"

Kind regards Jason AKA MazeBank

**Comment by thomaslos** [comment]
there can be only one vacationator @MazeBank ;) (kiss from xlos)

**Comment by thomaslos** [comment]
but agree with op!

**Comment by jhovgaard** [comment]
Promoted to Conflux: http://status.startupcompanygame.com
