### ISSUE TITLE
Suggestion: Colorblind mode

### ISSUE THREAD

**Issue by PazoxZodiac** [hovgaardgames/startupcompany#529]
Someone on Discord had trouble with the financial screen, because both halfs of the screen are not labeled, only the color of both halfs marks them as expenditure (red) and income (green).

There should be a simple colorblind mode in options and a title with "expenditure" and "income" over both halfs would be great too.

**Comment by MazeBank** [comment]
Hello PazoxZodiac,
I see this issue and this is gonna be solved as said in discord if I am not wrong ;)
In fact, this is not a suggestion but an issue so this title may not fit here.

Kind regards Jason AKA MazeBank

**Comment by Cazsius** [comment]
@MazeBank currently, this is not an issue, but suggestion, as it is titled, so I'm going to mark it that way, until @jhovgaard confirms this will be added to the game!

Best Regards!

**Comment by MazeBank** [comment]
@Cazsius Yes i agree but it is a little bit of both ;)

Jason </>

**Comment by jhovgaard** [comment]
Promoted to Conflux.
