### ISSUE TITLE
Suggestion: Preferred working hours for employee recruitment

### ISSUE THREAD

**Issue by PazoxZodiac** [hovgaardgames/startupcompany#530]
It would be nice, if you would be able to set the preferred working hours for the employees, when you set up the recruitment.

You can already set the preferred level and the time to search, additionally there should be a slider for the working hours (similar to the one under employee schedule), so the new employees would start with the set up time.

The costs for the search should be slightly higher, when you search with preferred working hours.

**Comment by Freakspot** [comment]
+1

**Comment by MazeBank** [comment]
I also would like to see this in Startup Company man.
good suggestion!

+1

**Comment by cpeosphoros** [comment]
"Necroing" this.

A nice feature would be the possibility to set different hours for different employees, with employees whose schedules doesn't overlap being able to share a desk - that would enable the possibility to implement work shifts.
