### ISSUE TITLE
Can't move the desks ?

### ISSUE THREAD

**Issue by Pyrostone** [hovgaardgames/startupcompany#534]
When I first launched the game, I put my desks about everywhere in my office. but now I want to rearange them, to make it cleaner...  but  I can't pick them. With or without employee on it, if there is one, it is as if I clicked on the employee, and if there isn't, it is as if I wanted to put an employee on it... so I can't select my desks for moving them.

**Comment by AnnaisFay** [comment]
Glad you found the solution. Have a great day! :)
