### ISSUE TITLE
Company Level Changed after Update

### ISSUE THREAD

**Issue by isparia** [hovgaardgames/startupcompany#535]
After updating from 12.3 to 12.4 my company level raised from 13 to 17

**Comment by AnnaisFay** [comment]
Hi isparia,

Could you explain a bit more about the situation? Did you just update and it happened or what? :)

Regards
Anna

**Comment by MazeBank** [comment]
> Hi isparia,
Could you explain a bit more about the situation? Did you just update and it happened or what? :)
> 
> Regards
> Anna

Haha you where toooo fast for me 📦

**Comment by isparia** [comment]
hey @AnnaisFay, 
sure i can, after the update i restarted the game and then i did 1 contract and my company level jumped from 13 to 17. 

For the Contract it was a Medium Urgency Contract with 34 Modules.

In Addition i think its a problem with the experience gain, I did now 3 more Contracts, and got the next level up, 1x High(54 Modules) , 1x Medium (30 Modules) and 1x Low (43 Modules).

I did a also a test now and the gained XP, which stands in the contract completed popup is 4476, but i gained 45% for the next level. Before the Update i gained around 2% for low, 5% medium and 10% high i think

**Comment by MazeBank** [comment]
# **ANNA IS GOD ;)**

**Comment by AnnaisFay** [comment]
Hm, weird. @jhovgaard any idea?

**Comment by isparia** [comment]
this seems to work only with old save games, in a new one the gain seems normal

**Comment by AnnaisFay** [comment]
Yes, exactly. It looks like an issue with the new update. If you are up for it, you may start a new save. If not, I highly doubt a fix is possible.

**Comment by MazeBank** [comment]
Hi there I am just gonna mix in here :P
I think it is just a bug/ glitch that happened on your save game nothing to do about it.
You could as @AnnaisFay said start a new Game.

Kind regards Jason

**Comment by isparia** [comment]
ohh i personal dont care but, sometimes its a glitch which can end up game breaking when its not addressed properly. 

@AnnaisFay @MazeBank
Closed from my side if you dont want to investigate it ^^
