### ISSUE TITLE
Beta 12.4: Marketing progress bar hours left not working

### ISSUE THREAD

**Issue by PazoxZodiac** [hovgaardgames/startupcompany#536]
In marketing for your products, you have green progress bars, which show the progress of the advertisement and they should show the hours left, but it is always showing the maximum hours.

![unbenannt](https://user-images.githubusercontent.com/30998912/29288343-afdd5160-8138-11e7-8507-b19e2a8dc1e8.PNG)

**Comment by MazeBank** [comment]
Hello @PazoxZodiac
Myself I do not have this issue.
This may be because you have some mods, or made a mod yourself.
go turn off all your mods and try again.

Jason </>

**Comment by Cazsius** [comment]
If someone replicates this bug and can give instructions on how to, i'll add the s:approved tag... 

Until then I will not add it, as I'm not sure if it's replicatable.

Best Regards!

**Comment by PazoxZodiac** [comment]
I started a new savegame without any mods and the bug is still present.
![image](https://user-images.githubusercontent.com/30998912/29344749-5767fc44-823a-11e7-8b5f-e98e84c1c478.png)

**Comment by jhovgaard** [comment]
Fixed!
