### ISSUE TITLE
Holidays timer not working

### ISSUE THREAD

**Issue by aanovitskiy** [hovgaardgames/startupcompany#537]
Hi guys, when someone leaves on holiday and I unassigns this person from the desk the timer is stuck and not ticking. So while people are away they have to be assigned and waste desk space! Not good. Also I suggest adding time of vacation to the main employee page, because it is pain to track who is coming back when. Cheers! Thank you for the game.

**Comment by MazeBank** [comment]
Hello @aanovitskiy 
Thank you for your suggestion and feedback!
As I now notified staff to look into this issue they will respond as soon as possible.

If you have any more questions I am here!

Jason </>

**Comment by jhovgaard** [comment]
Fixed!
