### ISSUE TITLE
Tentative Issue: Is it right for my contracts manager to find a contract I don't have the staff to complete?

### ISSUE THREAD

**Issue by markrichey** [hovgaardgames/startupcompany#538]
This is a tentative one and it actually turned my nicely organised game into chaos (so quite fun), I had an office with just Devs but my contract manager pulled a contract that needed a designer (I assume due to my level).

![screen shot 2017-08-14 at 22 08 50](https://user-images.githubusercontent.com/12082867/29292055-9c03dfe2-813d-11e7-8d3a-e176f0d54944.png)

Many Thanks
Mark

**Comment by MazeBank** [comment]
Hello @markrichey 
This is because of your level most likely.
It also may be because the amount of play time you have got on that profile.

Feel free to ask me anything!
Jason</>

**Comment by BitCaps** [comment]
You can just decline contracts that require items you can't produce.  I noticed this in my game and declined them until I hired a designer.

**Comment by jhovgaard** [comment]
Yes, the game tries to force the player into developing the staff.
