### ISSUE TITLE
display bug wall corner

### ISSUE THREAD

**Issue by Goldberggdn** [hovgaardgames/startupcompany#540]
There is a display bug the wall corner, as seen on screenshot it seems that both rotations 2 and 3 are shifted and not flush with the wall. Rotation 1 is OK (and rotation not on screenshot is fine too). Glass wall corner is OK in all rotations.

![display bug](https://user-images.githubusercontent.com/31019507/29293708-4ef4016e-814c-11e7-883b-24eb65018188.jpg)

**Comment by bartusek27** [comment]
Hi **Goldberggdn**,

first off, thank you so much for your report!
I am notifying you, that I just replicated your problem and it will be fixed as soon as possible! This bug can be pretty annoying, I hope that Jonas will fix it as soon as possible!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Fixed
