### ISSUE TITLE
Backend doesnt increment

### ISSUE THREAD

**Issue by rushadantia** [hovgaardgames/startupcompany#541]
The backend component does not update the value when i have an auto repeat feature on him. I have a manager for each player each creating a basic component on repeat. All work except the backend component

**Comment by bartusek27** [comment]
Hi **rushadantia**,

I see your problem, but for better replication of your problem, could you send us your savefile?
How to find it:

1.     Go to C:/Users/your username/Saved Games/Startup Company
2.     There, you should see your savefile in .json format
3.     Rename filetype to .txt (GitHub won't allow us to upload .json)
4.     Attach it to your reply

Thanks for your report, can't wait to hear from you back!
Take care,
bartusek27

**Comment by rushadantia** [comment]
[sg_ebce9bb3-e -.txt](https://github.com/hovgaardgames/startupcompany/files/1226033/sg_ebce9bb3-e.-.txt)
Here is the savefile. I went into the console and added money to the bank.

**Comment by jhovgaard** [comment]
Fixed, thanks for reporting.
