### ISSUE TITLE
Urgency not translated

### ISSUE THREAD

**Issue by premaliang** [hovgaardgames/startupcompany#543]
Beta 12.4. MacOS.
I'm doing Traditional Chinese translation. In contract view, the {urgency} in "urgency_label" is not translated. It shows {urgency} on contract view.
The other translations work properly.
I checked the other built in translations, all work properly except Simplified Chinese.

![2017-08-15 17 37 30](https://user-images.githubusercontent.com/5953493/29310527-9af09868-81e0-11e7-91cd-4e2963795d69.png)

**Comment by premaliang** [comment]
![2017-08-15 20 36 24](https://user-images.githubusercontent.com/5953493/29316174-70b867c4-81f9-11e7-9611-cf5a7d23955c.png)

Error occurred in parsing first Chinese character.

**Comment by bartusek27** [comment]
Hi premaliang,

first off, thank you so much for your report!
I am notifying you, that I just replicated your problem and it will be fixed as soon as possible! I noticed this too when doing Czech Translation - but for me, it was an easy fix - not using řžýáíé and others of my "special characters". Sadly, you can't :(

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Fixed, thanks for reporting!
