### ISSUE TITLE
Everyone leaves their position so fast

### ISSUE THREAD

**Issue by js3263854** [hovgaardgames/startupcompany#545]
Everyone leaves their position so fast
It's like I'm spending all time hiring people, surely you could reduce it heaps?

**Comment by MazeBank** [comment]
Hello @js3263854 
Do you use an HR Manager or something else to change work times?
If not can you please explain a little more what you mean.
so I can try figure out some solution.


<Jason/>

**Comment by js3263854** [comment]
Yes, I was, I had several dozen employees & cheats.. just found myself in fast forward mode but it seemed every 2 minutes I'd have an email saying they quit. Seems a tad too often to me

**Comment by js3263854** [comment]
Is there a way I can stop them quitting all together with the dev console?
I swear there are 5-8 people quitting per day.

**Comment by MazeBank** [comment]
Hello again!
Did you change working hours of the employees?
What does the smiley after the employee say? 
Maybe I can figure it out then.
Can you also send me a screenshot of the mods installed?

When I had employees and put them on full work days like 20 hours they were also done every day.

<Jason/t>

**Comment by js3263854** [comment]
Never changed the work hours, they're all good, smiling away. No mods. Everything is default.

**Comment by MazeBank** [comment]
Do you have any mods?

**Comment by js3263854** [comment]
No, just all the default stuff game straight off of steam.

**Comment by MazeBank** [comment]
What you could try is start a new game and see what happens.

<Jason/t>

**Comment by js3263854** [comment]
Yeah i've tried several, same thing. It seems to happen when you have a large number of employees say 10+

**Comment by MazeBank** [comment]
Hmke.....
This does sound really wired to me.
I have never had this issue before.
I will notice the staff team about this issue. @jhovgaard @Cazsius 

Thank you for reporting this.
If you have any further questions I am here!

<Jason/t>

**Comment by js3263854** [comment]
One in game day 5 people quit, the next I get emails that another 3 left, next day its more.. *Sigh* I just spent a good hour hiring almost non stop

**Comment by Cazsius** [comment]
This is an issue on your end @js3263854. Employees quitting often has to do with mood or work hours being too long.

**Comment by jhovgaard** [comment]
Reduce speed of mood decreasing.
