### ISSUE TITLE
Profit Issue

### ISSUE THREAD

**Issue by bhuvitek** [hovgaardgames/startupcompany#546]
Even m making a profit of 4k my money goes down by tht amount 
please solve tht issue
the game seems super good but u gotta get away of these issues...
all the bst

**Comment by MazeBank** [comment]
Hello @bhuvitek 
Can you explain this issue a little more for me?
There is a chance we can resolve this.

<Jason/t>

**Comment by mdiken** [comment]
The same thing has happened to me. Even though there's a green arrow next to my money and i seem to be profiting my money is always going down by the amount of profit i make per day.

**Comment by jhovgaard** [comment]
Haven't been able to reproduce this. If you still experience this issue please attach a savegame (%USERPROFILE%\Saved Games\Startup Company)
