### ISSUE TITLE
Delay between 100% completion of task and actual completion

### ISSUE THREAD

**Issue by PunkoHead** [hovgaardgames/startupcompany#550]
Hi all,

I noticed that there is a small delay between the 100% of a task and the actual completion.

**Steps to reproduce the issue:**

1. Click on a free developer.
2. Click on a task (UI Component).
3. Wait for the task to be nearly completed.
4. Once the task reaches 100%, start playing with the keys 1 and 2 until you finally reach the point where the task is completed (no %s are displayed) but the item is still not ready.
5. If you click on another item at this exact time, the next task will start and the UI Component will not be available.

On the screenshot below, I have the Encryption Component ready (but still in progress).
Let me know if you need further clarification.

![image](https://user-images.githubusercontent.com/7597032/29329391-6f18a442-81fe-11e7-9f71-50a8e95d4cb8.png)

**Comment by bartusek27** [comment]
Hi **PunkoHead**,

first off, thank you so much for your report!
I am notifying you, that I just replicated your problem and it will be fixed as soon as possible! 

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Thanks for reporting. This will be fixed in 12.8
