### ISSUE TITLE
Can't set worker on a 24 hours working day

### ISSUE THREAD

**Issue by PunkoHead** [hovgaardgames/startupcompany#551]
I know it is a bit strange, to want your workers 24/7 in the office, however it is in the game :)

If you set them from 00:00 to 24:00, the time actually is from 00:00 to 00:00 (they are not working any minute).
![image](https://user-images.githubusercontent.com/7597032/29330777-fee33264-8202-11e7-9b1b-15b80ba4ed63.png)
After entering the worker again, the slider is changed to:
![image](https://user-images.githubusercontent.com/7597032/29330810-19a3d7a2-8203-11e7-85e7-71001f24eb58.png)

Cheers,
Venelin

**Comment by johannwagner** [comment]
Hey, 

your bug was reported from another user.
You can see more information, quick fixes, and ideas at #489.

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann
