### ISSUE TITLE
Marketing 

### ISSUE THREAD

**Issue by Percy84** [hovgaardgames/startupcompany#552]
Marketing system is not very helpfull to Keep a System up on market. rebalance would be awesome.
System or Marketing Manager to Keep system stabl on the market (never saw in reality that millions of useres quit in ONE DAY) even if you have just 5mil users 

other bugs:
Glasswall still not overlapping other objects. 
Finanzmenu could have better overview also the stocks of other companies are not included in the values. 
Stockechange would be nice to open the own share if you would  

it would be nice to sent ALL employees in vacation at ones button 
are there also weekends possible ?! where you can Keep them working or not...  

THANKS 
ITS A GREAT GAME SPENT ALREADY over 16hrs since release on it

**Comment by Percy84** [comment]
forgot 
the marketing timer how much hrs a promotion left is not ticking down

**Comment by jhovgaard** [comment]
Thank you for your feedback :-)

Marketing and overlapping walls has been fixed. I noted your other suggestions.

Best,
Jonas
