### ISSUE TITLE
backend component wont build

### ISSUE THREAD

**Issue by YOUNGCHIGGA** [hovgaardgames/startupcompany#553]
whenever I try to build a backend component it either builds but doesn't count as if one built or it displays ones built but then goes back to 0. I tried firing worker and replacing, ive tried a different workstation and ive tried different building but nothing seems to work and its ruined the game>

**Comment by johannwagner** [comment]
Hey, 

I read your bug report carefully and I wasn't able to reproduce the bug. 
Could you provide us your save game to investigate further into this problem? Additionally, we need more information about your game version and your build number, which is located at Startup Company -> Properties -> Local Data.

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann

**Comment by jhovgaard** [comment]
Closed until more info.
