### ISSUE TITLE
Manager Assigned to an Employee / Employee not showing Manager

### ISSUE THREAD

**Issue by markrichey** [hovgaardgames/startupcompany#554]
Good evening,

I have assigned an employee (called Mina Hernandez) to a manager, they show as being managed on the managers screen but not on the employee screen. They are finishing a task and going into Idling. Happy to provide save if that would help?

Will start a new game at this point as I don't want to try unticking the assign box and setting it again in case the save will show whats happened.

Many thanks for the hard work!

Mark

![screen shot 2017-08-15 at 22 11 22](https://user-images.githubusercontent.com/12082867/29336793-ed7ade1a-8206-11e7-9556-1d294a8dca14.png)
![screen shot 2017-08-15 at 22 11 31](https://user-images.githubusercontent.com/12082867/29336795-ef81d434-8206-11e7-96ee-cfd494dbeb29.png)

**Comment by markrichey** [comment]
Ignore this it's my mistake I did not see the auto repeat for lead dev's is hidden in a sub section and then mis read the HR manager!

Working fine!
![screen shot 2017-08-15 at 23 08 40](https://user-images.githubusercontent.com/12082867/29338797-e0895b8e-820e-11e7-8993-fc4c99df852e.png)


Apologies

**Comment by AnnaisFay** [comment]
Hi mark!

Glad you managed to fix the issue on your own. Be sure to close the issue if you feel that it has been fixed 100%.

If you require more help, be sure to submit a new ticket or update this one. :)

Regards
Anna
