### ISSUE TITLE
Manager bonus should disable when manager is not at work

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#555]

**Comment by markrichey** [comment]
Do you mean when there not at work as in inactive (not working hours) or when there on holiday?

**Comment by Percy84** [comment]
may not disabeld but reduced would be good ... like in real life :D

**Comment by jhovgaard** [comment]
The problem is that you can currently reduce managers working hours to 3 hours without any consequences.

**Comment by BitCaps** [comment]
I could argue that, depending on the manager, workers would be more productive when the manager is away.  As long as the player is paying the managers salary, why not get the full benefit.

**Comment by markrichey** [comment]
Maybe if a manager works less than the people there employing then scale the benefit down based on that % difference? So if I work 10 hours a day and my manager works 6 then I gain some sort of "resentment" and the bonus I gain from a manager is reduced by the difference (40%).

**Comment by jhovgaard** [comment]
Fixed
