### ISSUE TITLE
Visual Bug - Large Meeting table and glass wall

### ISSUE THREAD

**Issue by LJack2k** [hovgaardgames/startupcompany#556]
Picture speaks a thousand words. 
![image](https://user-images.githubusercontent.com/6696404/29339095-efca9d60-8218-11e7-99c7-12047f083acd.png)

**Comment by johannwagner** [comment]
Hey, 

your bug was reported from another user.
You can see more information, quick fixes, and ideas at #325.

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann
