### ISSUE TITLE
Unlimited hype with publishing new product versions

### ISSUE THREAD

**Issue by Joe0890** [hovgaardgames/startupcompany#557]
- Publish a new product (social media in my case)
- Go into the product overview, switch to New Version tab. Press Next
![image](https://user-images.githubusercontent.com/31052137/29341919-3bba4b00-8230-11e7-96bd-4589806b3b57.png)
- Confirm selection
![image](https://user-images.githubusercontent.com/31052137/29341952-69641c0c-8230-11e7-959f-6584984f7757.png)
- Press Release button
![image](https://user-images.githubusercontent.com/31052137/29341965-8a070a14-8230-11e7-9c72-be9eabc7c07b.png)

Result:
Hype is increased by 10 without doing anything
![image](https://user-images.githubusercontent.com/31052137/29341977-a25a7d80-8230-11e7-8d1e-20f2099851cb.png)

**Comment by jhovgaard** [comment]
Fixed. Now required to at least remove or add 1 feature.
