### ISSUE TITLE
Manager's employee disappeared

### ISSUE THREAD

**Issue by blaineterror** [hovgaardgames/startupcompany#560]
The Affected employees options at HR Manager menu are not appearing.

![image](https://user-images.githubusercontent.com/31052452/29342459-448bf14a-8201-11e7-9090-5281974abcad.png)

When I unselect one of the managers (Chad Barton), the list appears correctly, but without Chad's employees.

![image](https://user-images.githubusercontent.com/31052452/29342645-41f54aa2-8202-11e7-9a19-029224a54349.png)

For some reason, one of the employees managed by Chad has disappeared. In the image below you can see that it is appearing that he is in charge of all employees (8/8), but only 7 are appearing managed by him.

![image](https://user-images.githubusercontent.com/31052452/29342719-b3291b0e-8202-11e7-9df2-9768ee85577e.png)

One of the employees "physically" disappeared:
![image](https://user-images.githubusercontent.com/31052452/29342779-21b883e8-8203-11e7-94f0-28283e63e4e5.png)

**Comment by johannwagner** [comment]
Hey, 

your bug was reported from another user.
You can see more information, quick fixes, and ideas at #608.

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann
