### ISSUE TITLE
Localization bugs: Brazilian Portuguese

### ISSUE THREAD

**Issue by blaineterror** [hovgaardgames/startupcompany#561]
I've found some texts that are not localizated for Brazilian Portuguese. I will add some suggestions for them below.

**HR Manager menu:**
_Managers to control_ = Controle de Gerentes
_In charge_ = Responsável
_Affected employees_ = Funcionários gerenciados
_Name_ = Nome
_Schedule_ = Horário
_Mood_ = Humor
![image](https://user-images.githubusercontent.com/31052452/29342925-1e4a82aa-8204-11e7-8388-659baa285255.png)

**Inbox:**
_Inbox_ = Caixa de Entrada (or just Entrada if the text box is small)
_List_ = Lista

![image](https://user-images.githubusercontent.com/31052452/29343093-4495a09c-8205-11e7-841f-53c3a0d87e15.png)

Module development:
Some of the components don't fit in the text box. I guess the best way is to increase text box sizes, but here are some suggestions to try to fit without loose its meaning.
_Filesystem component_ = Componente de Arquivos
_Database component_ = Componente de DB
_Search Algorithm component_ = Componente de Busca

![image](https://user-images.githubusercontent.com/31052452/29343142-9d62ee64-8205-11e7-8272-84f8f2af4706.png)

![image](https://user-images.githubusercontent.com/31052452/29343155-b1536eda-8205-11e7-8bb5-60ee38c065a2.png)

![image](https://user-images.githubusercontent.com/31052452/29343193-ebef0f7c-8205-11e7-84c2-c3d04c0d01e8.png)

**Product menu:**
Lowercase at first letter
_idade_ = Idade
_versão_ = Versão

![image](https://user-images.githubusercontent.com/31052452/29343427-4fe654da-8207-11e7-9ce7-cc6beac4d915.png)

Hope those suggestions fit well. :)

**Comment by johannwagner** [comment]
Hey, 

your bug was reported from another user.
You can see more information, quick fixes, and ideas at #602.

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann
