### ISSUE TITLE
Item duplication

### ISSUE THREAD

**Issue by bouixl** [hovgaardgames/startupcompany#562]
Steps(everything happens on the same employee):
- Pause the game
- Launch the craft of any module you have the components for
- Click on any other module you don't have components for, close windows about not having enough components
=> The items used in the first craft will have been refunded, but the craft will still be ongoing if you unpause the game

You can duplicate as many times you want as long you don't unpause the game.

**Comment by johannwagner** [comment]
Hey,

thanks for your bug report. I was able to reproduce the bug.
Heads up! Most bugs are resolved within two weeks. 

Regards, 
    Johann

**Comment by jhovgaard** [comment]
Fixed, thanks for reporting!
