### ISSUE TITLE
Stuck on black screen

### ISSUE THREAD

**Issue by MikaFromDenmark** [hovgaardgames/startupcompany#566]
When my workers is done with their tasks, I click "Jump to next day" but is stuck on black screen. I suspect that it's because my business has gone bankrupt, but shouldn't there be a message to notice the player, that is has gone bankrupt? That would be most logical.

I tried to start the time and just let the time flow. It stops at 23:59 and freezes the whole program. No buttons can be touched or clicked. Not even the ESC-button works. You need to completely shut down the game.

I've recorded the bug:

[https://www.youtube.com/watch?v=lp4tUG_B0e8&feature=youtu.be](url)

**Comment by jhovgaard** [comment]
This is simply because of performance, it will continue eventually. 

Are you running the game on a fast machine? It looks like the game is generally laggy in your video.

Check out the testing branch on Steam. I already fixed a lot of the performance problems :-)

**Comment by MikaFromDenmark** [comment]
My computer is not that fast, no. But there has not been any problems before, when clicking "Jump to next day" except for excactly that night - shown in the video - where I will hit -10,000$ the next day.
