### ISSUE TITLE
BUG: Developer: Completed Beginner Items Not Appearing in Inventory

### ISSUE THREAD

**Issue by ViniH** [hovgaardgames/startupcompany#567]
Under certain circumstances when a developer completes a basic item it does not appear in your inventory.

Apologies for the long reproduction steps, I have not yet spent the time to narrow down the precise use case that is causing this issue.

**Reproduction Steps**

1. Start a new game.
1. Pause the game.
1. Hire a developer.
1. Assign developer to a workstation.
1. Purchase and begin work on a basic component.
1. Allow time to advance at normal pace.
1. As the developer is about to finish the component, pause the game,
1. After a few seconds the component will be completed and the bar will reset, but the component is not in your inventory.

**Comment by jhovgaard** [comment]
Fixed. Changed order of lifecycle execution to avoid "empty ticks".
