### ISSUE TITLE
[Display] Delete button overlapping tab

### ISSUE THREAD

**Issue by Flamine** [hovgaardgames/startupcompany#568]
In a product window, "delete" button ("supprimer" in the french version) is overlapping whatever tab is underneath.

![image](https://user-images.githubusercontent.com/2950365/29383585-428deefe-82d1-11e7-9b3b-3cc7dfd3d92f.png)

**Comment by isparia** [comment]
its the marketing tab, and its because french words are too long, so in a fixed frame, the other tabs just get too wide. but you should be able to click it on the megaphone icon.

**Comment by jhovgaard** [comment]
Fixed
