### ISSUE TITLE
Hit "Next Day" and Stuck on black screen but generating investment money every "minute"

### ISSUE THREAD

**Issue by Cwoq** [hovgaardgames/startupcompany#569]
So I hit next day and I am stuck on black screen and every in game minute I am generating 150,000 (which is usually what I get per day from investments) every single in game minute.

**Comment by johannwagner** [comment]
Hey, 

I read your bug report carefully and I wasn't able to reproduce the bug. 
Could you provide us your save game to investigate further into this problem? Additionally, we need more information about your game version and your build number, which is located at Startup Company -> Properties -> Local Data.

Heads up! Most bugs are resolved within two weeks. 

Regards, 
    Johann

**Comment by jhovgaard** [comment]
Closed until savegame provided.
