### ISSUE TITLE
T10 Big table clipping issue

### ISSUE THREAD

**Issue by zerbsama** [hovgaardgames/startupcompany#571]
![Screen](http://i.imgur.com/wekzWl0.png)

**Comment by sanekaze** [comment]
yep same pb here

**Comment by johannwagner** [comment]
Hey, 

your bug was reported from another user.
You can see more information, quick fixes, and ideas at #325 .

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann
