### ISSUE TITLE
64-Bit Support and Lag

### ISSUE THREAD

**Issue by zerbsama** [hovgaardgames/startupcompany#572]
According to the Windows Resource monitor is this game 32 bit. Why? Or better, could this get switched to 64 bit? 

furthermore, it does lag, creating "hiccup" like situations, employees are switching between working and "unused" or however the English term is... The game freezes except for the shaking animation of the "unused" sign above their heads.

**Comment by johannwagner** [comment]
Hey, 

thanks for your enhancement ideas. 
You should get rid of the lag after the next performance update with Beta 12.7.

Regards, 
    Johann

**Comment by jhovgaard** [comment]
Thanks for reporting!

The upcoming performance update will hopefully fix most of your lag issues.

As there is no difference in performance between 32-bit and 64-bit I'm only building the game for 32-bit atm. I'll enable 64-bit if/when we are able to take advantage of it.

Best,
Jonas
