### ISSUE TITLE
Suggestion: slim down completed upgrades

### ISSUE THREAD

**Issue by zerbsama** [hovgaardgames/startupcompany#573]
If I upgrade a Service / Feature to the max and can not "invest" anything into the current version of it, why keeping it "full sized"? It also creates the heavy load on the game whenever the interface is opened.. on Animus 2018 it can even slow down the game heavily.

**Comment by johannwagner** [comment]
Hey, 

I did not get your point. Could you explain your point more detailed?
Also, what is meant by Animus 2018?

Regards,  
   Johann

**Comment by jhovgaard** [comment]
The upgrade feature is now deprecated. Thanks for reporting.
