### ISSUE TITLE
Lights during Nighttime (bug or missing feature?)

### ISSUE THREAD

**Issue by zerbsama** [hovgaardgames/startupcompany#574]
since we can adjust the timetable when to work (-- is there a shared desk mod anywhere ? --) we can have workers in the Building at Nighttime. But if I have employees in the building during Nighttime (i.E. between 23:00 and 5:00) the screen gets awfully dark, basically, they are "energy efficient" and don't like the lights of the room? Or is there no roof and no light in the Building? I wouldn't be able to work without at least some light to see the keyboard in front of me...

**Comment by johannwagner** [comment]
Missing Feature is fitting, I think.

**Comment by jhovgaard** [comment]
Promoted to idea: https://startupcompany.cnflx.io/public/ideas/948
