### ISSUE TITLE
Changing office = need to buy again all the furniture

### ISSUE THREAD

**Issue by Kalytis** [hovgaardgames/startupcompany#575]
There is no "Stock" in the shop, which means that if we change our premises, we have to buy again all of the stuff we previously got. This is a shame, given a medium table costs 5.500$.
I believe a "Stock" in the shop would actually be needed.

Excellent game, though !

**Comment by Kalytis** [comment]
Alright... Didn't see what it said about selling all the goods when moving out. My bad.

**Comment by markrichey** [comment]
Hi @Kalytis you should have an option near the bottom of your screen to mark this as closed now.
