### ISSUE TITLE
I finished the game in 8 hours.

### ISSUE THREAD

**Issue by FransiS17** [hovgaardgames/startupcompany#577]
Hi! i get the level 20 in 8 hours playing, And I've unblocked everything. Wtf!!??
![captura](https://user-images.githubusercontent.com/31109008/29426493-1a2d504c-8387-11e7-8ad5-787f99a50ace.PNG)
?

**Comment by johannwagner** [comment]
This is an early access title. More Content will be added, soon. Thanks for your report !
