### ISSUE TITLE
HR Manager menu no longer shows all employees

### ISSUE THREAD

**Issue by ImYourFavourite** [hovgaardgames/startupcompany#579]
I'm not sure how to describe it, except that you can no longer send many employees on vacation.

<img width="804" alt="screen shot 2017-08-17 at 9 07 31 pm" src="https://user-images.githubusercontent.com/17707864/29440091-1dec4b26-8390-11e7-9989-2aba8de854ef.png">

The only thing that fixes it is unchecking and rechecking one of the managers that the HR manager is in charge of.

<img width="801" alt="screen shot 2017-08-17 at 9 08 59 pm" src="https://user-images.githubusercontent.com/17707864/29440125-54b3fb40-8390-11e7-8fdd-8a676b541134.png">

When you skip to the next day, it disappears again?

<img width="801" alt="screen shot 2017-08-17 at 9 11 10 pm" src="https://user-images.githubusercontent.com/17707864/29440166-a07eaf98-8390-11e7-8ba7-8e4db3228af9.png">

Otherwise I can't stop playing it. My roommate and I are both ADDICTED

**Comment by kileycouch** [comment]
also experiencing the exact same issue but with 3 different managers

**Comment by bmoondesign** [comment]
Same issue here. Really hard to manage employees now

**Comment by ImYourFavourite** [comment]
For me it turned out that I was using intermediate desks instead of expert desks, which fixed it for me

**Comment by johannwagner** [comment]
Hey, 

thanks for your bug report!

Regards, 
    Johann

**Comment by jhovgaard** [comment]
The issue has been fixed and will be included in the next update.

Thanks for reporting!
