### ISSUE TITLE
BUG DEV Mod

### ISSUE THREAD

**Issue by pifortif** [hovgaardgames/startupcompany#582]
Hello when I throw the game in mode developer impossible to play because the game remains blocked on the screen of load also after deinstallation and reinstallation of the game nothing do not still change the same problem.

Can give me an help please

Bye pifortif

**Comment by johannwagner** [comment]
Hey,

I have no clue how you broke the game this way. You can disable your Steam Cloud and remove the options.json file from your save game folder. 

Let me know, if this solves your problem. 

Regards,  
  Johann
