### ISSUE TITLE
Bug: I can't see my saved games

### ISSUE THREAD

**Issue by Erickelleon** [hovgaardgames/startupcompany#583]
![2017-08-19](https://user-images.githubusercontent.com/31165860/29489171-4dbe3e46-84cf-11e7-80e1-59e75ddc341c.png)

I don't know but since yesterday i can't see ma saved games that part is empty
(sorry the bad english no is my first languaje but nothing skpeak spanish here)

**Comment by johannwagner** [comment]
Same as #446.
