### ISSUE TITLE
unable to sort by employee level

### ISSUE THREAD

**Issue by kileycouch** [hovgaardgames/startupcompany#584]
![image](https://user-images.githubusercontent.com/31166149/29489262-82a5a232-84ea-11e7-8d75-75e5e9475a2d.png)

**Comment by johannwagner** [comment]
Hey,

thank you for your bug report.
I am sure, Jonas will look into that issue if other bugs are resolved.

Regards,
Johann

**Comment by jhovgaard** [comment]
The issue has been fixed and will be included in the next update.

Thanks for reporting!
