### ISSUE TITLE
Savegames gone 

### ISSUE THREAD

**Issue by Percy84** [hovgaardgames/startupcompany#585]
played today new game after update... NO SAVEGAME IN. 3hrs gaming lost :(
please add at least a manual save function 
THANKS

**Comment by JoshLWScott** [comment]
Had the same issue yesterday, saved files dissapeared after a couple hours.

**Comment by johannwagner** [comment]
Hey, 

your bug was reported from another user.
You can see more information, quick fixes, and ideas at #586.

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann
