### ISSUE TITLE
No difference between normal time and sped up

### ISSUE THREAD

**Issue by jonesy497** [hovgaardgames/startupcompany#587]
Time moves really fast with no difference between the normal speed button and the fast forward button.

**Comment by johannwagner** [comment]
Hey, 

that is part of the performance optimization. Time goes slower if the calculations need more time as usual.

Regards, 
    Johann

**Comment by jonesy497** [comment]
Hi

I'm not sure I understand. What's the purpose of the Fast forward button?

Thanks
Catrin

Sent from BlueMail<http://www.bluemail.me/r?b=10455>
On 24 Aug 2017, at 12:19, Johann Wagner <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey,

that is part of the performance optimization. Time goes slower if the calculations need more time as usual.

Regards,
Johann

**Comment by jhovgaard** [comment]
Fixed by updating UI time twice when fast forwarding.
