### ISSUE TITLE
Black screen after restart

### ISSUE THREAD

**Issue by jonesy497** [hovgaardgames/startupcompany#588]
If you fail a game and try to start a new game in the same session, it loads the new game with a black screen which allows you to see everything and do normal stuff, but you can't see the office. I had to close the game and reopen it in order to start a new game.

**Comment by johannwagner** [comment]
Hey, 

I read your bug report carefully and I wasn't able to reproduce the bug. 
We need more information about your game version and your build number, which is located at Startup Company -> Properties -> Local Data.

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann

**Comment by jhovgaard** [comment]
Thanks for reporting! I'm closing until we have more info about the issue.
