### ISSUE TITLE
Needs more info

### ISSUE THREAD

**Issue by jonesy497** [hovgaardgames/startupcompany#589]
I can understand not having a tutorial as it makes it a bit more challenging, however some of the features don't have any clue at all as to what they mean or do. I think it needs a lot more info pop ups when you hover over a thing e.g. the star when hiring staff, the percentage etc.

**Comment by johannwagner** [comment]
Hey, 

Jonas wants to create a clean game without many popups or tutorials. Could you provide more examples, that Jonas is able to make the game more intuitive?

Regards, 
    Johann

**Comment by jonesy497** [comment]
Hi

I was thinking more like a little dialogue box that just appears as you hover the mouse over a table column, to explain what it is, like the Star that shows up next to employees or the percentage when looking at applicants, etc. They don't need to be invasive or disruptive, as they don't need to contain much text at all (e.g "level" or "employee level") and they could be set to only appear after the mouse has been over the specified area for x seconds, rather than immediately, so it's obvious that the player wants to see them.

Thanks
Catrin

**Comment by jhovgaard** [comment]
Promoted to idea: https://startupcompany.cnflx.io/public/ideas/532
