### ISSUE TITLE
erreur au démarage du jeu

### ISSUE THREAD

**Issue by ejcc82** [hovgaardgames/startupcompany#591]
ceci apparaît depuis aujourd'hui et n'apparaissait pas hier
![bug startup](https://user-images.githubusercontent.com/31175637/29492438-a366175e-857b-11e7-8fc1-3957ffddb440.jpg)

**Comment by johannwagner** [comment]
Please phrase your bug reports in English, German or Danish. This is an error by a mod you installed earlier. Please inform the creator of the mod.
