### ISSUE TITLE
Suggestion Benefits costs should be by Employee 

### ISSUE THREAD

**Issue by isparia** [hovgaardgames/startupcompany#592]
Its way to cheap to push the productivity in a large company. 
I think the cost should be by employee, this way it raises with the number of people you have just in real live. For that you could lower the costs.
Costs could be calculated by the wage of the employee, equally to the productivity boost it gives you.
we come in total up to 35% productivity boost from the benefits, so we would pay per employe 35% of their wage to gain this.

**Comment by johannwagner** [comment]
Hey, 

I read your enhancement idea carefully. 
We let the community decide if they want or don't want the feature. 

Everyone can vote under this post with :thumbsup: and :thumbsdown: . 

Regards, 
    Johann

**Comment by jhovgaard** [comment]
This is actually already happening. All employee based benefits costs are calculated by the amount of employees.
