### ISSUE TITLE
Bad Turkish translation

### ISSUE THREAD

**Issue by Cyerol** [hovgaardgames/startupcompany#594]
There are too many mistakes in translation

**Comment by AnnaisFay** [comment]
Hi Cyerol,

The turkish translation is actively being made by a few people of our community. Rest assured that it will be error free at some point. If you'd like to contribute, feel free to join the Discord and help them out in the #turkish text channel. :)

Regards
Anna

**Comment by johannwagner** [comment]
Translation is a mod. Please report problems to Steam Forums of the mod.
