### ISSUE TITLE
no item made with night worker

### ISSUE THREAD

**Issue by sanekaze** [hovgaardgames/startupcompany#595]
Hi and sorry for my bad english

I have two design worker, one on day and one on night, on the same graphic component item

On day no problem, items are made to 7-15pm, but on the next morning, no items were made by the night worker on 17-00pm hours. 

For exemple, 7 items at 15pm, and always 7 items on the next days

Can you help me about that?
Edit: same pb for all my 3 night design workers, all my night développement workers.. 

Thanx

PS: Error on french traduction on one word in the price description of the recruitment window

Do i need to make specific topic about that?

**Comment by johannwagner** [comment]
Same as #489.
