### ISSUE TITLE
Numbers don't show in the Turkish Translation

### ISSUE THREAD

**Issue by mehmetgulsen** [hovgaardgames/startupcompany#596]
When you pick the Turkish as the language of the game, numbers are broken. Here are the ones I could see at a first glance:

- "Managing 3 employes" message for the Managers and HR Managers.
- Day counter in the load save screen.
- Number of users and profit amount of the products on the top right of the screen.
- The production time of a component or similar stuff when mousing over to select production.
- Prices of furniture in the shop.

Instead of the numbers that should have been displayed, there are text like "{miktar}" or "{gun}" .

There are more like the ones I have listed but they're really obvious and easy to spot. If it is needed, I can provide screenshots and list other similar numbers that are broken.

**Comment by johannwagner** [comment]
Please report those failures to the creator of the Turkish Mod.
