### ISSUE TITLE
Contract work hours for modules not included

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#597]
" When a contract shows the 'price per hour' for bids (and normal contracts?) - does it include the hours needed for all of the components required to make a module?

It seems that the more modules a contract has, the less overall profitable it is, since it doesn't seem to account for the cost to build the components of the modules themselves.

Basically - the 'work time' should be cost of making all items in the contract, and the time to make the subcomponents as well.

Thanks !
 MindALot.
"

**Comment by johannwagner** [comment]
I reviewed your code from Beta 11.12 at this point and I am quite sure, that this is a point.

**Comment by anderschbe** [comment]
Definitely confirmed, and very critical. A backend module (4h backend component, 6h network component, 10h module) counts as 10h only. Which makes it a really bad deal.

**Comment by jhovgaard** [comment]
The issue has been fixed and will be included in the next update.

Thanks for reporting!
