### ISSUE TITLE
Game crashes in 2 hour intervals

### ISSUE THREAD

**Issue by Matamanthemaster** [hovgaardgames/startupcompany#598]
I have played the game for four hours in total now. This has been split up into two sessions of two hours because of crashing. Playing the steam version, now with 261 in-game days after the second crash, and 99 days after the first crash. It appears to start lagging just before the crash in spikes, that may be linked to work station processes. When I start getting lag it starts off with minor spikes, and cumulatively increases over time until the crash. After the second crash I noticed that lag spikes only started occurring closer to the crashes. My game can be loaded from saves after crashing, but I think maybe a button to manually save should exist for piece of mind when closing the program.

**Comment by jhovgaard** [comment]
Hi there,

Beta 12.7 has been released since you created this issue. It solves the black screen/skip-to-next-day bug.

Please let me know if you still experience the problem.

Best,
Jonas

**Comment by Matamanthemaster** [comment]
First time I launched the game since the update. I started a new company and I got to about 150 days, and the game crashed again. It did not get progressively worse like last time, but there were occasional, short lag spikes. They did not seem as frequent as prior.
