### ISSUE TITLE
Users dont grow during Vacation

### ISSUE THREAD

**Issue by isparia** [hovgaardgames/startupcompany#600]
If you send your whole company on a 3 Day vacation the usergrow stops even with a hype above 90%

![image](https://user-images.githubusercontent.com/30974730/29534194-6098834a-86b5-11e7-9575-fff6ed2ba1d0.png)

Addition:
this only seems to happen when you send your whole company on vacation and press the jump to the next day, (it jumps to the end of the vacation)

**Comment by InDieTasten** [comment]
I can confirm this happens. I would like to see this fixed :)

**Comment by jhovgaard** [comment]
The issue has been fixed and will be included in the next update.

Thanks for reporting!
