### ISSUE TITLE
Sale Executive bug (at leats I guess it is) 

### ISSUE THREAD

**Issue by cutekiwi** [hovgaardgames/startupcompany#601]
Hey, 

I recently encountered a bug with my sale executive girl. I closed the game probably during a bid. When I oppened it again, I clicked on the girl, selected the next contract and the pic that i linked to my post showed up on my screen. Nowhere to click to accept the contract, how can i do ?

![image](https://user-images.githubusercontent.com/31220415/29534547-b2958f2a-86b6-11e7-9eda-2c736cf3025c.png)

**Comment by isparia** [comment]
can confirm that, had this aswell today, only way to get rid of it is to fire her

**Comment by johannwagner** [comment]
Known Bug.

Same as #516.
