### ISSUE TITLE
I ONLY WANT YOU TO SAY THAT IN YOUTUBE THERE ARE PEOPLE GIVING YOUR GAME AND I TELL YOU BECAUSE I KNOW YOU ARE A PERSON WHO IS EXPECTING MUCH.

### ISSUE THREAD

**Issue by carlos30053** [hovgaardgames/startupcompany#603]
I JUST WANT YOU TO KNOW THAT IN YOUTUBE THERE ARE PEOPLE GIVING YOUR GAME AND I TELL YOU BECAUSE I KNOW YOU ARE A PERSON WHO IS EXPECTING MUCH.

**Comment by jhovgaard** [comment]
Thank you for the info!
