### ISSUE TITLE
30:Uncaught SyntaxError: Identifier '_modPath' has already been declared

### ISSUE THREAD

**Issue by lsfritz** [hovgaardgames/startupcompany#604]
Bottom toolbar is completely gone. The game is full of coding language instead of a normal form.

**Comment by isparia** [comment]
@lsfritz do you have any mods enabled?

**Comment by lsfritz** [comment]
Yes, I have. But after taking all mods off, the problem remains. T-T

**Comment by isparia** [comment]
hmmm that's weird.
could you provide a list which mods you had enabled, then i would check it on my side too and take a look if i can get the same behavior.

What you also can try is to reinstall the game, but make a backup of your savegames first. 
you can find them here: 
(on Windows) C:\Users\<YourUserName>\Saved Games\Startup Company\ 
they should look like this
![image](https://user-images.githubusercontent.com/30974730/29601178-6541ff0e-87da-11e7-8c38-776edf3a5ff5.png)

I would do it like this
1. Copy the save games to secure location
2. Delete the Startup Company Folder
3. Deinstall the Game
4. Check if all Gamefiles are gone
5. Install the game again, and give it a try (this should generate a save games folder again)
6. If all looks ok copy you savegames back into the savegames folder

**Comment by jhovgaard** [comment]
This is 100% a mod causing problems. Removed everything in %USERPROFILE%\Saved Games\Startup Company\mods and everything should be good :-)

**Comment by lsfritz** [comment]
Problem solved. I deleted all of the Mods file and resubscribed the mods i need. Everything back to normal :)  I have about 127M subscribers for my products <3
