### ISSUE TITLE
[BUG] Can't play anymore (easy to reproduce)

### ISSUE THREAD

**Issue by skol-pro** [hovgaardgames/startupcompany#606]
I created a backup for a saved game by duplicating and appending .backup before JSON extension.
File name looks like `sg_83f3f1b2-f.backup.json`.

The load screen IG is now blank, forever, even if I remove the file and remove everything from `options.json`...

Basically, I can't play anymore, just by doing that :-D ... >:-(

Console error:
`
Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: saveGame in ctrl.saveGames | orderBy: '-day' track by saveGame.id, Duplicate key: 83f3f1b2-f, Duplicate value: {"id":"83f3f1b2-f","companyName":"Skol Dev Inc","gameover":false,"fileName":"sg_83f3f1b2-f.backup.json","day":84}
`

**Comment by johannwagner** [comment]
You have to move savegames out of the folder. 

Same Bug as #446
