### ISSUE TITLE
|BUG| Tier 13 to Tier 17

### ISSUE THREAD

**Issue by hitfan** [hovgaardgames/startupcompany#607]
I was Tier 13 and after i get 100%, i was  Tier 17.

**Comment by LucasMateijsen** [comment]
I have the same issue. As far as I can tell, it does not have any 'conditions' to show this behaviour. Basically going a tier up from 13 will put you on Tier 17 right away.

**Comment by jhovgaard** [comment]
Fixed, each tier will now increase XP requirement by 20-30% per tier for Tier 13-20.
