### ISSUE TITLE
[Bug] Crew disappear

### ISSUE THREAD

**Issue by adbforlife** [hovgaardgames/startupcompany#608]
Sometimes when I try to sell tables some other random member disappears (like forever gone and I have to re-employ one)

E.g., I was selling a manager's table to get a better one, and a senior developer and his table were gone.. (happened multiple times)

**Comment by johannwagner** [comment]
I experienced that bug, too.

**Comment by jhovgaard** [comment]
Was fixed in 12.7. It used to happen when hovering items while pressing `DELETE`.
