### ISSUE TITLE
Saved Games location

### ISSUE THREAD

**Issue by Mitrail** [hovgaardgames/startupcompany#609]
Saved games are stored on C:\Users\name which seems to be the location for files written in %userprofile%.
Note : by Saved games I mean \Saved Games\ and all its files and sub-folders

However, %userprofile% can refer to multiple location.
In my case, in explorer.exe it refers to 
C:\Users\name (SSD) and D:\User (HDD).
Note: echo %userprofile% in cmd.exe only return C:\Users\name.
 Almost every other games store saves in D:\User\Documents.

First issue : saved game should be in D:\User rather than C:\Users\name
Second issue : for consistency reasons, it should be preferable to locate them in users' "documents" folder rather than profile folder.

**Comment by johannwagner** [comment]
Hey, 

we talked yesterday about your problem in Discord, too.
This is a very specific problem. Windows should save games at `C:/Users/Mitrail/Saved Games/Startup Company`.

I am sure, Jonas will look into that issue if other bugs are resolved. 

Regards, 
    Johann

**Comment by Mitrail** [comment]
The "Saved Games" folder is created by the game (dates if creation are the same) so I assumed that this folder was part of the save files. 
I indeed have C:/Users/Mitrail/Saved Games/Startup Company
but it could be preferable to have **D:**\User\ **Documents**\Saved Games\Startup Company
It was unclear so I'm adding a note to the main post.

**Comment by jhovgaard** [comment]
Hi there,

The game use the `homedir` path returned from Windows. I'm using the Saved Games special folder introduced since Vista (https://en.wikipedia.org/wiki/Special_folder).

Is it possible for you to get the correct path using any of Windows' path variables?

**Comment by HighfiveJae** [comment]
Hi there Jonas,

I might be experiencing a related issue except that I'm on Mac OS. I just loaded my game this morning after playing for almost 8 hours yesterday and it only shows Day 18 from my load files. More than happy to help investigate this further, but I'd need a little guidance.

Thanks,
Jae

**Comment by jhovgaard** [comment]
@HighfiveJae I do believe the save issue you experienced has been fixed by atomic saving. 

@Mitrail I'm closing this issue. If you find a Windows path variable that gives you the path, I can update the game to support it too. Just update this issue and I'll reopen.

Thanks for reporting!
