### ISSUE TITLE
Turn of Mods Without Unsubing

### ISSUE THREAD

**Issue by GameDevTycoon1** [hovgaardgames/startupcompany#610]
it will be nice to be able to turn mods off when you are recording games to youtube and the turn them on after recording to your privet game

instead to have to unsub and then sub agian

**Comment by johannwagner** [comment]
Hey, 

I read your feature request carefully. 
We let the community decide if they want or don't want the feature. 

Everyone can vote under this post with :thumbsup: and :thumbsdown: . 

Regards, 
    Johann

**Comment by GameDevTycoon1** [comment]
👍

**Comment by Sleme** [comment]
👍

**Comment by jhovgaard** [comment]
Promoted to idea: https://startupcompany.cnflx.io/public/ideas/523

**Comment by jhovgaard** [comment]
Closing issue. Idea is starting to build up votes.
