### ISSUE TITLE
suggestion: the money system

### ISSUE THREAD

**Issue by Brixt18** [hovgaardgames/startupcompany#611]
the money system is very bad at play time, please fix that. I'm play and the money low very fast. The game say "game over" xd

**Comment by johannwagner** [comment]
Hey, 

Could you provide us your save game to investigate further into this problem? Additionally, we need more information about your game version and your build number, which is located at Startup Company -> Properties -> Local Data.

You should get multiple messages before getting bankrupt. I experienced a similar bug.

Heads up! Most bugs are resolved within two weeks. 

Regards, 
    Johann

**Comment by AdwinVL** [comment]
Once you settled down your company and you have a good inventory, you should only go for high urgency jobs, the pay is way better. I'm in late stage of the game and I still only need 1 Beginner Sales Executive to survive financially.
