### ISSUE TITLE
Glitches in Graphics

### ISSUE THREAD

**Issue by bcombs95** [hovgaardgames/startupcompany#612]
Just wanted to say quick, that I placed a conference table and then I tried placing the glass walls around it but the glass walls ended up layer behing the table so it looks like the table is sitting on top of the glass.

Thanks

**Comment by johannwagner** [comment]
Hey, 

your bug was reported from another user.
You can see more information, quick fixes, and ideas at #325.

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann
