### ISSUE TITLE
Ads button hidden

### ISSUE THREAD

**Issue by Ryflew** [hovgaardgames/startupcompany#613]
Hi,

In the "our project menu" i can't see the "ads" button (only the the icon) because the red delete button is on them.
I have the game in french.

**Comment by johannwagner** [comment]
Hey, 

your bug was reported from another user.
You can see more information, quick fixes, and ideas at #568 .

Heads up! Most bugs are resolved within two weeks. 
If you think, that I closed your bug without reason, please message me on Discord (TupperBox).

Regards, 
    Johann
