### ISSUE TITLE
White screen after load

### ISSUE THREAD

**Issue by anderschbe** [hovgaardgames/startupcompany#615]
I encountered a rather weird bug. Whenever I load the attached save, I get a white screen. A superficial scan with a json analyzer didn't reveal any obvious errors, so maybe you might be able to gain more information from it.

![white screen](https://user-images.githubusercontent.com/26141445/29743427-3577665a-8a92-11e7-8689-3b553acaaa5a.png)
[sg_d9f62a0e-c.zip](https://github.com/hovgaardgames/startupcompany/files/1253840/sg_d9f62a0e-c.zip)

**Comment by jhovgaard** [comment]
Looks like Steam update failed. Please click the "Verifiy Integrity of Game Files" under Startup Company's Steam Properties.

**Comment by RedstoneRaudi** [comment]
Hey, can you try to reinstall the game?
If Steam is reporting you a file permissions error you can write it here and I can send you a solution for fixing it.

**Comment by anderschbe** [comment]
Neither an integrity check nor a reinstall did anything to the problem. The game works fine with other saves. So either the save file is corrupt (which I'm hard pressed to see given it's a simple json file), or it's something weird that kicks the renderer in the behind. Sorry if I can't give more precise info. There isn't even an error message of any kind, just that white screen.

**Comment by RedstoneRaudi** [comment]
Can you launch the game in Devmode? There should open a console. Are there any errors?
In my opinion it would be easier if you join the official discord. There it's more easy to communicate.
https://discord.gg/A2gpWVf
