### ISSUE TITLE
Product Counter No longer Fluid

### ISSUE THREAD

**Issue by bcombs95** [hovgaardgames/startupcompany#616]
This is just another small thing that I wouldn't expect you to get to any time soon, but since the game updated to 12.7 today, when I went back into my game the user counter and the $/day from the product counter is  no longer increasing in a fluid motion (i.e 1,2,3,4,5 has turned into 1,3,6,8). It still increases but its not as smooth, it jumps to higher numbers. Like I said it's a small thing that I noticed when i went back in today.

Other than that you've made a great game and keep up the great work!

Thanks, 
bcombs95

**Comment by Scholle1309** [comment]
could be work as intended, less calculations for the game = better performance

**Comment by AdwinVL** [comment]
A slight random number increase seems more realistic to me then a constant fluid increase. If it really is more random now, i'm very happy they changed it.

**Comment by bartusek27** [comment]
Hi **bcombs95**,

I see what you mean, but I am affraid this was intended. Is there someone that doesn't like it too?

Thanks and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Increased update rate in Beta 13.
