### ISSUE TITLE
Wrong inventory overrides

### ISSUE THREAD

**Issue by RedstoneRaudi** [hovgaardgames/startupcompany#618]
Open an empty contracts overview -> don't close it and click on an dev -> http://i.imgur.com/VYbM3JD.png

If there is an open inventory of any type of employee and you are opening other uis without closing the old one -> http://i.imgur.com/8gC30Rk.png (it's an dev)

I hope these short instructions are helpful for reproducing the bug :)

**Comment by jhovgaard** [comment]
Fixed!
