### ISSUE TITLE
Suggestion: Employee adaption system

### ISSUE THREAD

**Issue by werkain** [hovgaardgames/startupcompany#619]
This is just a suggestion but im thinking that perhaps it would be more immersive if the employees get better and faster at producing a specific product depending on how much theyve made it. Kinda like a skill system. Just a thought.

**Comment by RedstoneRaudi** [comment]
That would be a nice idea. I would definitely like this feature.

**Comment by bartusek27** [comment]
Hi **werkain**,

first off, thank you so much for giving us this cool suggestion! Let's open a discussion, who else like it too?
Definitely suggest this for voting @ [https://startupcompany.cnflx.io/public](https://startupcompany.cnflx.io/public)!

Thank you and have a great fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Added as public idea: https://startupcompany.cnflx.io/public/ideas/854
