### ISSUE TITLE
Called in sick looping

### ISSUE THREAD

**Issue by kitsps** [hovgaardgames/startupcompany#620]
First, I saw one employer's status showing "Called in sick". Then, everyone in the office has that status too.
I saw a lot of reimbursements because the game stuck in a loop.
Finally, I became bankrupt. So I have no reason to continue playing except restarting the game.

**Comment by bartusek27** [comment]
Hi **kitsps**,

first off, thank you so much for reaching to us! I see your problem, but for better replication of your problem, could you send us your savefile?

How to find it: (If using Windows)
1. Go to C:/Users/\<your name\>/Saved Games/Startup Company
2. There, you should see your savefile in .json format
3. Rename filetype to .txt (GitHub won't allow us to upload .json)
4. Attach it to your reply

Thanks for your report, can't wait to hear from you back!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
The issue has been fixed and will be included in the next update.

Thanks for reporting!
