### ISSUE TITLE
White screen after computer crash

### ISSUE THREAD

**Issue by sanekaze** [hovgaardgames/startupcompany#621]
Hi,
My computer juste crash while playing. 
Now, i got a white screen on startup.
Tried to uninstall and reinstall, same issue

Discuss with redstonraudi on discord who try to help and active the dev mode, but no developermode line in the options.json.
Add it manually, start the game, same issue white screen
Delete startup company folder in C:\Users\Moi\Saved Games\Startup Company and still white screen on startup.

Win10 x64 / Game version 12.7 updated yesterday

If you can help, thanx :)

**Comment by sanekaze** [comment]
![nvidia share_2017-08-27_17-54-16](https://user-images.githubusercontent.com/31188520/29751825-3bb462ea-8b53-11e7-9a07-fe92ba546a8f.png)

**Comment by jhovgaard** [comment]
Fixed by wiping %appdata%\Startup Company. Added automatic clean up on launch to avoid future problems.
