### ISSUE TITLE
Achievements still locked in steam

### ISSUE THREAD

**Issue by sanekaze** [hovgaardgames/startupcompany#622]
Hi,
I reached some of the achievements of the game but they're still locked on steam
game version 12.7

![steam_2017-08-27_18-23-03](https://user-images.githubusercontent.com/31188520/29751913-c858a188-8b54-11e7-86d4-99f5e3775127.png)

**Comment by Scholle1309** [comment]
Same here: 

It's Something
Complete your first contract

Same But Different
Install 1 mod

Install All The Mods
Install 5 mods

**Comment by jhovgaard** [comment]
Fixed!
