### ISSUE TITLE
Meeting Table Stuck

### ISSUE THREAD

**Issue by AdwinVL** [hovgaardgames/startupcompany#623]
Hi, there is a series of actions i did and it got the Meeting Table stuck, unable to select it again and it is currently phasing through the wall. I can select the coffee tables behind it, but not the meeting table itself. I checked the whole map to see if i could get a hover focus effect anywhere, but that didn't work. It's a ghost object now and it's possible to place anything on top of the ghost object. I don't even know if i get the office bonus.

<img width="424" alt="schermafbeelding 2017-08-27 om 21 01 26" src="https://user-images.githubusercontent.com/6034389/29753129-ee89ed92-8b6a-11e7-9088-01e378b585c7.png">

So this is what i did. First I selected it with a right click, planning to move it. rightclicked again on accident (so it rotated) and then rappidly clicked left mouse button without actually ever moving my mouse. I guess it didn't get the time to check if it was a correct placement or not.

In my understanding, It could be possible that the positioncheck is linked with onmousemove. If not, i am of no help :) so good luck, hope you can fix it!

Oh yeah, i'm using Mac OSX El Capitan version 10.11.6 
Graphic Card: AMD Radeon R9 M370X 2048 MB
Build Number: 2070277
Version: 12.7 (I think... It updates automaticly because of steam)

**Comment by bartusek27** [comment]
Hi **AdwinVL**,

first off, thank you so much for your report!
I am notifying you, that I couldn't exactly replicate your problem. I've actually found out that by your technique, I can place Meeting Table on Coffee Machine, but it was on proper depth.

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by mxdumas** [comment]
Hi barusek27,

I'm also having depth issues with the meeting table. See the screenshot. By the way, congratulations on this game. Very nice work! :)

Maxime

![image](https://user-images.githubusercontent.com/6152473/29998250-402e1992-8ff4-11e7-8917-7e898f8fbf09.png)

**Comment by jhovgaard** [comment]
Fixed in Beta 13.

Thanks for reporting!
