### ISSUE TITLE
Upgrading Functions Only uses 1 module per upgrade.

### ISSUE THREAD

**Issue by Cieronpowell** [hovgaardgames/startupcompany#624]
To Upgrade a function the GUI says it requires x modules eg. For Mobile Login System upgrade, requires 23 backend modules, when upgrade is pressed it only takes 1 upgrade module out of inventory. Leaving inventory with 22 backed modules.

**Comment by Scholle1309** [comment]
Same as #510

**Comment by jhovgaard** [comment]
#504 actually. Closing this one :-)
