### ISSUE TITLE
Furniture freezing

### ISSUE THREAD

**Issue by ChloeCakes** [hovgaardgames/startupcompany#625]
When I try to place a desk, it "freezes" the game, I can move my mouse and click on finance views but it only display "clcik or or right click..." and the trash can icon. It very much makes the game unplayable or it wouldnt be an issue

**Comment by bartusek27** [comment]
Hi **ChloeCakes**,

first off, thank you so much for your report!
I am notifying you, that I couldn't replicate your problem. If it happens to anyone else, please open this issue.

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27
