### ISSUE TITLE
Achievement Bug

### ISSUE THREAD

**Issue by adriannab99** [hovgaardgames/startupcompany#627]
Achievements "It's Something," "Same But Different," and "Install All the Mods" are not registering on Steam when completed in-game. Additionally, I am also experiencing the furniture glitch where it cannot be placed when being selected through the buying screen and effectively freezes the game.

**Comment by Scholle1309** [comment]
Already fixed in the upcoming version

**Comment by bartusek27** [comment]
Hi **adriannab99**,

first off, thank you so much for your report!
I am notifying you, that this problem has already been fixed in the newest version.

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27
