### ISSUE TITLE
Translate Issue

### ISSUE THREAD

**Issue by premaliang** [hovgaardgames/startupcompany#629]
After uploaded mod to steam workshop. The message shown in pop up window is not in the json file.
![2017-08-28 20 16 36](https://user-images.githubusercontent.com/5953493/29773185-d367de60-8c2e-11e7-8a25-671813d26663.png)

**Comment by bartusek27** [comment]
Hi **premaliang**,

first off, thank you so much for your report!
I can confirm that it is missing, so I hope it will be fixed as soon as possible!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
The issue has been fixed and will be included in the new update.

Thanks for reporting!
