### ISSUE TITLE
I literally run through the game at day 96 or so.

### ISSUE THREAD

**Issue by xshinkux** [hovgaardgames/startupcompany#630]
I just got from day 95 to 96, and all of sudden nothign worked, the workes were doing nothing and so on, so i decided to restart the game in the hope to fix the problem.

Instead of fixing the problem it made it even worse, in not even starting up the save game. 

As example, i chose "saved games (or so)" and i chose my actual save game at arround day 96.
It didn´t even load up instantly, i had to "continue" manually.

As i pressed Continue, it appeared a white screen, with the interface shown, like the menu at the bottom on the top right corner the zoom options etc. 

Everything except my "company" with all the workers and buro was shown. 

I tried to start up a new game, to look if the save game had a problem or the whole game, it appeared to be a save game error that is occuring. 

The newly set up game went perfectly without issues. 

After finding that out, i tried to "relogin" inot the not working save game. 

This time clicking on continue, made a error message show up. 

In the error message was displayed: 1:Uncaught TypeError: Cannot read property 'name' of undefined

![image](https://user-images.githubusercontent.com/31417628/29787559-b2ed0484-8c2f-11e7-881b-3460a0aa5068.png)

**Comment by jhovgaard** [comment]
Hi there,

 Can you send me your savegame? It's located in %USERPROFILE%\Saved Games\Startup Company\ and the file starts with sg_.

Best,
Jonas
