### ISSUE TITLE
Screen scaling (Game-breaking bug)

### ISSUE THREAD

**Issue by deoster** [hovgaardgames/startupcompany#631]
I have 4K 17inch gaming laptop. The text is insanly small and there is no option for UI scaling or changing to lower resolution in-game. Please implement either of these features ASAP, it's absolutly unplayable on my screen.

**Comment by bartusek27** [comment]
Hi **deoster**,

first off, thank you so much for your report!
I can confirm that large resolutions are problematic, so I hope it will be fixed as soon as possible!

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
Fixed, Big UI is now available in Options.

Thanks for reporting!
