### ISSUE TITLE
I can not use the modes

### ISSUE THREAD

**Issue by Cettin** [hovgaardgames/startupcompany#632]
I can not use the modes that I have installed in the Steam workshop two days ago while I can. Is this the reason for the new update?

**Comment by hippophil** [comment]
same for me

**Comment by bartusek27** [comment]
Hi guys,

first off, thanks for your report, we appreciate it! To help you, I am affraid I'll need more help. Can you provide me with the names of not working mods? Also, on what version are you right now?

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
This should have been fixed in latest build.

Please let me know if you're still experiencing problems.
