### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by Niels54380** [hovgaardgames/startupcompany#633]
I download the version 1.12 on my 1st PC
after, i download the version 12.8 on my 2nd PC
Can i have the save of my 1st PC on my 2nd??
please help me

**Comment by bartusek27** [comment]
Hi **Niels54380**,

first off, thank you so much for your question!
May I ask you why you have different versions on your devices? Steam should get your game updated automatically.

Once again, thank you and have fun playing Startup Company!
Take care,
bartusek27

**Comment by Niels54380** [comment]
(sorry, i was mistaken, on my 1st PC, i had the version 11.2,  not 1.12^^) 
my 1st computer hasn't any more network ( he is disconnected... and i can't have it again... I download SC and after i automatically disconnectc it this story is complicated, i know ! ^^)
so can i have my save without steam or network??

**Comment by jhovgaard** [comment]
Hi @Niels54380 

Enable Steam Cloud Save and your savegame gets transferred automatically.

Best,
Jonas
