### ISSUE TITLE
Mods not loading into game

### ISSUE THREAD

**Issue by Pinksheep1236** [hovgaardgames/startupcompany#634]
I downloaded a few mods for the game and I quit the game and came back on, but the mods didn't load.  I tried it again it was the same result, I tried it 3 times and every time when i looked in the mods tab it would say that I had no mods and when I played the game thinking it was a glitch no mods were active.

**Comment by gaubuchon** [comment]
The game os overwriting and deleting the mods fold in Application Support/savedata on OS X on each restart.

**Comment by bartusek27** [comment]
Hi premaliang,

first off, thank you so much for your report!
Because I can't test it (I have no Apple device), I will report it straight to the developer. It looks like it's game's issue.

Once again, thank you for this report and have fun playing Startup Company!
Take care,
bartusek27

**Comment by jhovgaard** [comment]
This should have been fixed in latest build.

Please let me know if you're still experiencing problems.
