### ISSUE TITLE
Cant Fast Forward to next Day

### ISSUE THREAD

**Issue by pragaras** [hovgaardgames/startupcompany#637]
Since Day 500 i cant fast forward to next day. 
If i do, the screen gets black and will never go away.

Uninstalling all mods didnt help

**Comment by Geekolas** [comment]
I've the same but, it's after asking to my employes to do 24h journey to test... (With 100% mood Mod)

**Comment by jhovgaard** [comment]
Mods can easily mess up your savegame and break the game. Feel free to attach your savegame here. I'll fix it then.

Best,
Jonas
