### ISSUE TITLE
Startup Company Load issue 

### ISSUE THREAD

**Issue by leei50** [hovgaardgames/startupcompany#639]
Hello, 

I previously was on the game last night and was closing on 100k contracts. Exceeding more profit than I have currently. For some reason it the cloud server wont load my last gameplay and it keep starting me back to my day 161. Can this be fixed ? 

Thanks, Leei

**Comment by jhovgaard** [comment]
Hi there,

Sorry for the late reply. Did this happen once, or did it continue to happen?

Thanks,
Jonas

**Comment by leei50** [comment]
Hello,

And Once.

**Comment by jhovgaard** [comment]
The issue has been fixed and will be included in the next update.

Thanks for reporting!
