### ISSUE TITLE
Office problems

### ISSUE THREAD

**Issue by GamerFranceTheo** [hovgaardgames/startupcompany#640]
Hello ,
 here is a little worry with this office I can not select it to delete it how to do?

Codialement,
![desktop 09 09 2017 - 12 06 39](https://user-images.githubusercontent.com/9782846/30239231-50084a72-9558-11e7-9c02-2d4f6f6b2e80.jpg)

**Comment by jhovgaard** [comment]
Fixed!

Thanks for reporting.
