### ISSUE TITLE
Can't fast forward vacation

### ISSUE THREAD

**Issue by Fjzon** [hovgaardgames/startupcompany#641]
I have a HR manager which made the decision to send **all** employees on vacation. At the same time I sent the HR manager on vacation. You usually get the opportunity to fast forward until everyones back. But since I got the HR manager it doesn't seem possible.

**Comment by InDieTasten** [comment]
If anyone stumbles across this via search, skipping the vacation does in fact work, but you need to make sure, that all employees are on vacation. In the HR Manager interface, you can only send people to vacation, that are assigned to the HR Manager or the managers of the HR manager.
