### ISSUE TITLE
mods aren't working

### ISSUE THREAD

**Issue by Agterberg** [hovgaardgames/startupcompany#642]
the workshop mods on **steam** aren't working.
on **the modspage in the game** aren't any mods but i **subscribed** to them.
can you please fix it or give instructions.

**Comment by AntoineBel** [comment]
Same for me, I'm on OS Sierra Mac

**Comment by danielsetreus** [comment]
Same. Mac OS Sierra.

**Comment by uguralp** [comment]
Same issue. Mods don't work on my mac os. I don't know if it's just a mac issue, but clearly, it's problem for all users. I hope you fix this issue soon. Have a good work!

**Comment by jhovgaard** [comment]
Should be working now. Please let me know if you're still having problems with latest version (12.10).
