### ISSUE TITLE
Grow users in product

### ISSUE THREAD

**Issue by Jaastorqui** [hovgaardgames/startupcompany#643]
if you click on the button for spend day, the growers are stopping, but if do not click its working

**Comment by jhovgaard** [comment]
Hi there,

Can you show me a screenshot of the problem? I'm not sure I understand.

**Comment by InDieTasten** [comment]
I think he's trying to say, that skipping time doesn't keep product users increasing. That is definitely true for when I skip vacation. For normal day night, I'm not sure, but it might still simulate growth of user base over night.

**Comment by jhovgaard** [comment]
The issue has been fixed and will be included in the next update.

Thanks for reporting!
