### ISSUE TITLE
UI Placement Issue with small objects

### ISSUE THREAD

**Issue by markrichey** [hovgaardgames/startupcompany#644]
Hello,

Tiny tiny issue so please don't give it much priority!
I don't seem to be able to get the plant into the corner of the 1st office space, have put a sofa their fine but not the plant. Tried rotating it etc but it seems almost like it has the same size as the sofa!

![screen shot 2017-09-11 at 22 13 30](https://user-images.githubusercontent.com/12082867/30297154-b25ef738-973e-11e7-8a60-042e67d3e501.png)
![screen shot 2017-09-11 at 22 14 01](https://user-images.githubusercontent.com/12082867/30297155-b261240e-973e-11e7-803b-f458f86221a4.png)
![screen shot 2017-09-11 at 22 14 09](https://user-images.githubusercontent.com/12082867/30297156-b26577b6-973e-11e7-8e4c-6c42364f55a8.png)

Many thanks!
Mark

**Comment by jhovgaard** [comment]
Fixed :-)
