### ISSUE TITLE
New localization not shown in options

### ISSUE THREAD

**Issue by premaliang** [hovgaardgames/startupcompany#646]
I'm doing traditional Chinese localization. In v12.9, in main menu->options->Language, the Tradition Chinese is not shown even mod is loaded. Only default language
 is shown.
I try Japanese localization, same issue.

![2017-09-23 23 21 10](https://user-images.githubusercontent.com/5953493/30774496-f37039dc-a0b5-11e7-9672-23cbb94bdd27.png)
![2017-09-23 23 22 10](https://user-images.githubusercontent.com/5953493/30774501-0f3f15e8-a0b6-11e7-9810-e0a3e69f6238.png)

**Comment by jhovgaard** [comment]
Hi there,

Are you the author of the mod? If it's not showing it's a problem with the mod it self.
