### ISSUE TITLE
Attempt to select workstation to place bugs out

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/startupcompany#648]
https://youtu.be/OvDD5Hx87nw?t=3m30s

**Comment by InDieTasten** [comment]
This also happened to me once, when I was picking up an object using right click

**Comment by jhovgaard** [comment]
Interesting. Any idea how to reproduce it?

**Comment by jhovgaard** [comment]
Should have been fixed now be implement isodom.js
