### ISSUE TITLE
PT1: Improvement calculations bug

### ISSUE THREAD

**Issue by EEsmash** [hovgaardgames/startupcompany#654]
When using a lead dev to improve instances there are several bugs:

If you directly switch from quality to efficiency or vice versa you don't get the components back.

Tested with landing page: 

When you start improving but got 0 backend/network components and cancel it you will get 1 of each.

When you start improving and have only 1 backend/network component and cancel it you will get another 1 so you have 2.

**Comment by jhovgaard** [comment]
All fixed :-)
