### ISSUE TITLE
Contract number stuck at "NaN" on new game 

### ISSUE THREAD

**Issue by johan-buret** [hovgaardgames/startupcompany#664]
on Beta 13.9 , the default version, every contract show up as "#Nan" on a new game.

The problem is on  the getContractNumber function that behaves unexpectly with an empty contract list
```
>>> GetRootScope().Helpers.GetContractNumber
< ()=>_.last(GetRootScope().settings.contracts.map(e=>e.number).sort())+1

>>>GetRootScope().Helpers.GetContractNumber()
< NaN 
```

even worse, when a contract gets attached with a `number `property   set to `NaN `,  this non-value comes last with the sort

**Comment by johan-buret** [comment]
Also, another bug triggered on the save : 
```
GetRootScope().settings.contracts.map(e=>e.number).sort()
(18) [0, 0, 0, 0, 0, 10, 10, 10, 10, 10, 10, 10, 10, 5, 6, 7, 8, 9]
GetRootScope().settings.contracts.map(e=>e.number).sort( (x,y)=> Math.sign(x-y) )
(18) [0, 0, 0, 0, 0, 5, 6, 7, 8, 9, 10, 10, 10, 10, 10, 10, 10, 10]
```

**Comment by jhovgaard** [comment]
Thanks for reporting! Fixed, will be shipped with Beta 14.
