### ISSUE TITLE
Add mods to workshop

### ISSUE THREAD

**Issue by maddoctor1905** [hovgaardgames/startupcompany#677]
Hi,
I create a mod for startup company but i have absolutely no idea about how adding it to the workshop of this game.
Anyone can help me about that ?
thanks !

**Comment by rremo** [comment]
> When you're done creating a mod, all you have to do is click the "Upload to Steam" button. The currently logged in Steam account will be the owner of the mod, and every time you launch Startup Company from this account you will be able to update the mod directly from the game:

See: http://steamcommunity.com/games/606800/announcements/detail/1442694218413163678

For creating mods: https://github.com/hovgaardgames/startupcompany/wiki/Modding

**Comment by SyncMasta** [comment]
Hi there,

i do not have such a button when i created a new mod.

Syncmasta

2017-12-28 12:15 GMT+01:00 Remo <notifications@github.com>:

**Comment by XMGamingMaster** [comment]
This bug is already known. 
You have to create a ownerId.txt inside your mod folder and the content has to be your steamID64.
The "upload to steam" button should be visible after a game restart.

**Comment by jhovgaard** [comment]
Fixed in the upcoming Beta 13.11
