### ISSUE TITLE
Keep selected components in employee inventory instead of public inventory

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#69]
To be able to reserve components to specific Lead Devs, enabling you to really see what is still available when planning productions.

**Comment by bretterer** [comment]
jhovgaard.  I would rather see this.  IF your lead developers are being managed by a manager, do the merges from the manager and they will send the merge requests to an open lead developer that knows how to do that merge.  Then you can stack a queue of merges from the manager to the lead developer

**Comment by InDieTasten** [comment]
I don't know about that. Might be a bit confusing.

**Comment by bretterer** [comment]
@InDieTasten just a thought from me playing the latest beta to make game play a little easier when merging.

**Comment by BrutalCSkakan** [comment]
I approve your idea @bretterer. This should maybe be a late-game functionality though?

**Comment by InDieTasten** [comment]
@bretterer I was referring to OP, not you, hence no mention ;)

**Comment by jhovgaard** [comment]
Thanks for your inputs guys. I'll get back to this task later (when doing T3 content).

**Comment by jhovgaard** [comment]
This issue is irrelevant now, since Lead Devs will "spent" components when merging starts. Closing.
