### ISSUE TITLE
[MOD] Add more Virtual Server Types

### ISSUE THREAD

**Issue by petrachi** [hovgaardgames/startupcompany#697]
Hi ! 

I wanted to create a mod to add more "virtual server" types, because with 128ms response time + 772m users + 0.01CU/ms, it needs 32 "Large Virtual Cluster" to run. So upgrade a product from there is quite a challenge, since most of the "features" add a lot of response time, and buying 100+ "Large Virtual Cluster" is neither easy to do in-game, or practical.

My problem is : I don't find where I should add the new values. I looked an long time to all the JS objects I could find, And I event though that I found the right place with the `Components` Object, as "Server" is listed under `ComponentTypes`, but I could not find the already existing servers listed there. I also looked for something called `Modules`, as a guess from what I could read on [issue#163](https://github.com/hovgaardgames/startupcompany/issues/163), but with no more luck. 
So, where should I put these values ?

Ho, and great game BTW. I quite enjoy it !

**Comment by jhovgaard** [comment]
Hi petrachi,

It's currently not possible to add custom servers, but will be by April 12 when Beta 15 is released.

Feel free to catch us in #modding at our Discord server for more info: https://discord.gg/hovgaardgames

Best,
Jonas
