### ISSUE TITLE
Inventory components not centered

### ISSUE THREAD

**Issue by BrutalCSkakan** [hovgaardgames/startupcompany#70]

**Comment by InDieTasten** [comment]
Pretty sure this is a duplicate, though I can't find the corresponding issue for that

**Comment by InDieTasten** [comment]
@jhovgaard Please close, if confirmed as already being fixed as part of another issue. I'm just 100% sure I've seen an issue with a screenshot where there was no space on the left of the items

**Comment by jhovgaard** [comment]
Not relevant in new view.
