### ISSUE TITLE
[Feature] [Modding] Better error reporting

### ISSUE THREAD

**Issue by cpeosphoros** [hovgaardgames/startupcompany#700]
Hi there, first of all, great game, great mod functionality. I hope you can keep your enthusiasm and carry the game out of early access with great success.

I've just installed half a dozen mods from Steam and got this upon running the game:

```
Sorry, something bad happened!
Try uninstall all mods
Error:

file:///~/.local/share/Steam/steamapps/common/Startup%20Company/resources/app/index.html(1:1):Uncaught SyntaxError: Unexpected token < in JSON at position 0

Close

```
My suggestion is that the error message should point to the offending file. As it is, I can't pinpoint which one is causing the problem without either linting all json files or switching on/off each mod - which is a pain, but that is another issue.

**Comment by jhovgaard** [comment]
Hi cpeosphoros,

You're absolutely right. I'll look into improving this in Beta 16.

Best,
Jonas
