### ISSUE TITLE
[Feature] [Modding] Toggle mod on/off instead of unsubscribing

### ISSUE THREAD

**Issue by cpeosphoros** [hovgaardgames/startupcompany#701]
As the title says, it would be nice to be able to toggle mods on/off, instead of outright unsubbing them from the Workshop.

The option to directly unsubbing at the mod manager is nice, but sometimes I just want to toggle something off for a while, and having to go back to the workshop page to re-enabling it is a real pain.

**Comment by jhovgaard** [comment]
Hi again,

The feature is currently up for voting over at Conflux: https://startupcompany.cnflx.io/public/ideas/523

Feel free to give a vote :-)

Best,
Jonas
