### ISSUE TITLE
[Modding]Sample Furnituremod won't build

### ISSUE THREAD

**Issue by hthroweriii** [hovgaardgames/startupcompany#702]
I tried to install the sample mod from [here](https://github.com/hovgaardgames/startupcompany/wiki/Modding). After installing the mod and  restarting the game in dev mode(using the "--dev" argument) I see an error in the console.

> furniture mod failed: TypeError: Database.items.push is not a function

I changed the code in the start.js file from:
`    Database.items.push({});
`
to
`    Database.items.coffeetable = 
        {...} ;
`

and now it is working. Am I the only one having this issue or is the wiki just out of date?

Version: 14.2 beta
OS: Mac OS Sierra 10.12.6

**Comment by jhovgaard** [comment]
Hi hthroweriii,

Thanks for reporting. I've fixed the furnituremod. The link has been updated, so simply download the zip again.

Best,
Jonas
