### ISSUE TITLE
Add HR Manager

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/startupcompany#77]
HR Manager allows you to:
- Control working hours (make all employees work at the same time)
- Automatically send employees on vacation when required

HR Managers control managers, so you first need to control the employees by managers.

**Comment by WodeCraft** [comment]
The HR Manager is part of the Beta 7 but it doesn't seem to have any function, is that correct?
I can see my two other managers in his list, but I can't do anything with them.

**Comment by InDieTasten** [comment]
@WodeCraft Correct. It's there, but not implemented yet. Referring from #190

**Comment by jhovgaard** [comment]
Done
