### ISSUE TITLE
Missing number formatting

### ISSUE THREAD

**Issue by joakimbugge** [hovgaardgames/startupcompany#98]
As the attached screenshot shows, not all numbers are formatted, which causes somewhat poor readability. The format should probably be localized as well.

![image](https://cloud.githubusercontent.com/assets/2697311/19220283/43ed6f14-8e2a-11e6-999e-0d7bcc3381b6.png)

Let me know if you want me to list unformatted numbers.

**Comment by InDieTasten** [comment]
@joakimbugge That would be really nice of you if you would do that. But before you do, maybe wait until @jhovgaard sets this issue on s:approved.

**Comment by jhovgaard** [comment]
@joakimbugge That would be awesome, yes please! All approved 👍

**Comment by jhovgaard** [comment]
Areas removed, closing this one.
